### ISSUE TITLE
volumes are doubled for Grouped Daily ( Bars )

### ISSUE THREAD

**Issue by skyscraper** [polygon-io/issues#10]
**URL**
https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2020-05-08

**Result**
The volumes returned are inaccurate (some are roughly doubled, others are roughly tripled)
For example, SPY volume for the date above (May 8, 2020) came back as 153,568,475

**Expected Result**
Expected results are to have accurate volumes (compared against both Yahoo Finance and Marketwatch)
For example, SPY volume listed for the date above (May 8, 2020) is published on Yahoo Finance as 76,452,400 and on Marketwatch as 76.62M.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: CentOS
 - Browser n/a
 - Version n/a

**Additional context**
I was told this is also related to the duplicate events coming through the websocket trades feed, so I'm assuming when this issue is fixed, that the websocket issue will be fixed as well. If this is inaccurate, I can open an additional bug, just let me know.

**Comment by jrbell19** [comment]
This is a known issue. We have a few different solutions that we will be testing over the next few days to mitigate the incorrect data. The underlying issue is the duplicate packets that we are receiving on a network level. Apologies for the inconvenience.

**Comment by shjoshi95** [comment]
> This is a known issue. We have a few different solutions that we will be testing over the next few days to mitigate the incorrect data. The underlying issue is the duplicate packets that we are receiving on a network level. Apologies for the inconvenience.

Last I heard, the solutions would be tested and deployed by the end of this coming weekend. Is that still the plan? Really would like to see this one fixed ASAP

**Comment by jrbell19** [comment]
> > This is a known issue. We have a few different solutions that we will be testing over the next few days to mitigate the incorrect data. The underlying issue is the duplicate packets that we are receiving on a network level. Apologies for the inconvenience.
> 
> Last I heard, the solutions would be tested and deployed by the end of this coming weekend. Is that still the plan? Really would like to see this one fixed ASAP

We have tested a few different solutions that haven't worked, and are continuing to implement a solution as quickly as possible. We really appreciate your patience.

**Comment by shjoshi95** [comment]
> > > This is a known issue. We have a few different solutions that we will be testing over the next few days to mitigate the incorrect data. The underlying issue is the duplicate packets that we are receiving on a network level. Apologies for the inconvenience.
> > 
> > 
> > Last I heard, the solutions would be tested and deployed by the end of this coming weekend. Is that still the plan? Really would like to see this one fixed ASAP
> 
> We have tested a few different solutions that haven't worked, and are continuing to implement a solution as quickly as possible. We really appreciate your patience.

Any ETA for next round of testing for the fix?

**Comment by qrpike** [comment]
This will be solved with our deployment tonight, which means tuesday ( monday is trading holiday ) this should be fixed.

**Comment by shjoshi95** [comment]
> This will be solved with our deployment tonight, which means tuesday ( monday is trading holiday ) this should be fixed.

Thanks for the followup! If a deployment happened last night, why is that the fixed aggregations cannot be accessed right now over the weekend, and that the start of a new trading day is required to query historical data?

**Comment by qrpike** [comment]
We reconcile aggregates EOD to make sure everything is correct. So after midnight those aggregates should have been updated. I can confirm this has been fixed in production and should not see any more duplicate volume. If this persists, please re-open.

**Comment by shjoshi95** [comment]
> We reconcile aggregates EOD to make sure everything is correct. So after midnight those aggregates should have been updated. I can confirm this has been fixed in production and should not see any more duplicate volume. If this persists, please re-open.

Hi, from what I can see with hourly data today, the issue seems to have been fixed. But when trying to query from some older daily data, it seems that every other row is showing double-counted volume. Here is an example:

https://api.polygon.io/v2/aggs/ticker/MSFT/range/1/day/2020-04-01/2020-05-14?unadjusted=false&apiKey=KEY

Please correct me if I have misunderstood, but is the fix only guaranteed to work for new aggregations going forward from the time of this most recent deployment?
