### ISSUE TITLE
Missing historic data before 4 days ago.

### ISSUE THREAD

**Issue by blackr2d** [polygon-io/issues#102]
**URL**
https://api.polygon.io/v1/historic/crypto/BTC/USD/2020-02-08?limit=10000&apiKey=...

Many other aggregate or tick data tried, all empty.

**Result**
Empty result
{'day': '2020-02-08',
 'map': {'c': 'conditions',
  'p': 'price',
  's': 'size',
  't': 'timestamp',
  'x': 'exchange'},
 'msLatency': 1,
 'status': 'success',
 'symbol': 'BTC-USD',
 'ticks': None,
 'type': 'crypto'}

**Expected Result**
Data present

**Desktop (please complete the following information):**
Not relevant

**Additional context**
Support confirmed data is missing and being backfilled in the chat. Opening the issue to track the progress.

**Comment by jrbell19** [comment]
Hi there, 

This is actually an issue that we are currently working to resolve. We are migrating the currencies data to a new database, so until that is complete this data will be unavailable. We are shooting to have this complete within the next week or so. 

Really sorry for the inconvenience.

**Comment by jrbell19** [comment]
Crypto data is available again back to May of 2017.

**Comment by blackr2d** [comment]
What historical data is available? Trades, aggregates? For all available pairs? How can I verify it, I do not wish to pay again just to discover most data is missing. I have paid previously for a whole month, is there a chance to reactivate the API key to test?

**Comment by blackr2d** [comment]
Thank you, solved.
