### ISSUE TITLE
Ticker details (company, sector, industry, etc) missing for 149 stocks

### ISSUE THREAD

**Issue by tr8dr** [polygon-io/issues#103]
**URL**
Ran the following REST call to get __company information__ on 1700 stocks with the appropriate substituted ```symbol``` and ```apikey```.  These stocks were the S&P 500 stocks + 1200 of the highest volume stocks outside of the S&P 500.

https://api.polygon.io/v1/meta/symbols/$symbol/company?apiKey=$apikey

**Result**
Of the 1700 stocks, 149 came back with __404 Not Found__.   The stocks with missing information are:

ACA, AFYA, ALC, ALEC, ALLO, AMCR, APG, ARCE, ATCO, AVLR, AVTR,
BBIO, BEST, BHC, BILI, BILL, BIPC, BJ, BKNG, BKR, BNTX, BYND, CARR,
CBRE, CCEP, CDAY, CGC, CHNG, CHWY, CHX, CPRI, CRON, CRWD,
CTVA, CVET, CWEN, CWK, DADA, DAO, DBX, DDOG, DELL, DKNG, DOCU,
DOYU, DT, EAF, ELAN, EQ, EQH, EQX, ESTC, ET, EVRG, FHI, FOUR, FSK,
FSLY, FTCH, FTDR, FUTU, FVRR, GFL, GH, GL, GLIBA, GMAB, GO, GSX,
HCR, HUYA, HWC, HWM, IAA, IQ, J, JEF, KC, KDP, KOD, LEGN, LEVI, LHX,
LIN, LVGO, LYFT, MDLA, MRNA, NET, NIO, NKLA, NLOK, NTCO, NVST, NVT
OCFT, ONEM, OPCH, ORCC, OTIS, OVV, OZK, PD, PEAK, PGNY, PING,
PINS, PLAN, PPD, PRSP, PS, PSN, PTON, QRTEA, RAMP, RTX, SBSW, SDC,
SDGR, SLQT, SMAR, SPCE, SPOT, STNE, SUZ, SVMK, TCOM, TENB, TFC, TME,
TT, TXG, VIAC, VIE, VIR, VRM, VRT, VVNT, WELL, WH, WMG, WORK, WTRG,
WYND, XP, YETI, ZI, ZS, XLC

**Expected Result**
The query should have returned with company information for the above instead of 404 Not Found.
<img width="1023" alt="Screen Shot 2020-12-01 at 4 39 20 PM" src="https://user-images.githubusercontent.com/3257426/100800031-fbd45c00-33f3-11eb-93c0-7983b8f3ed53.png">

**Desktop (please complete the following information):**
Not applicable.  Being called from an API

**Additional context**
Note that all of the above are in your database, as the following queries did not fail for each of the stocks above:

https://api.polygon.io/v2/reference/splits/$symbol?apiKey=$apikey
https://api.polygon.io/v2/reference/dividends/$symbol?apiKey=$apikey

All 3 types of query were successful for the majority of the stocks queried.   I also ran the above queries for all 1700 stocks multiple times and had the same results (149 missing stocks / company info).

**Comment by jrbell19** [comment]
This is related to #81 

We are working on our new Symbols API that will ensure that this data is kept up to date and accurate. 

Sorry for the confusion.

**Comment by Stormy110** [comment]
This issue has been resolved with our new Ticker Details vX endpoint.
https://polygon.io/docs/get_vX_reference_tickers__ticker__anchor

Please use this endpoint to query for symbol details in the future.
