### ISSUE TITLE
Missing number of items in the aggregate window

### ISSUE THREAD

**Issue by kmecpp** [polygon-io/issues#105]
**URL**
https://api.polygon.io/v2/aggs/ticker/SPY/range/1/day/2005-01-01/2020-12-07

**Result**
A little over a dozen days don't have an "n" value. Example:
{'v': 70293653.0, 'vw': 356.4524, 'o': 357.5, 'c': 355.33, 'h': 357.72, 'l': 355.25, 't': 1605906000000}

Does no "n" mean zero items or is missing data or something else? It would be helpful if cases like these were explained in the docs.

**Comment by cnaccio** [comment]
Just ran into this issue as well. "n" is not returned when querying aggregate bars using the REST API, but the documentation states otherwise. Is there a workaround in the meantime?

**Comment by cnaccio** [comment]
Actually, could this be related to the edition we're using? I just noticed on the pricing page that trades and quotes is only available in the developer and up plan. I'm currently using Polygon through Alpaca, so not sure which edition that is. Anyhow, just thought I'd mention it in case this is the issue.

**Comment by cnaccio** [comment]
Wanted to report back that I'm now seeing number of trades in the results today. Not sure if the issue is ticker/time dependent, or if it's simply been resolved, but I'll keep an eye on it, and report back any issues.

**Comment by jrbell19** [comment]
This should have been resolved last week. Sorry for the confusion. 

Please let me know if you see anything else out of the ordinary.

**Comment by cnaccio** [comment]
Thanks @jrbell19, all appears good now!
