### ISSUE TITLE
Missing historical data for AAL (before 2013-12-01)

### ISSUE THREAD

**Issue by tr8dr** [polygon-io/issues#106]
**Problem**
The stock AAL should have history back into the 1980s, however the __daily bar__ and __1min bar__ history erroneously __starts in Dec 2013__ instead of the 1980s (or however far back your historical archives for other stocks go).   Furthermore, the "listdate" attribute in the Ticker details query is wrong.

**Result**
Here is the result of a query for 1/2 a month in 2011, coming back with no bars.  A similar query for 1min bars will also come back empty:
<img width="1008" alt="Screen Shot 2020-12-10 at 3 20 38 PM" src="https://user-images.githubusercontent.com/3257426/101825569-c3bbd000-3afb-11eb-9f3a-6be879b1e83d.png">

Here are the ticker details (also wrong):
<img width="1023" alt="Screen Shot 2020-12-10 at 3 19 51 PM" src="https://user-images.githubusercontent.com/3257426/101825607-d209ec00-3afb-11eb-8f65-c03063b62e4f.png">

**Expected Result**
This stock should have historical data going back decades.   (personally I just need the data from 2010 onwards).

**Desktop (please complete the following information):**
 - API based queries

**Comment by jrbell19** [comment]
This is actually an instance where the company was traded under another ticker. American Airlines was previously traded as AMR until they were acquired by US Airways and began trading as AAL in Dec of 2013

https://www.forbes.com/sites/maggiemcgrath/2013/11/15/the-new-american-airlines-lands-a-new-ticker-symbol/?sh=3063f3c07f2e
