### ISSUE TITLE
82 stocks missing history (1min bars)

### ISSUE THREAD

**Issue by tr8dr** [polygon-io/issues#107]
**Problem**
I have loaded historical data for a variety of equities from 2010-01-04 (or 1st listing date, whichever is greater).  Of the 1700 stocks I loaded __82 are missing history__:

__Partial History Missing__

- __AAL__: listed on: 1990-01-01, 1st data: __2013-12-09__, missing __1435 days__
- __AAXN__: listed on: 2001-06-07, 1st data: __2017-04-06__, missing __2649 days__
- __ACHC__: listed on: 1994-03-04, 1st data: __2011-11-01__, missing __666 days__
- __AG__: listed on: 2006-01-04, 1st data: __2010-12-15__, missing __345 days__
- __ALLE__: listed on: 2013-11-18, 1st data: __2013-12-02__, missing __14 days__
- __ALLY__: listed on: 2014-01-28, 1st data: __2014-04-10__, missing __72 days__
- __APTV__: listed on: 2011-11-17, 1st data: __2017-12-05__, missing __2210 days__
- __AY__: listed on: 2014-06-13, 1st data: __2017-11-14__, missing __1250 days__
- __BB__: listed on: 1999-02-04, 1st data: __2017-10-16__, missing __2842 days__
- __BSAC__: listed on: 1997-01-13, 1st data: __2012-04-12__, missing __829 days__
- __BWXT__: listed on: 2015-06-16, 1st data: __2015-07-01__, missing __15 days__
- __CC__: listed on: 1990-01-02, 1st data: __2015-07-01__, missing __2004 days__
- __CHTR__: listed on: 2010-01-05, 1st data: __2010-09-14__, missing __252 days__
- __DXC__: listed on: 2017-03-16, 1st data: __2017-04-03__, missing __18 days__
- __EA__: listed on: 1994-01-03, 1st data: __2011-12-20__, missing __715 days__
- __EHC__: listed on: 1990-01-02, 1st data: __2018-01-02__, missing __2920 days__
- __ENIA__: listed on: 1994-01-03, 1st data: __2016-04-27__, missing __2305 days__
- __EQC__: listed on: 2010-07-01, 1st data: __2014-08-01__, missing __1492 days__
- __EURN__: listed on: 2010-05-28, 1st data: __2015-01-23__, missing __1701 days__
- __FTS__: listed on: 2005-08-02, 1st data: __2016-10-14__, missing __2475 days__
- __FTV__: listed on: 2016-06-13, 1st data: __2016-07-05__, missing __22 days__
- __FWONA__: listed on: 2011-11-29, 1st data: __2017-01-25__, missing __1884 days__
- __FWONK__: listed on: 2016-04-18, 1st data: __2017-01-25__, missing __282 days__
- __GHC__: listed on: 1990-01-24, 1st data: __2013-11-29__, missing __1425 days__
- __GOOGL__: listed on: 2004-08-19, 1st data: __2014-04-03__, missing __1550 days__
- __HFC__: listed on: 1994-01-03, 1st data: __2011-07-01__, missing __543 days__
- __HPE__: listed on: 2015-10-19, 1st data: __2015-11-02__, missing __14 days__
- __IAC__: listed on: 2003-06-23, 1st data: __2016-01-21__, missing __2208 days__
- __INFO__: listed on: 2014-06-19, 1st data: __2016-07-13__, missing __755 days__
- __IOVA__: listed on: 2013-10-23, 1st data: __2017-06-28__, missing __1344 days__
- __IQV__: listed on: 2013-05-09, 1st data: __2017-11-15__, missing __1651 days__
- __ITGR__: listed on: 2000-09-29, 1st data: __2016-07-01__, missing __2370 days__
- __JBGS__: listed on: 2017-07-06, 1st data: __2017-07-18__, missing __12 days__
- __KEYS__: listed on: 1996-06-26, 1st data: __2014-11-03__, missing __1764 days__
- __KL__: listed on: 2016-12-06, 1st data: __2017-08-16__, missing __253 days__
- __LITE__: listed on: 1997-10-16, 1st data: __2015-08-04__, missing __2038 days__
- __LKQ__: listed on: 2003-10-03, 1st data: __2012-05-22__, missing __869 days__
- __LW__: listed on: 2016-11-01, 1st data: __2016-11-10__, missing __9 days__
- __MDLZ__: listed on: 2001-06-13, 1st data: __2012-10-02__, missing __1002 days__
- __MLCO__: listed on: 2006-12-19, 1st data: __2017-04-06__, missing __2649 days__
- __MNST__: listed on: 1995-08-18, 1st data: __2012-01-09__, missing __735 days__
- __MSCI__: listed on: 2007-11-15, 1st data: __2010-07-06__, missing __183 days__
- __MSI__: listed on: 1990-01-02, 1st data: __2011-01-04__, missing __365 days__
- __NEE__: listed on: 1990-01-02, 1st data: __2010-06-23__, missing __170 days__
- __NGVT__: listed on: 2016-05-02, 1st data: __2016-05-16__, missing __14 days__
- __NOMD__: listed on: 2014-09-09, 1st data: __2016-01-12__, missing __490 days__
- __NSP__: listed on: 1997-01-29, 1st data: __2011-03-09__, missing __429 days__
- __NYCB__: listed on: 1993-11-23, 1st data: __2012-11-13__, missing __1044 days__
- __OLED__: listed on: 1996-04-12, 1st data: __2013-06-24__, missing __1267 days__
- __OMF__: listed on: 2013-10-16, 1st data: __2015-11-27__, missing __772 days__
- __ON__: listed on: 2000-04-28, 1st data: __2015-04-06__, missing __1918 days__
- __PBA__: listed on: 2010-10-06, 1st data: __2012-04-02__, missing __544 days__
- __PK__: listed on: 2016-12-22, 1st data: __2017-01-04__, missing __13 days__
- __PYPL__: listed on: 2015-07-06, 1st data: __2015-07-20__, missing __14 days__
- __QQQ__: listed on: 1999-03-10, 1st data: __2011-03-23__, missing __443 days__
- __SCCO__: listed on: 1996-01-05, 1st data: __2010-02-17__, missing __44 days__
- __SPGI__: listed on: 1990-01-02, 1st data: __2016-04-28__, missing __2306 days__
- __SPXL__: listed on: 2008-11-05, 1st data: __2012-06-29__, missing __907 days__
- __SPXS__: listed on: 2008-11-05, 1st data: __2012-06-29__, missing __907 days__
- __SSRM__: listed on: 1996-08-01, 1st data: __2017-08-03__, missing __2768 days__
- __SYNH__: listed on: 2014-11-07, 1st data: __2018-01-08__, missing __1158 days__
- __TCF__: listed on: 1990-01-02, 1st data: __2017-05-08__, missing __2681 days__
- __TCP__: listed on: 1999-05-25, 1st data: __2011-12-12__, missing __707 days__
- __TECK__: listed on: 2006-06-29, 1st data: __2016-12-05__, missing __2527 days__
- __TECS__: listed on: 2008-12-17, 1st data: __2012-06-29__, missing __907 days__
- __TGTX__: listed on: 2012-04-30, 1st data: __2013-05-30__, missing __395 days__
- __TPR__: listed on: 2000-10-05, 1st data: __2017-10-31__, missing __2857 days__
- __TRIP__: listed on: 2011-12-07, 1st data: __2011-12-21__, missing __14 days__
- __UAA__: listed on: 2005-11-18, 1st data: __2016-12-07__, missing __2529 days__
- __VEDL__: listed on: 2013-09-09, 1st data: __2015-05-11__, missing __609 days__
- __VEON__: listed on: 1996-11-15, 1st data: __2017-03-31__, missing __2643 days__
- __VIAV__: listed on: 2015-07-23, 1st data: __2015-08-04__, missing __12 days__
- __VRNT__: listed on: 2002-05-16, 1st data: __2010-07-06__, missing __183 days__
- __VST__: listed on: 2016-11-07, 1st data: __2017-05-10__, missing __184 days__
- __WAFD__: listed on: 1990-03-26, 1st data: __2012-02-21__, missing __778 days__
- __WPM__: listed on: 2005-07-06, 1st data: __2017-05-16__, missing __2689 days__
- __WRK__: listed on: 2015-06-24, 1st data: __2015-07-02__, missing __8 days__
- __WWD__: listed on: 1996-05-31, 1st data: __2011-01-31__, missing __392 days__
- __YUMC__: listed on: 2016-10-17, 1st data: __2016-11-01__, missing __15 days__
- __ZBH__: listed on: 2001-08-07, 1st data: __2015-06-29__, missing __2002 days__
- __ZG__: listed on: 2011-07-20, 1st data: __2015-08-17__, missing __1489 days__

**Sample URL**
https://api.polygon.io/v2/aggs/ticker/AGR/range/1/minute/2010-02-09/2010-03-06?timespan=minute&multiplier=1&stocksTicker=AGR&from=2010-02-09&to=2010-03-06&unadjusted=true&limit=50000&apiKey=__apikey__

**Result**
My query ran from the max of 2010-1-4 or listing date (as per Ticker information query).  # of missing days listed above. 
  
**Expected Result**
Expected that would be able to retrieve bars from the listing date (or 2010-1-4), whichever is later, instead there was a gap from the listing date to the 1min bars available or in some cases there were no bars at all.   See above

**Desktop (please complete the following information):**
 - API based

**Comment by qrpike** [comment]
For QQQ we have answered the issue here: https://github.com/polygon-io/issues/issues/118

We will continue to look into these tickers, but please be aware we store data as it happened. So if there was a ticker change, it will be under the previous ticker symbol. I have stated our coming solution in the GH issue I linked here.

**Comment by qrpike** [comment]
Looking into a couple of these:
- ZG ticker symbol changed from 'Z': https://www.iclub.com/faq/Home/Article?id=444&category=1&parent=0
- ZBH was previously ZMH: https://www.streetinsider.com/Corporate+News/Zimmer+Holdings+%28ZMH%29+Announces+Completion+of+Combination+with+Biomet/10676341.html
- YUMC was spun off and listed on nov-1-2016: https://www.cnbc.com/2016/11/01/yum-china-opens-at-2451-a-share-after-spinning-off-from-yum-brands.html
- WWD was previously WGOV: https://www.bizjournals.com/denver/news/2011/01/26/woodward-governor-drops-the-governor.html

These are just the bottom couple I quickly searched but I'm confident these gaps are due to ticker changes, and not actual gaps in the data itself.

**Comment by qrpike** [comment]
Closing this issue. Feel free to re-open if you can find gaps where there have been no ticker changes.
