### ISSUE TITLE
NBBO Historical Quotes Missing

### ISSUE THREAD

**Issue by bmasterc** [polygon-io/issues#109]
**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/SPY/2020-12-09?reverse=true&limit=100&apiKey=

2020-12-11 is missing too... I tested a few tickers and they are missing data for these days too. I think yall should have some scripts to check for missing data at the very least... Im sure there are more, I just checked for last week.

**Result**
{"results":[],"success":true,"map":{"p":{"name":"bid_price","type":"float64"},"x":{"name":"bid_exchange","type":"int"},"t":{"name":"sip_timestamp","type":"int64"},"f":{"name":"trf_timestamp","type":"int64"},"c":{"name":"conditions","type":"[]int"},"i":{"name":"indicators","type":"[]int"},"s":{"name":"bid_size","type":"int"},"P":{"name":"ask_price","type":"float64"},"S":{"name":"ask_size","type":"int"},"X":{"name":"ask_exchange","type":"int"},"y":{"name":"participant_timestamp","type":"int64"},"q":{"name":"sequence_number","type":"int"},"z":{"name":"tape","type":"int"}},"ticker":"SPY","results_count":0,"db_latency":0}

**Expected Result**
More than 0 results, tick data returns fine for these dates/symbol

**Additional context**
The other days return fine:
https://api.polygon.io/v2/ticks/stocks/nbbo/SPY/2020-12-08?reverse=true&limit=100&apiKey=
https://api.polygon.io/v2/ticks/stocks/nbbo/SPY/2020-12-10?reverse=true&limit=100&apiKey=

**Comment by jrbell19** [comment]
Sorry about this. This data is now available. We are working on resolving the underlying issue.
