### ISSUE TITLE
Bad historical data for stock "ES"

### ISSUE THREAD

**Issue by tr8dr** [polygon-io/issues#110]
**URL**
https://api.polygon.io/v2/aggs/ticker/ES/range/1/day/2010-01-05/2010-01-14?unadjusted=true&sort=asc&limit=120&apiKey=zivQ7TLyrisFjq9Xh7jtgjZs0iScICCF

**Result**
The returned prices are in the 8 - 9$ range, however should be in the 25$ range after split or $50 range without adjustment.

**Screenshots**
<img width="1001" alt="Screen Shot 2020-12-16 at 8 20 35 AM" src="https://user-images.githubusercontent.com/3257426/102355100-67cccd80-3f79-11eb-899f-aaf88fcb9a02.png">

**Desktop (please complete the following information):**
 - API

**Comment by jrbell19** [comment]
It turns ourt that the prices that are returned in this request are not for Eversource Energy, but a completely different company. ES did not begin trading until 2015-02-19. 

We are working on a way to track company ticker changes, delistings, and acquisitions. 

Apologies for the confusion.
