### ISSUE TITLE
Multiple stocks missing splits or have bad splits

### ISSUE THREAD

**Issue by tr8dr** [polygon-io/issues#111]
**Sample URL**
https://api.polygon.io/v2/reference/splits/A?apiKey=...

Stocks with missing splits (so far in my testing):
- A
- CAG
- CPRT (has an erroneous split on 2017-04-10, in addition to the correct 2017-04-11)
- DISCA
- DISCK
- DOV
- HLT (split ratio on 2017-01-04 is incorrect, and 2017-01-03 should not exist I believe)
- HPE 
- HSIC (missing 2019 split)
- JCI (missing 2016 split)
- MET (missing 2017 split)
- NI (missing 2015 split)
- OKE (missing 2014 split)
- PNR (missing 2018 split)
- SPG (missing 2014 split)
- VFC (missing 2019 split)
- VTR (missing 2015 split)

**Result**
Shows no splits or has erroneous splits

**Expected Result**
Missing splits, should have 1 or more splits (depending on equity listed above)

**Desktop (please complete the following information):**
 - API

**Questions**
When should we expect the new "stock meta data" backend that resolves these problems?

**Comment by jrbell19** [comment]
Hi there, 

This is an issue that we are currently working to address. Apologies for the inconvenience. 

I will keep this thread updated as we make progress.

**Comment by tr8dr** [comment]
Also would like to note that the dividends seem off for just about every stock I have looked at.    Are you parsing (or planning to parse) this from EDGAR?   I would be happy to help.

**Comment by jrbell19** [comment]
We currently do not parse this from EDGAR, but that is the plan.

**Comment by Zhan-Li** [comment]
Polygon has missing dividend history in 2020 for a lot of tickers (example: AAPL), so I come here to check whether they actually solve the problem. Yet, both splits and dividends are still missing for relevant tickers, 2 months after the last reply. I guess it is time to switch to a different data vendor. 

And to guys at Polygon, nice API! But you need to get the basics right: Your data needs to to be right.

**Comment by tr8dr** [comment]
@Zhan-Li , I am a user of Polygon as well (and the submitter of the bug report).  The missing data presents a problem for me as well.   What I have done is to:

- use polygon as a basis for market data (which works great)
- pull meta data from yahoo and some other sources (programmatically)

Yahoo is not perfect, however (I've had to manually adjust split information in a few instances);

**Comment by qrpike** [comment]
We are currently rewriting all of our reference data APIs. I believe the dividends issue you mentioned has been fixed, but please confirm. We expect all reference data to be working well by end of Q2. Very sorry about this.

**Comment by spazmodius** [comment]
Maybe related: getting splits for QQQ returns a record that far predates its existence:

`GET https://api.polygon.io/v2/reference/splits/QQQ`

```js
{
  status: 'OK',
  count: 1,
  results: [{
    ticker: 'QQQ',
    exDate: '2000-03-20',
    paymentDate: '2000-03-20',
    ratio: 0.5
  }]
}
```

**Comment by jeremiahritchey** [comment]
@qrpike Do you think you're still on track to meet the end of Q2 date?

> We are currently rewriting all of our reference data APIs. I believe the dividends issue you mentioned has been fixed, but please confirm. We expect all reference data to be working well by end of Q2. Very sorry about this.

**Comment by Azmisov** [comment]
From the slack page: The stock splits endpoint does not seem to match what is shown on NASDAQ's site. E.g. IRCP lists 4:1 ratio on Polygon, while NASDAQ lists 4.29:1

**Comment by jrbell19** [comment]
These splits have been added to our system. Please let us know if you run into any similar issues.

**Comment by mickdewald** [comment]
There are no splits for AMD
