### ISSUE TITLE
Provide documentation about API rate limits

### ISSUE THREAD

**Issue by sharok** [polygon-io/issues#112]
**Describe the bug**
The documentation does not provide any documentation about API request limits.
I have some code that requests symbols and their details. 
Sometimes I get `Too Many Requests` error:
> Call failed with status code 429 (Too Many Requests): GET https://api.polygon.io/v1/meta/symbols/X:ONTUSD/company

**Expected behavior**
The documentation should have information about rate limits.

**Comment by qrpike** [comment]
Thank you for the feedback. This is made clear on the product pages, but we will look into adding this onto the docs as well, depending on your current account plan.

**Comment by bruce-duhamel** [comment]
I reviewed the product pages and it isn't clear what the limits are.

"There is no limit to how much you can use our stock data APIs. No maximum queries per minute or daily call limits on all premium plans."

Under stock pricing, the stocks basic plan is documented to support 5 calls per minute. The remaining plans are unlimited but I'm still seeing 429 Too Many Requests errors on the developer plan.

Can you please clarify when you start throttling requests?

**Comment by jrbell19** [comment]
Could you please share the request IDs that received 429s? This sounds like a bug, which I would be happy to look into.

**Comment by bruce-duhamel** [comment]
```
2021-08-02 12:16:53 DEBUG 375563 https://api.polygon.io:443 "GET /v2/aggs/ticker/C:DZDEUR/range/1/hour/2021-07-30/2021-07-30?apiKey=redacted&limit=1440 HTTP/1.1" 429 206


{'status': 'ERROR', 'request_id': '4503771a712fe5ba1351ba8cc2c3ac35', 'error': "You've exceeded the maximum requests per minute, please wait or upgrade your subscription to continue. https://polygon.io/pricing"}
```

**Comment by jrbell19** [comment]
Ah, I see. The foundation for each subscription and entitlement is the desired asset class. Because you are Subscribed to Stocks Developer and **Currencies Basic**, accessing currencies data will be rate-limited to the 5 req/sec. You will need to upgrade to the Currencies Starter tier to have unlimited access to that data. 

Apologies for the confusion.

**Comment by bruce-duhamel** [comment]
This isn't a currencies API call? I'm requesting aggregate prices for a stock?

**Comment by jrbell19** [comment]
> 2021-08-02 12:16:53 DEBUG 375563 https://api.polygon.io:443 "GET /v2/aggs/ticker/C:DZDEUR/range/1/hour/2021-07-30/2021-07-30?apiKey=redacted&limit=1440 HTTP/1.1" 429 206

You are querying **C:DZDEUR**, which is the Algerian Dinar to the Euro

**Comment by bruce-duhamel** [comment]
Oh! Thanks for clarifying, I'm just mindlessly retrieving what I thought were stock prices, didn't realize I had currencies mixed in there.

**Comment by jrbell19** [comment]
No worries!
