### ISSUE TITLE
Daily and 1min data wrong for equity: *TFC*

### ISSUE THREAD

**Issue by tr8dr** [polygon-io/issues#116]
**URL**
https://api.polygon.io/v2/aggs/ticker/LIN/range/1/day/2011-05-22/2011-10-08?unadjusted=true&sort=asc&limit=120&apiKey=...

**Result**
For both 1min and daily bars, Polygon shows prices in the __$8__ range, however prices should be in the __$26__ range.  The range where they are incorrect spans a 5 month period (where drmean represents the difference in basis points between polygon and other sources)::

<img width="304" alt="Screen Shot 2020-12-31 at 3 35 17 PM" src="https://user-images.githubusercontent.com/3257426/103425054-d0bd6380-4b7d-11eb-92b2-68daf749714f.png">

**Desktop (please complete the following information):**
 - API

**Additional context**
Ping me on slack if you have any questions.  Want to get the corrected data for this period.

**Comment by jrbell19** [comment]
Hi there, 

This is actually a case of an acquisition between BB&T and Suntrust. It seems like you are referencing Suntrust's (STI) share price for this time period. Truist Financial was not traded until 12/06/2019

https://www.iclub.com/faq/Home/Article?id=660&category=27&parent=26

Hope this clears things up.
