### ISSUE TITLE
QQQ gap

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#118]
The aggs is returning no data for QQQ from late 2004 to early 2011

**Comment by qrpike** [comment]
After deeper investigation, this seems to be the desired output. The ticker was changed from QQQQ to QQQ on March 22 2011. I can confirm there is data for QQQQ on the dates in the 'gap' mentioned here. 

We store data exactly as it happened and do not alter historic data. So this is the desired behavior. We are working on a point in time master symbol list which will solve these ticker changes, but more to come on that in the coming weeks.
