### ISSUE TITLE
Stock Financials API returns results that are 1 fiscal year out of date

### ISSUE THREAD

**Issue by sdcoffey** [polygon-io/issues#119]
**URL**
`https://api.polygon.io/v2/reference/financials/TSLA?type=Q&limit=1&sort=-reportPeriod&apiKey=redacted`

**Result**
Quarterly results only as recent as 2020-03-31

```json
{
  "status": "OK",
  "results": [
    {
      "ticker": "TSLA",
      "period": "Q",
      "calendarDate": "2020-03-31",
      "reportPeriod": "2020-03-31",
      "updated": "2020-04-30",
      "dateKey": "2020-04-30",
      "accumulatedOtherComprehensiveIncome": -113000000,
      "assets": 37250000000,
      ...
    }
  ]
}
```

**Expected Result**
I'm expecting to see the most recent quarterly results, including the 2nd and 3rd quarters of 2020.

**Desktop (please complete the following information):**
 - OS: macOS
 - Client: curl 7.64.1

Thanks!

**Comment by jnrbsn** [comment]
Any update on this? I also see out-of-date data. I've checked several large-cap US stocks, and the latest quarter on all of them is either Q4 2019 or Q1 2020. When do you think this might be fixed?

**Comment by jrbell19** [comment]
@jnrbsn No update yet. We have started rebuilding the foundation of all of the reference APIs though. We will incrementally be releasing fixes as they become available. 

Apologies for the ongoing issues.

**Comment by adam-arthur** [comment]
@jrbell19 what does "rebuilding the foundation" mean... is a v2 being released? Or the data is just being updated.

Also hitting this issue :)

**Comment by jcarter326613** [comment]
I'm getting this issue for CLOV
https://api.polygon.io/v2/reference/financials/CLOV?limit=5&type=Q&sort=-calendarDate&apiKey=plY0sAPpTd3QbCYe4oXH4INJ04tdsppF
Most recent report is for 2004-09-30

**Comment by jmeyers44** [comment]
@jrbell19 any update on when this bug might be resolved?

**Comment by kmcminn** [comment]
yeah this is a bummer. was not expexting basic data like P/E, EPS for stock tickers to be useless.

**Comment by jrbell19** [comment]
This is currently being worked on. We are confident in our new [Tickers API,](https://polygon.io/docs/get_vX_reference_tickers_anchor) and have begun parsing through the SEC filings. We are shooting to post an update soon about the state of the reference/tickers endpoint, as well as the future of the financials / corporate actions endpoints. 

We really appreciate your patience as we tackle this. It has proven to be quite an effort.

**Comment by ronald-bohn** [comment]
Performed some testing in an attempt to update some data. Tested 3,608 tickers to see how many were out-of-date. Spoiler alert: it was all of them. I have a complete list if anyone from the polygon team needs it, but my guess is that they are aware, since it appears to be literally 100% of the tickers.

**Comment by jnrbsn** [comment]
@jrbell19 I understand that you're working on a new API to replace this one, but that doesn't mean you can let the old one be broken for months. It was working at some point, so it seems reasonable that you could have done enough work to fix it before trying to rewrite it. Why would I want to use your new API if you have a history of letting your APIs be broken for months at a time? I really like the idea of Polygon, and your APIs seem great in theory, but I haven't been convinced that I can trust your service.

**Comment by jrbell19** [comment]
The reason it has taken so long to update this data is because we are working to parse the filings directly from the SEC Edgar database, which has proven much more cumbersome than originally expected. We pride ourselves on obtaining our data directly from the source, which ultimately means doing things the hard way. 

We are shooting to bring this dataset back up to date by the end of this quarter. Unfortuantely, I do not have any workarounds for the time being.

**Comment by jnrbsn** [comment]
But it was working before. There's data there. It's just outdated. Why couldn't you keep doing it the old way until the new way was ready? Are you saying the old way was not at all fixable?

**Comment by ebobby** [comment]
Will that new data input fix also the ticker details API? It has pretty old market caps and employee head count.

**Comment by wbarksdale** [comment]
Any updates on timeline for this? :)

**Comment by jrbell19** [comment]
Yes, we are getting very close. We are currently parsing 10K and 10Q data directly from the SEC EDGAR database, and will likely have something to show for this in the next few weeks.

**Comment by meberhard** [comment]
Thanks for the update!
Are you able to narrow it down how many weeks this will approximately take?

**Comment by ivanantipin** [comment]
any update on this?

**Comment by jrbell19** [comment]
Yes! I'm happy to announce that we have just released our Updated Financials API. It is still experimental, but you will be able to fetch up-to-date filing information. 
https://polygon.io/docs/get_vX_reference_financials_anchor

**Comment by devangnegandhi** [comment]
Thanks Jack,
I will try out the new endpoint soon and let you know if I have any
questions

Regards,
Devang Negandhi
