### ISSUE TITLE
NBBO Data Missing after 2020-05-12

### ISSUE THREAD

**Issue by freepi** [polygon-io/issues#12]
**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/AAPL/2020-05-12?limit=10

**Result**
{
  "error": "Unknown database error ( Error Code: 001 )",
  "errorcode": "001",
  "status": "ERROR",
  "success": false
}

**Expected Result**
NBBO data returned

**Additional context**
Seems to happen for all symbols, not just AAPL and be ongoing (see followup comment)

**Comment by freepi** [comment]
Now it's doing it for 2020-05-13, which I'm pretty sure was previously working, so it seems like it's not a one-off problem.  Meanwhile, 2020-05-14 seems to be working fine, so the problem seems to have a delay of about a day.

**Comment by jrbell19** [comment]
We are aware of the issue and are working to implement the solution. Sorry for the inconvenience!

**Comment by qrpike** [comment]
@freepi Can you try now?

**Comment by freepi** [comment]
Working great, thanks!
