### ISSUE TITLE
Incorrect price data for RBZ

### ISSUE THREAD

**Issue by jcarter326613** [polygon-io/issues#124]
**URL**
https://api.polygon.io/v1/open-close/RBZ/2019-03-01?unadjusted=false&apiKey=[key]
https://api.polygon.io/v1/open-close/RBZ/2019-03-01?unadjusted=true&apiKey=[key]

**Result**
The close and other values are coming in at the $1 range.
{"status":"OK","from":"2019-03-01","symbol":"RBZ","open":1.17,"high":1.23,"low":1.07,"close":1.14,"volume":105896,"afterHours":1.2,"preMarket":1.25}

**Expected Result**
The actual price at that time as confirmed by thinkorswim and the following URL is in the $9 range.
https://www.advfn.com/stock-market/NASDAQ/RBZ/historical/more-historical-data?current=1&Date1=02/01/19&Date2=06/01/19

**Comment by jrbell19** [comment]
This was caused by a missing split, which has since been added to our DB. 

We are working on a solution to fix the root of this issue, which is open in previous issues. This should return prices as expected now. Apologies for the confusion.
