### ISSUE TITLE
Support Option Data

### ISSUE THREAD

**Issue by nerkka** [polygon-io/issues#126]
**Is your feature request related to a problem? Please describe.**
It will be nice if Polygon can support Stock Option Data.

**Describe the solution you'd like**
REST API
- Historical Option trades, quotes, open interest, IV, etc. 

WebSocket stream 
- Delayed & live option trade and quotes streaming.

**Comment by jrbell19** [comment]
We are actually planning to start supporting options data by the end of Q2. 

Are there any specific features you'd like to see?

**Comment by nerkka** [comment]
> We are actually planning to start supporting options data by the end of Q2.
> 
> Are there any specific features you'd like to see?

That sounds exciting. I'm pretty happy with your REST/WSS API, so I'm pretty sure you have a good plan for Option as well. 

Is `by the end of Q2` sometime around June?

**Comment by alippai** [comment]
I'm interested in the SPX option chain (full) data on 1 minute bar agg level.

**Comment by Peter-Pasta** [comment]
It would be very nice if the historical dataset contains expired contracts as well. 
Looking forward to that endpoint!

**Comment by Peter-Pasta** [comment]
Will this be released at the end of Q2 or is it delayed?

**Comment by jrbell19** [comment]
We're still building the APIs out. It will likely be sometime mid-Q3. Be sure to sign up for notifications and updates at polygon.io/options

**Comment by Peter-Pasta** [comment]
Thank you. Really anticipating this and already subscribed.

**Comment by nerkka** [comment]
Is there a realistic timeline for this?
