### ISSUE TITLE
Missing dividends, even on heavily traded tickers like SPY

### ISSUE THREAD

**Issue by iamthebruce** [polygon-io/issues#128]
**URL**
https://api.polygon.io/v2/reference/dividends/SPY

**Result**
Here's the result of a query on SPY dividends, as you can see, only 23 are listed.

{
 "status": "OK",
 "count": 23,
 "results": [
  {
   "ticker": "SPY",
   "exDate": "2018-12-21",
   "paymentDate": "2019-01-31",
   "recordDate": "2018-12-24",
   "declaredDate": "2018-01-10",
   "amount": 1.435
  },
  {
   "ticker": "SPY",
   "exDate": "2018-09-21",
   "paymentDate": "2018-10-31",
   "recordDate": "2018-09-24",
   "declaredDate": "2018-01-10",
   "amount": 1.323
  },
  {
   "ticker": "SPY",
   "exDate": "2018-06-15",
   "paymentDate": "2018-07-31",
   "recordDate": "2018-06-18",
   "declaredDate": "2018-06-14",
   "amount": 1.246
  },
  {
   "ticker": "SPY",
   "exDate": "2018-03-16",
   "paymentDate": "2018-04-30",
   "recordDate": "2018-03-19",
   "declaredDate": "2018-01-10",
   "amount": 1.097
  },
  {
   "ticker": "SPY",
   "exDate": "2017-12-15",
   "paymentDate": "2018-01-31",
   "recordDate": "2017-12-18",
   "declaredDate": "2017-12-14",
   "amount": 1.351
  },
  {
   "ticker": "SPY",
   "exDate": "2017-09-15",
   "paymentDate": "2017-10-31",
   "recordDate": "2017-09-18",
   "declaredDate": "2017-09-14",
   "amount": 1.235
  },
  {
   "ticker": "SPY",
   "exDate": "2017-06-16",
   "paymentDate": "2017-07-31",
   "recordDate": "2017-06-20",
   "declaredDate": "2017-06-16",
   "amount": 1.183
  },
  {
   "ticker": "SPY",
   "exDate": "2017-03-17",
   "paymentDate": "2017-04-28",
   "recordDate": "2017-03-21",
   "declaredDate": "2017-05-22",
   "amount": 1.033
  },
  {
   "ticker": "SPY",
   "exDate": "2016-12-16",
   "paymentDate": "2017-01-31",
   "recordDate": "2016-12-20",
   "declaredDate": "2017-01-04",
   "amount": 1.329
  },
  {
   "ticker": "SPY",
   "exDate": "2016-09-16",
   "paymentDate": "2016-10-31",
   "recordDate": "2016-09-20",
   "declaredDate": "2016-11-08",
   "amount": 1.082
  },
  {
   "ticker": "SPY",
   "exDate": "2016-06-17",
   "paymentDate": "2016-06-17",
   "amount": 1.078
  },
  {
   "ticker": "SPY",
   "exDate": "2016-03-18",
   "paymentDate": "2016-03-18",
   "amount": 1.05
  },
  {
   "ticker": "SPY",
   "exDate": "2015-12-18",
   "paymentDate": "2015-12-18",
   "amount": 1.212
  },
  {
   "ticker": "SPY",
   "exDate": "2015-09-18",
   "paymentDate": "2015-10-30",
   "recordDate": "2015-09-22",
   "declaredDate": "2015-12-01",
   "amount": 1.033
  },
  {
   "ticker": "SPY",
   "exDate": "2015-06-19",
   "paymentDate": "2015-07-31",
   "recordDate": "2015-06-23",
   "declaredDate": "2015-06-19",
   "amount": 1.03
  },
  {
   "ticker": "SPY",
   "exDate": "2015-03-20",
   "paymentDate": "2015-04-30",
   "recordDate": "2015-03-24",
   "declaredDate": "2015-03-20",
   "amount": 0.931
  },
  {
   "ticker": "SPY",
   "exDate": "2014-12-19",
   "paymentDate": "2015-01-30",
   "recordDate": "2014-12-23",
   "declaredDate": "2014-12-19",
   "amount": 1.135
  },
  {
   "ticker": "SPY",
   "exDate": "2014-09-19",
   "paymentDate": "2014-10-31",
   "recordDate": "2014-09-23",
   "declaredDate": "2014-12-08",
   "amount": 0.939
  },
  {
   "ticker": "SPY",
   "exDate": "2014-06-20",
   "paymentDate": "2014-07-31",
   "recordDate": "2014-06-24",
   "declaredDate": "2014-06-20",
   "amount": 0.937
  },
  {
   "ticker": "SPY",
   "exDate": "2014-03-21",
   "paymentDate": "2014-03-21",
   "amount": 0.825
  },
  {
   "ticker": "SPY",
   "exDate": "2013-12-20",
   "paymentDate": "2013-12-20",
   "amount": 0.98
  },
  {
   "ticker": "SPY",
   "exDate": "2013-09-20",
   "paymentDate": "2013-10-31",
   "recordDate": "2013-09-24",
   "declaredDate": "2013-12-12",
   "amount": 0.838
  },
  {
   "ticker": "SPY",
   "exDate": "2013-06-21",
   "paymentDate": "2013-07-31",
   "recordDate": "2013-06-25",
   "declaredDate": "2013-06-21",
   "amount": 0.839
  }
 ]
}

**Expected Result**
This is not correct. SPY has been paying quarterly dividends since 1993. There should be 110+ dividends listed. Here's a list of SPY dividends I downloaded from dividend.com:

Date	Amount
Oct 30, 2020	$1.339
Jul 31, 2020	$1.366
Apr 30, 2020	$1.406
Jan 31, 2020	$1.570
Oct 31, 2019	$1.384
Jul 31, 2019	$1.432
Apr 30, 2019	$1.233
Jan 31, 2019	$1.435
Oct 31, 2018	$1.323
Jul 31, 2018	$1.246
Apr 30, 2018	$1.097
Jan 31, 2018	$1.351
Oct 31, 2017	$1.235
Jul 31, 2017	$1.183
Apr 28, 2017	$1.033
Jan 31, 2017	$1.329
Oct 31, 2016	$1.082
Jul 29, 2016	$1.078
Apr 29, 2016	$1.050
Jan 29, 2016	$1.212
Oct 30, 2015	$1.033
Jul 31, 2015	$1.030
Apr 30, 2015	$0.931
Jan 30, 2015	$1.135
Oct 31, 2014	$0.939
Jul 31, 2014	$0.937
Apr 30, 2014	$0.825
Jan 31, 2014	$0.980
Oct 31, 2013	$0.838
Jul 31, 2013	$0.839
Apr 30, 2013	$0.694
Jan 31, 2013	$1.022
Oct 31, 2012	$0.780
Jul 31, 2012	$0.688
Apr 30, 2012	$0.614
Jan 31, 2012	$0.770
Oct 31, 2011	$0.625
Jul 29, 2011	$0.628
Apr 29, 2011	$0.553
Jan 31, 2011	$0.653
Oct 29, 2010	$0.602
Jul 30, 2010	$0.531
Apr 30, 2010	$0.480
Jan 29, 2010	$0.590
Oct 30, 2009	$0.508
Jul 31, 2009	$0.518
Apr 30, 2009	$0.561
Jan 30, 2009	$0.719
Oct 31, 2008	$0.691
Jul 31, 2008	$0.669
Apr 30, 2008	$0.642
Jan 31, 2008	$0.775
Oct 31, 2007	$0.719
Jul 31, 2007	$0.656
Apr 30, 2007	$0.551
Jan 31, 2007	$0.793
Oct 31, 2006	$0.579
Jul 31, 2006	$0.556
Apr 28, 2006	$0.520
Jan 31, 2006	$0.672
Oct 31, 2005	$0.522
Jul 29, 2005	$0.488
Apr 29, 2005	$0.467
Jan 31, 2005	$0.568
Dec 02, 2004	$0.351
Oct 29, 2004	$0.467
Jul 30, 2004	$0.413
Apr 30, 2004	$0.394
Jan 30, 2004	$0.514
Oct 31, 2003	$0.399
Jul 31, 2003	$0.359
Apr 30, 2003	$0.353
Jan 31, 2003	$0.435
Oct 31, 2002	$0.377
Jul 31, 2002	$0.352
Apr 30, 2002	$0.330
Jan 31, 2002	$0.392
Oct 31, 2001	$0.368
Jul 31, 2001	$0.345
Apr 30, 2001	$0.315
Jan 31, 2001	$0.410
Oct 31, 2000	$0.374
Jul 31, 2000	$0.347
Apr 28, 2000	$0.370
Jan 31, 2000	$0.347
Oct 29, 1999	$0.371
Jul 30, 1999	$0.404
Apr 30, 1999	$0.319
Jan 29, 1999	$0.391
Oct 30, 1998	$0.358
Jul 31, 1998	$0.351
Apr 30, 1998	$0.313
Jan 31, 1998	$0.378
Oct 31, 1997	$0.347
Jul 31, 1997	$0.349
Apr 30, 1997	$0.298
Oct 31, 1996	$0.351
Jul 31, 1996	$0.350
Apr 30, 1996	$0.285
Jan 31, 1996	$0.381
Oct 31, 1995	$0.311
Jul 31, 1995	$0.315
Apr 28, 1995	$0.267
Jan 31, 1995	$0.362
Oct 31, 1994	$0.287
Jul 29, 1994	$0.304
Apr 29, 1994	$0.270
Jan 31, 1994	$0.316
Oct 29, 1993	$0.285
Jul 30, 1993	$0.317
Apr 30, 1993	$0.213

I checked another ticker with a long history of dividends, EMD, which pays out monthly dividends since inception. It has only dividend history back to 2017. Your oldest SPY dividend goes back to 2013, however. So there doesn't seem to be a pattern to the missing data (i.e. every ticker missing all dividends before 2013), but rather data is missing randomly across tickers.

**Comment by jrbell19** [comment]
This is something that we are aware of, and are working to correct. We are actively working to revamp our reference data. We'll soon be sourcing this data directly from the SEC filings, which will ensure this dataset is kept up to date and accurate. 

Apologies for the inconvenience.

**Comment by asieke** [comment]
Is there any update on this bug?  Still appears that it is not properly including even the most recent dividend for SPY.

Most recent dividend was paid on 10/29/2021, yet the most recent returned from the API is:

`  {
   "ticker": "SPY",
   "exDate": "2021-06-18",
   "paymentDate": "2021-07-30",
   "recordDate": "2021-06-21",
   "declaredDate": "2021-01-22",
   "amount": 1.376
  }`

**Comment by jrbell19** [comment]
We are currently working to update our Dividends endpoint. We anticipate an update by the end of the year or early next. 

Apologies on the delay of this.

**Comment by jrbell19** [comment]
Our Dividends v3 endpoints contain these missing dividends and allows us to easily update them if any are missed. https://polygon.io/docs/stocks/get_v3_reference_dividends

Please let us know if you see any similar issues.
