### ISSUE TITLE
price spikes in the trade stream

### ISSUE THREAD

**Issue by kchad** [polygon-io/issues#13]
**Client**
Which WebScoket client are using?
WebSocket4Net from the C# example page.

**Issue**
Two examples from 4/1/2020 are below. I was hoping the Exchange ID or Trade Conditions would 
give some info but there are valid trades with " x:4 c:53 52 41" in the stream. In the examples below the volume is huge - this is not always the case. If these are Dark Pool trades reported through FINRA, how do I filter them out?

format below is "symbol time price volume exchange conditions"

IWM 1585752938363 109.4 1 x:12 c:37
IWM 1585752938363 109.4 1 x:12 c:37
IWM 1585752938363 109.4 1 x:12 c:37
IWM 1585752938363 109.4 1 x:12 c:37
IWM 1585752938799 114.6247 125984 x:4 c:53 52 41
IWM 1585752938799 114.6247 125984 x:4 c:53 52 41
IWM 1585752938834 109.41 200 x:12 c:
IWM 1585752938834 109.41 200 x:12 c:
IWM 1585752938834 109.41 100 x:12 c:

SPY 1585753014550 249.75 66 x:11 c:14 37 41
SPY 1585753014550 249.75 34 x:11 c:14 37 41
SPY 1585753014550 249.75 66 x:11 c:14 37 41
SPY 1585753014550 249.75 34 x:11 c:14 37 41
SPY 1585753014600 249.75 100 x:12 c:
SPY 1585753014603 257.6591 251065 x:4 c:53 52 41
SPY 1585753014600 249.75 100 x:12 c:
SPY 1585753014603 257.6591 251065 x:4 c:53 52 41
SPY 1585753014600 249.75 100 x:12 c:
SPY 1585753014603 257.6591 251065 x:4 c:53 52 41
SPY 1585753014907 249.74 100 x:12 c:
SPY 1585753015061 249.7376 200 x:4 c:
SPY 1585753015106 249.735 80 x:4 c:37 

**Expected Result**
Trading platforms do not show these price spikes. I need a way to filter them out.

**Comment by qrpike** [comment]
Finra is exchange ID `4` which means it was a TRF trade. These can happen outside the normal range. 

See ( https://polygon.io/glossary/us/stocks/conditions-indicators ) for trade conditions which you should probably filter out. If it does not update the consolidated OHLCV, it can vary greatly.

**Comment by kchad** [comment]
Thank You qrpike! I recommend Polygon.io links to that page from the Websocket docs.
Are those condition processing guidelines applicable for all exchanges or just Finra?

**Comment by qrpike** [comment]
@kchad We will be updating WS docs in the near future, and we will note that recommendation. Those guidelines are applicable for all trades.
