### ISSUE TITLE
VWAP (vw) and tick VWAP (a) values are swapped for WebSocket Aggregates (Per Second) 

### ISSUE THREAD

**Issue by gcatlin** [polygon-io/issues#131]
**Client**
wscat

**Issue**
It looks like the values for `vw` (VWAP) and `a` (tick VWAP) for WebSocket Aggregates (Per Second) events are swapped. For example, here's an event for the 1 second period starting Fri Feb 26, 2021 at 3:37 PM ET:
```
{"ev":"A","sym":"RKT","v":241,"av":47467961,"op":23.33,"vw":21.805,"o":21.805,"c":21.805,"h":21.805,"l":21.805,"a":22.4898,"z":120,"s":1614371820000,"e":1614371821000}
```
The OHLC values are all 21.805 however `a` is `22.4898` and `vw` is `21.805`

**Expected Result**
Should be: `"a":21.805` and `"vw":22.4898`

**Desktop (please complete the following information):**
n/a

**Additional context**

**Comment by jrbell19** [comment]
This is something that we are aware of and should be able to address in the near future. 

Apologies for the inconvenience.

**Comment by gcatlin** [comment]
Looks like this is affecting the REST Aggregates (Bars) endpoint too, per this [Slack thread](https://polygon-io.slack.com/archives/CUQUYL63W/p1616364106055500).

**Comment by robertroyster** [comment]
Did this get fixed in the new release?
Please let us know before you fix it as we have all coded around it.

**Comment by gcatlin** [comment]
Looks like this was mitigated by changing the [Websocket documentation](https://polygon.io/docs/websockets/ws_stocks_AM_anchor) to reflect the actual behavior:
- `vw`: The tick's volume weighted average price
- `a`: Today's volume weighted average price

For the [REST Aggregates (Bars) API](https://polygon.io/docs/get_v2_aggs_ticker__stocksTicker__range__multiplier___timespan___from___to__anchor), `vw` is "The volume weighted average price". It's not stated explicitly, but it's really **the tick's** volume weighted average price, just like it is with Websocket aggregates.

 If you want the VWAP since market open (or any point in time), you need to calculate it manually. To do so, you need to track:
- `cumulative volume`: sum of tick volumes since time T (e.g. market open)
- `cumulative dollar volume`: sum of (tick volume * tick VWAP) since time T

And then:
- VWAP = `cumulative dollar volume` / `cumulative volume`

Alternatively, if you don't track tick VWAP, you can estimate VWAP using each tick's high, low, close, and volume [as described here](https://www.tradingview.com/support/solutions/43000502018-volume-weighted-average-price-vwap/).
