### ISSUE TITLE
Snapshot of all tickers returned 0 for all fields in `day`

### ISSUE THREAD

**Issue by mosheduminer** [polygon-io/issues#132]
**URL**
`https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers` (via the polygon python library).

**Result**
The API call was made yesterday (2021-03-15) at 6pm, and the fields (o, c, h, l, v, vw) in the `day` object are all `0`, instead of their appropriate values.

**Expected Result**
Expected the appropriate data to be shown.

**Desktop (please complete the following information):**
 Running in AWS lambda

**Additional context**

**Comment by jrbell19** [comment]
Hi there, 

Sorry you ran into this. This is a known issue that we have since addressed. Please let me know if you see anything else out of the ordinary.
