### ISSUE TITLE
Snapshot - Ticker returning inconsistent "updated" timecode formats

### ISSUE THREAD

**Issue by unscripted** [polygon-io/issues#133]
**URL**
https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers/BCPC?&apiKey=*

**Result**
Over time, when getting the URL above, the "updated" timestamp is switching between a 19 digit and 13 digit timecode. When the 19 digit timecode is returned it appears to be set to GMT. However, the 13 digit timecode is in the future (even for GMT)

**Expected Result**
The user expects the "updated" time to use a consistent timestamp format that is set to GMT.

**Screenshots**
<img width="1038" alt="Screen Shot 2021-03-17 at 2 08 44 PM" src="https://user-images.githubusercontent.com/985099/111527516-0231de00-872e-11eb-9938-ff56143266e1.png">
<img width="1035" alt="Screen Shot 2021-03-17 at 2 10 53 PM" src="https://user-images.githubusercontent.com/985099/111527522-03630b00-872e-11eb-81a4-a9d3c40c7373.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version Version 89.0.4389.82 (Official Build) (x86_64)

**Comment by jrbell19** [comment]
Thanks for bringing this to our attention! We have a fix for this in staging and will be releasing it tonight. 

Please let me know if you see anything else out of the ordinary.
