### ISSUE TITLE
Websocket connection drops periodically during trading hours

### ISSUE THREAD

**Issue by nickmachairas** [polygon-io/issues#134]
**Client**
Behavior is the same both with Python and Golang

**Issue**
The websocket connection (subscribed to A.* and AM.*) drops *every hour* during trading hours but stays alive without issues after hours till next day 9:30am. Please note the periodic behavior: every 1 hour +- 15 minutes. To make the case that my system processes the messages fast enough, the connection will not drop during high volume intervals, unless of course it hits the one hour mark.

**Expected Result**
I expected the connection to be stable, and I confirmed that the messages are being read fast enough, no backlog is causing the disconnect. Messages are buffered and passed to a MQ.

**Screenshots**
Connection error code is 1006 on Python and "connection reset by peer" on Golang. I can share more if you need.

**Desktop (please complete the following information):**
Both a VM on GCP (N. Virginia) and my office system (NYC area)

**EDIT:**
Adding to the strange behavior, I can confirm that "pongs" are ***not*** returned during trading hours, leading to an i/o timeout error with Golang, but they ***are*** returned from the polygon server during off hours.

After spending so much time on this, and to restore my sanity, I would be absolutely thrilled to see a stable implementation by anyone, using any programming language whatsoever, parsing the A.* and AM.* streams. Thanks.

**Comment by mmoghaddam385** [comment]
Hi @nickmachairas , sorry you're running into this issue. Unfortunately I'm not able to reproduce the problem, could you try connecting to the websocket server and subscribing using a tool like [wscat](https://github.com/websockets/wscat)? You can find step-by-step instructions on how to do that on our [websocket docs page](https://polygon.io/docs/websockets).

Also, on your edit about "pongs": While testing with `wscat`, you can pass the flags `--show-ping-pong` and `--slash` to enable slash commands and send a ping to the websocket server by typing `/ping` in wscat. 

For example: 
```bash
$ wscat --show-ping-pong --slash -c wss://socket.polygon.io/stocks
Connected (press CTRL+C to quit)
< [{"ev":"status","status":"connected","message":"Connected Successfully"}]
> /ping
< Received pong
```

(you can send pings after authenticating and subscribing to symbols too).

Please let me know if you experience the same issues while using `wscat`

**Comment by nickmachairas** [comment]
Hello @mmoghaddam385 , thanks for following up. When you are saying you could not reproduce the problem, are you implying that you recently subscribed to ``A.*,AM.*`` during trading hours and had a reliable connection that did not drop for more than 1.5 hours? If so may I ask which client you are using, what your system resources are and if you have some unique networking settings?

If not then you are probably misdiagnosing my problem. I don't have a problem connecting and subscribing. I have a problem establishing a reliable, long-lived connection to ``A.*,AM.*`` (one day even ``T.*,Q.*``). To my knowledge, my system can easily handle parsing all messages from ``A.*,AM.*``: cpu is at 6% with plenty of network capacity, plus my Polygon dashboard shows no buffered messages. Yet the connection is still dropped every hour. Do you have any other recommendations on how I can troubleshoot? I even tried Google Cloud to make sure my own ISP was not the culprit.

I am writing more about this issue on your Golang client repo.

To answer your question, yes I can ping and receive pong on wscat but for some reason this does not happen with the Python or Golang clients.

**Comment by mmoghaddam385** [comment]
Let me clarify what I did to try to reproduce the issue you're facing: 

I opened a connection using wscat (`wscat --show-ping-pong --slash -c wss://socket.polygon.io/stocks`), authenticated and subscribed to `A.*,AM.*` and let it sit for ~1.5 hours (10:18am EST - 11:44am EST this morning). Throughout the connection I would periodically send pings and confirm that the server responded with a pong.

I did this on a macbook pro (16gb RAM, 2.6 GHz 6-Core Intel Core i7) with no special network settings that I know of.

I'd recommend letting wscat run longer on your system to see if the same issue shows up when using the simplest possible client. It if does happen with wscat, it's likely a network related issue, otherwise it might be something in the client itself.

I hope this helps, apologies for the inconvenience this has caused.

**Comment by nickmachairas** [comment]
Thanks, Michael. I just had wrote about this on the other repo. It looks like wscat works for you and others. I will test once the markets reopen with wireshark too. I just don't understand why wscat would work and not Python or Golang. Have you tested any clients other than wscat?
