### ISSUE TITLE
Reveal data source

### ISSUE THREAD

**Issue by Peter-Pasta** [polygon-io/issues#136]
To better judge the quality of the data it would be helpful if the docs would detail the data source and get a little into the process of how it was prepared/processed/parsed by Polygon (if applicable). I am sure there are some proprietary things you don’t want to give away but I am just talking about a general description for each endpoint.

**Comment by jrbell19** [comment]
Here's a write up that should explain in more detail where we are getting the data: https://polygon.io/blog/understanding-the-sips/

**Comment by Peter-Pasta** [comment]
> We receive data directly from both SIPs as RAW binary feeds rather than via retransmission or through an intermediary.

Are all of Polygon's endpoints fed with data from the SIP feeds?

**Comment by jrbell19** [comment]
Any of the US equity price data is sourced from the SIPs. The data that is made available through aggregates is calculated on our end, based on a number of qualifying conditions. You can read about this process in our blog post: https://polygon.io/blog/understanding-trade-eligibility/

**Comment by Peter-Pasta** [comment]
Thank you!
