### ISSUE TITLE
Missing aggregate bars for HUSN prior to 5/8/2020

### ISSUE THREAD

**Issue by cnaccio** [polygon-io/issues#137]
Using the API url below, I'd expect intraday pricing data to be available for HUSN

https://api.polygon.io/v2/aggs/ticker/HUSN/range/1/minute/2019-01-01/2019-12-30?unadjusted=false&sort=asc&limit=120&apiKey=YOU_SPECIAL_KEY

**Comment by jrbell19** [comment]
This is a result of the company changing tickers from CIFS to HUSN effective **May 8, 2020**: On April 10, 2020, the board of directors of China Internet Nationwide Financial Services, Inc. (the “Company”) resolved to change the Company’s name to “Hudson Capital Inc.” to re-brand the Company and better reflect the plans for its next phase of growth.

https://investorshub.advfn.com/Hudson-Capital-Inc-HUSN-11448/#:~:text=Name%2DChange%20from%20CIFS%20to,its%20next%20phase%20of%20growth.

We are planning to track these changes in the near future. Apologies for the inconvenience.
