### ISSUE TITLE
AAPL dividend from August 2020 is wrong

### ISSUE THREAD

**Issue by sk-** [polygon-io/issues#139]
**URL** https://api.polygon.io/v2/reference/dividends/AAPL?&apiKey=

**Result** The dividend for August 2020 is 0.205, the same data is shown on https://polygon.io/quote/AAPL
It seems that you are somehow getting the adjusted price for that particular dividend. 

**Expected Result**
The correct dividend is 0.82. See https://www.nasdaq.com/market-activity/stocks/aapl/dividend-history.

**Comment by kmcminn** [comment]
see #119
