### ISSUE TITLE
30m data LOW not matching Trading View 

### ISSUE THREAD

**Issue by yoann-trouillet** [polygon-io/issues#14]
**URL**
The RESTful API call you are making (please be sure to omit your API key)
/aggs/ticker/AAPL/range/30/minute/1588305600000/1589572800000

**Result**
The low value for the 12:20 (America/New_York) bar is off
{
      open: 304.7,
      close: 304.95,
      high: 305.36,
      **low: 301.92**,
      u: "1589560200",
      t: "15-05-2020 12:30"
   },
See attached screen shots

**Expected Result**
We expect the data to match with Trading View (+- margin of error)

<img width="934" alt="Screen Shot 2020-05-16 at 10 53 37 am" src="https://user-images.githubusercontent.com/19640156/82106330-8a88d080-9763-11ea-8d23-1e5f432d26f7.png">

**Screenshots**
See attached screen shots

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Nodejs AXIOS Rest API Call
 

**Additional context**
that same low value is also wrong in the minute data

**Comment by jrbell19** [comment]
The prices are off because tradingview is only collecting data from Nasdaq, while we are collecting data from all 16 exchanges.
