### ISSUE TITLE
A forex simulator server for the weekend hours (for coding while the markets are inactive)

### ISSUE THREAD

**Issue by enjoysmath** [polygon-io/issues#142]
The markets are not active right now, it being the weekend.  I am having trouble getting a python `websockets` library server to send myself a random forex price signal.

See this SO post: https://stackoverflow.com/questions/67343487/python-websockets-library-server-not-streaming-any-data-but-connecting-and-at

So I am requesting that the developers make a simple WebSocket server just like they already have but sends out a (preferably life-like) random forex price signal.  You connect to it just by changing the URL and the rest of your code should stay the same.

This would be nice, since I'm really excited about coding at the moment, but there is no market data to code a technical indicator with.  And what if you had users that could strictly only code on the weekends because of work or school.  

Thank you for this great API - I'm really enjoying its perfection, cleanliness, and affordable price.  I've got the $49/ month Forex package.

Also and in particular, the website has the greatest UX and API toolset.

**Comment by enjoysmath** [comment]
If you code this, it should maybe have a cutoff time of 1 hour, so that users don't mistakenly forget to change the URL to the real market, and lose a lot of money, LOL.

**Comment by LucPettett** [comment]
@enjoysmath Just use the crypto API, that'll push prices to you 24/7, then manually change your ticker to a forex code pair for testing!

**Comment by matichenor** [comment]
We don't have future plans to distribute simulated data.  However, you could replicate this functionality by building capturing and replaying historic data or using crypto data as suggested by Luc.
