### ISSUE TITLE
Pagination for  "v3/reference/tickers" has multiple bugs 

### ISSUE THREAD

**Issue by marco-alban-atomic** [polygon-io/issues#143]
**URL**
 "v3/reference/tickers"

**Result**
1) Make query with params: 
      `active=true&sort=ticker&order=asc&limit=1000&exchange=XNYS&apiKey=blah`

 2) You'll get a cursor in response object. Second pagination call works fine:
      `/v3/reference/tickers/?cursor=123&apiKey=blah"

 3) Third pagination call fails because next_cursor returns:
     "next_cursor": "https://api.polygon.io:443:443/v3/reference/tickers..."
     Notice the double `:443`

Manually parsing the url to just get the cursor and rehydrate what should be the correct url (no :443) makes it so that the same next_cursor is always returned (e.g. data is the same and cursor is ignored, you cannot advance pagination)

**Expected Result**
3rd pagination call should work

** Additional **
Fix seems to "hard code" url to always be `https://api.polygon.io:443` and then build the next url manually. It seems like pagination just doesn't work without adding the port. Relying on the next_url returned from the object itself does not work as it will return :443:443

**Desktop (please complete the following information):**
 - OS: macOS
 - curl

**Comment by marco-alban-atomic** [comment]
edited, meant `next_url`. Definitely the same API. I was able to work around it by building the url manually with some string manipulation to remove extra port. I can still reproduce it. Hopefully this helps, will move on to other things. Feel free to close.

**Comment by lueurxax** [comment]
I can reproduce this bug with header 'Host'`curl -H "Host: api.polygon.io:443" 'https://api.polygon.io:443/v2/reference/news?cursor=eyJsaW1pdCI6MTAwLCJzb3J0IjoicHVibGlzaGVkX3V0YyIsIm9yZGVyIjoiZGVzY2VuZGluZyIsInRpY2tlciI6eyJlcSI6IkFBUEwifSwicHVibGlzaGVkX3V0YyI6eyJndCI6IjIwMjEtMDUtMTFUMDg6MjU6MDMuODcyWiJ9LCJzZWFyY2hfYWZ0ZXIiOlsxNjIxNDI2NTAwMDAwLG51bGxdfQ&apiKey=$POLYGON_API_KEY' | jq -r .next_url`
