### ISSUE TITLE
Different search result between v2/reference/tickers and v3/reference/tickers when search term contains spaces

### ISSUE THREAD

**Issue by syedhusain-appspace** [polygon-io/issues#149]
**URL**
https://api.polygon.io/v3/reference/tickers?apiKey={{Polygon Dev APIKEY}}&search=Lithium Americas Corp. Common Shares

**Result**
Seems like all tickers

**Expected Result**
Only tickers related to the search term

**Screenshots**
![image](https://user-images.githubusercontent.com/66248986/120268213-0191f800-c2d8-11eb-8c77-fe09c390f789.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Postman
 - Version 8.5.1

**Additional context**
When searching "Lithium" only, it manage to return related tickers only. Only happen if the search term contains spaces. Other example "Southwestern Energy Company". V2 API returns all tickers that contains the search term: https://api.polygon.io/v2/reference/tickers?search=Lithium Americas Corp. Common Shares&apiKey={{Polygon Dev APIKEY}}.

Encoding the space with %20 doesn't help

**Comment by jrbell19** [comment]
This is something that we are looking into Sorry for the confusion.
