### ISSUE TITLE
Url field from /v2/reference/tickers always return 404

### ISSUE THREAD

**Issue by sharok** [polygon-io/issues#15]
**URL**
https://api.polygon.io/v2/reference/tickers/AAPL

**Result**
Polygon returns 404

**Expected Result**
Polygon should return details for this ticker. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81

**Additional context**
I use v2/reference/tickers for fetching symbols and every ticker in the response contains `url` field. I expect that this URL can be used for getting details. But, right now it always returns 404, I have tried several tickers.

**Comment by jrbell19** [comment]
We are currently aware of this. For now, if you're looking for company information query the ticker details endpoint directly: 

https://api.polygon.io/v1/meta/symbols/AAPL/company?apiKey=

**Comment by jrbell19** [comment]
Ticker Details: https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker
