### ISSUE TITLE
Duplicate ticker issue "BAUG"

### ISSUE THREAD

**Issue by awentzonline** [polygon-io/issues#153]
**URL**
https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/2021-06-10?adjusted=true&apiKey=
For dates 2021-06-10 through 2021-06-17

**Result**
It appears that the ticker "BAUG" is duplicated in those API calls. This must have started happening between last Friday and today (July 9th through 12th, 2021)

**Screenshots**
<img width="784" alt="Screen Shot 2021-07-12 at 7 15 40 PM" src="https://user-images.githubusercontent.com/5231065/125379581-9eb76600-e345-11eb-9566-6d657596b0a2.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: chrome and with python client

**Comment by jrbell19** [comment]
Hi, this has since been resolved. Apologies for the inconvenience!
