### ISSUE TITLE
Not getting open-close data for July 15th

### ISSUE THREAD

**Issue by gms008** [polygon-io/issues#154]
**URL**
https://api.polygon.io/v1/open-close/ALK/2021-07-15

**Result**
error: 404, {"status":"NOT_FOUND","request_id":"21aa5db118fb4e3d59954f46ea9fa728","message":"Data not found."}

**Expected Result**
json response with open/close prices

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04

**Additional context**
I am getting the same error for every stock. I am getting correct responses for all other days of last week (week of July 12th). As far as I am aware July 15th wasn't a holiday.

**Comment by gms008** [comment]
I'm seeing data now but is there an explanation for why it was missing?

**Comment by jrbell19** [comment]
Hi there, 

Sorry I missed this. We had some intermittent issues arise when we made some infrastructure upgrades, which led to some data being unavailable for a short period of time. 

Apologies for any inconvenience this may have caused. Please let me know if you see anything else out of the ordinary.
