### ISSUE TITLE
Add number of trades to snapshot response

### ISSUE THREAD

**Issue by brigmecham** [polygon-io/issues#158]
We want to monitor number of trades per equity via the snapshot api.  

We can currently get this data from the aggregates api, but only for one equity at time, or via the web socket.

It would be a lot easier if we could just have it in the snapshot api as a new field in the min object.

**Comment by matichenor** [comment]
Closing this ticket as it looks like a similar request to https://github.com/polygon-io/issues/issues/150.  Be sure to comment or react to the other ticket so we can track interest in the feature!

**Comment by matichenor** [comment]
per above
