### ISSUE TITLE
PROPERTIES section should contain relevant fields description for /v2/reference/tickers

### ISSUE THREAD

**Issue by sharok** [polygon-io/issues#16]
**Describe the bug**
Wrong PROPERTIES description for /v2/reference/tickers.
The response contains `ticker` property, but in the PROPERTIES section contains `symbol`.
Moreover, not all fields are described.

**To Reproduce**
1. Go to [https://polygon.io/docs/#get_v2_reference_tickers_anchor](url)
2. Scroll down to the PROPERTIES section on the right.

**Expected behavior**
PROPERTIES  section should contain relevant fields description

**Comment by jrbell19** [comment]
We'll go in and correct this asap!
