### ISSUE TITLE
Minutely aggregations show split for GOOG when 'adjusted' unset

### ISSUE THREAD

**Issue by erikreed** [polygon-io/issues#164]
Hello -- I am trying to understand the API behavior of a split like GOOG -> GOOGL using the minutely stock aggregation endpoint.

**URL**
- `/v2/aggs/ticker/{symbol}`

**Result**
GOOG shows a split in 2014, which to me is counter-intuitive since `adjusted` is not set in the request.
![image](https://user-images.githubusercontent.com/903366/136094386-2dcd0108-eba5-4483-a272-7987cbbf636d.png)

2014 is not a standard split given the company splitting to two tickers, so perhaps there is a better way to handle this? [edit: 2015 was the company restructure, so that seems unrelated]

**Expected Result**
As a comparison, AAPL does not exhibit this behavior.
![image](https://user-images.githubusercontent.com/903366/136094575-822ecd70-fd0f-4403-b173-d418786e21a4.png)

**Additional context**
The queries were performed via the python client and aggregated in pandas, no transforming of the data.

Client version:
```
polygon-api-client==0.1.11
```

Code approximation:
```python
respone = client.stocks_equities_aggregates(
    ticker="GOOG",
    multiplier=1,
    from_=str(from_dt),
    to=str(to_dt),
    timespan='minute',
    limit=50000,
    sort='desc'
)
```

**Comment by jrbell19** [comment]
This has been resolved

**Comment by erikreed** [comment]
Fantastic thanks!
