### ISSUE TITLE
Duplicate entries in Tickers API

### ISSUE THREAD

**Issue by bluelu** [polygon-io/issues#165]
Hi,

It seems that there is a bug when requesting active ticker symbols using the Tickers API, where symbols appear duplicated in the returned results.

This popped up for me with the following request: https://api.polygon.io/v3/reference/tickers?market=stocks&exchange=XNAS&date=2021-10-01&sort=ticker&order=asc&limit=1000&apiKey=* 

The returned results contain twice the CASY symbol, with otherwise identical information (except for "last_updated_utc" and the case of "name"). The second appears to be the most recent.

{
"ticker": "CASY",
"name": "CASEYS GENERAL STORES INC",
"market": "stocks",
"locale": "us",
"primary_exchange": "XNAS",
"active": true,
"currency_name": "usd",
"cik": "0000726958",
"composite_figi": "BBG000BF0672",
"share_class_figi": "BBG001S5PHZ2",
"last_updated_utc": "2011-05-10T00:00:00Z"
},
{
"ticker": "CASY",
"name": "Casey's General Stores Inc",
"market": "stocks",
"locale": "us",
"primary_exchange": "XNAS",
"type": "CS",
"active": true,
"currency_name": "usd",
"cik": "0000726958",
"composite_figi": "BBG000BF0672",
"share_class_figi": "BBG001S5PHZ2",
"last_updated_utc": "2021-10-07T00:00:00Z"
},

Should I just ignore the duplicate entry and take the last entry?

**Comment by jrbell19** [comment]
We will be working to address this over the course of the next week or so. I will post updates here as I get them.

**Comment by bluelu** [comment]
Ok, thanks :)

**Comment by endoffile78** [comment]
This is still an issue, I get CASY back 4 times.

```
    {
        "ticker": "CASY",
        "name": "CASEYS GENERAL STORES INC",
        "market": "stocks",
        "locale": "us",
        "active": true,
        "currency_name": "usd",
        "cik": "0000726958",
        "composite_figi": "BBG000BF0672",
        "share_class_figi": "BBG001S5PHZ2",
        "last_updated_utc": "2011-01-14T00:00:00Z"
    },
    {
        "ticker": "CASY",
        "name": "CASEYS GENERAL STORES INC",
        "market": "stocks",
        "locale": "us",
        "primary_exchange": "XNAS",
        "active": true,
        "currency_name": "usd",
        "cik": "0000726958",
        "composite_figi": "BBG000BF0672",
        "share_class_figi": "BBG001S5PHZ2",
        "last_updated_utc": "2011-05-10T00:00:00Z"
    },
    {
        "ticker": "CASY",
        "name": "CASEYS GENERAL STORES INC",
        "market": "stocks",
        "locale": "us",
        "active": true,
        "currency_name": "usd",
        "cik": "0000726958",
        "composite_figi": "BBG000BF0672",
        "share_class_figi": "BBG001S5PHZ2",
        "last_updated_utc": "2011-04-29T00:00:00Z"
    },
    {
        "ticker": "CASY",
        "name": "Casey's General Stores Inc",
        "market": "stocks",
        "locale": "us",
        "primary_exchange": "XNAS",
        "type": "CS",
        "active": true,
        "currency_name": "usd",
        "cik": "0000726958",
        "composite_figi": "BBG000BF0672",
        "share_class_figi": "BBG001S5PHZ2",
        "last_updated_utc": "2022-01-29T00:00:00Z"
    },
```

**Comment by jrbell19** [comment]
Resolved
