### ISSUE TITLE
Reference Options: Response contains too much data

### ISSUE THREAD

**Issue by Peter-Pasta** [polygon-io/issues#167]
**URL**

```
underlyings = 'AAPL&AMZN'
url = f"https://api.polygon.io/vX/reference/options/contracts?underlying_ticker{underlyings}&limit=1000&apiKey={dep['polygon']}"
```

**Result**

I am getting more than the specified underlyings. In this case it seems that I get ALL underlyings, starting with 'A'.

**Expected Result**

I am expecting to receive only the options contracts for AAPL and AMZN

**Comment by Peter-Pasta** [comment]
The issue in the URL was that it missed an equal sign before the tickers. However, it only works when I pass a single ticker. I think it would be very useful if polygon accepts URLs containing multiple tickers and responds with the respective data.

**Comment by jrbell19** [comment]
This is not a bug we are planning to fix. Our contracts endpoint only accepts a single ticker at a time. Closing
