### ISSUE TITLE
Options WebSocket Trades Documentation is Missing Field

### ISSUE THREAD

**Issue by SamuelLabrador** [polygon-io/issues#174]
**Describe the bug**
The response object for the Trade subscriptions seems to be missing a key/value pair. When I receive the actual data, there's a `q` in the trade object. However, the doc page does not display that key/value pair in the response object. 

Based on the stock trades REST API response object, I'm assuming this is the sequence number.

**Additional context**
https://polygon.io/docs/options/ws_options_T

**Comment by jrbell19** [comment]
'q' is sequence number. I'll make a ticket to adjust the docs. Apologies for the confusion.
