### ISSUE TITLE
Quotes NBBO Data Fails with "Unauthorized" for Dates December 2 and December 3 2021

### ISSUE THREAD

**Issue by bellabelanichglynn** [polygon-io/issues#175]
**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/AAPL/2021-12-03?reverse=true&limit=10
and
https://api.polygon.io/vX/quotes/SFIX?timestamp=2021-12-03

Doesn't matter which Stock or using v2 or vX, both fail.

**Result**
Failed to Authorize 500

**Expected Result**
It should return results just like every other day (e.g. https://api.polygon.io/vX/quotes/SFIX?timestamp=2021-12-06 )

**Screenshots**
The above should be enough - it also fails in the built-in query runner on the REST docs. 

**Desktop (please complete the following information):**
Mac Chromium Browser 96

**Additional context**

**Comment by jrbell19** [comment]
We are aware of this issue and are currently working to resolve this. Apologies for the inconvenience.
