### ISSUE TITLE
how manage and create docs? 

### ISSUE THREAD

**Issue by ksdaftari** [polygon-io/issues#179]
hello have loved the web api documentation in https://polygon.io/docs/stocks and was wondering if what built off is any open source application. in our org we are looking to see how to better document our web apis, we have used sphinx for most documentation but struggling to strike balance on something that is more interactive and easier to maintain and integrates with rest of sphinx documentation, given this project seems to have great documentation was wondering if willing share how go about documenting (especially regards to frameworks/practices may be using), doesnt need to be anything to detailed but just looking to see what is out there and how other teams like yours have tackled

**Comment by matichenor** [comment]
@ksdaftari , sorry for the delayed reply to your question!  As far as I know we built our doc solution in-house based on an underlying open-api spec.  The doc solution was coded in nodejs. 

Glad you like it!
