### ISSUE TITLE
Missing Forex History for 2019

### ISSUE THREAD

**Issue by jrbell19** [polygon-io/issues#18]
**URL**
https://api.polygon.io/v2/aggs/ticker/C%3AEURUSD/range/1/day/2019-01-01/2020-01-01?apiKey=XXXX

**Result**
No data points for 2019 

**Expected Result**
Daily bars for all of 2019. Even tried querying smaller timeframes. 

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [all]

**Additional context**
The data was previously available, definitely a new issue

**Comment by tankorsmash** [comment]
I'm not sure if this is the same issue I'm having, but even for 2020 data on the EUR - USD: 

    https://api.polygon.io/v2/aggs/ticker/C:EURUSD/range/1/day/2020-01-01/2020-02-01?sort=asc&apiKey=<API_KEY>

shows up blank:

```
// 20201013103451
// https://api.polygon.io/v2/aggs/ticker/C:EURUSD/range/1/day/2020-01-01/2020-02-01?sort=asc&apiKey=<APIKEY>

{
  "ticker": "C:EURUSD",
  "status": "OK",
  "queryCount": 0,
  "resultsCount": 0,
  "adjusted": true,
  "results": null,
  "request_id": "d0c40e9e1a0a42b22f2faf03bdb62ad6"
}
```

**Comment by jrbell19** [comment]
The Currencies backfill is now complete. Tick and aggregated data for forex will be available back to June of 2009. 

Crypto historical data is currently available back to May of 2017.
