### ISSUE TITLE
Wrong Dividends  Data

### ISSUE THREAD

**Issue by ligrire** [polygon-io/issues#182]
**URL**
The RESTful API call you are making (please be sure to omit your API key)
https://api.polygon.io/v3/reference/dividends?ticker=EWY&apiKey=
https://api.polygon.io/v2/reference/dividends/EWY?apiKey=
**Result**
What result are getting?
v3 result:

{"results":[{"cash_amount":1.678518,"declaration_date":"2021-12-10","dividend_type":"CD","ex_dividend_date":"2021-12-13","frequency":2,"pay_date":"2021-12-17","record_date":"2021-12-14","ticker":"EWY"},{"cash_amount":0.630268,"declaration_date":"2020-12-11","dividend_type":"CD","ex_dividend_date":"2020-12-14","frequency":2,"pay_date":"2020-12-18","record_date":"2020-12-15","ticker":"EWY"},{"cash_amount":1.307628,"declaration_date":"2019-12-13","dividend_type":"CD","ex_dividend_date":"2019-12-16","frequency":2,"pay_date":"2019-12-20","record_date":"2019-12-17","ticker":"EWY"},{"cash_amount":0.789911,"declaration_date":"2018-12-17","dividend_type":"CD","ex_dividend_date":"2018-12-18","frequency":2,"pay_date":"2018-12-24","record_date":"2018-12-19","ticker":"EWY"},{"cash_amount":0.66336,"declaration_date":"2014-12-16","dividend_type":"CD","ex_dividend_date":"2014-12-17","frequency":2,"pay_date":"2014-12-24","record_date":"2014-12-19","ticker":"EWY"}],"status":"OK","request_id":"4788b7a26df7962d28ead2933d7f2b0a"}

v2 result:

{"status":"OK","count":8,"results":[{"ticker":"EWY","exDate":"2020-12-14","paymentDate":"2020-12-18","recordDate":"2020-12-15","declaredDate":"2019-12-16","amount":0.63},{"ticker":"EWY","exDate":"2019-12-16","paymentDate":"2019-12-20","recordDate":"2019-12-17","declaredDate":"2018-12-28","amount":1.308},{"ticker":"EWY","exDate":"2018-12-18","paymentDate":"2018-12-24","recordDate":"2018-12-19","declaredDate":"2017-12-29","amount":0.79},{"ticker":"EWY","exDate":"2017-12-19","paymentDate":"2017-12-26","recordDate":"2017-12-20","declaredDate":"2017-12-18","amount":2.176},{"ticker":"EWY","exDate":"2016-12-21","paymentDate":"2016-12-28","recordDate":"2016-12-23","declaredDate":"2017-02-23","amount":0.645},{"ticker":"EWY","exDate":"2015-12-21","paymentDate":"2015-12-28","recordDate":"2015-12-23","declaredDate":"2016-01-05","amount":1.202},{"ticker":"EWY","exDate":"2014-12-17","paymentDate":"2014-12-24","recordDate":"2014-12-19","declaredDate":"2015-05-08","amount":0.663},{"ticker":"EWY","exDate":"2013-12-18","paymentDate":"2013-12-30","recordDate":"2013-12-20","declaredDate":"2014-01-06","amount":0.898}]}

**Expected Result**
https://www.nasdaq.com/market-activity/funds-and-etfs/ewy/dividend-history

**Additional context**
Data from both new API and old API for dividends history are not complete.

**Comment by Stormy110** [comment]
Hello there, thank you for reaching out and sharing this with us! I will go in and add those missing dividends. Apologies for the inconvenience!

**Comment by ligrire** [comment]
> Hello there, thank you for reaching out and sharing this with us! I will go in and add those missing dividends. Apologies for the inconvenience!

Thank you. I wonder why this problem arrises and whether missing dividends problem only happens on this stock or other stocks can have missing information as well? This is just one random stock I selected to check for data correctness.

**Comment by Stormy110** [comment]
Apologies for the delay! This should be fixed now. We have recently released an updated Dividends v3 endpoint that should have all dividends going forward. If you ever notice any other missing dividends, feel free to reach out and we can add them manually. Apologies for any inconvenience this has caused!
