### ISSUE TITLE
historical options tickers

### ISSUE THREAD

**Issue by chasecb** [polygon-io/issues#183]
Without a list of options tickers belonging to a given underlier at some point in the past the historical options data becomes tough to work with.

**Describe the solution you'd like**
A list all contracts for a given date in the past.

**Describe alternatives you've considered**
A reference ID type function that lists all options expirations for a given ticker within a date range so the tickers might be assebled by brute force.

**Additional context**
How can one use the historical options data without a list of historical tickers?

**Comment by jrbell19** [comment]
We are working to support historical options contracts by the end of Q1 2022. Apologies for the inconvenience!

**Comment by matichenor** [comment]
We are in progress on development of this feature.  Thank you for your suggestion!

**Comment by matichenor** [comment]
Historic options tickers are now available!

See https://polygon.io/docs/options/get_v3_reference_options_contracts for API doc.
