### ISSUE TITLE
NBBO data not available for Jan 7, 2022

### ISSUE THREAD

**Issue by FreeGoldRush** [polygon-io/issues#184]
**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/TSLA/2022-01-07

All tickers fail on Jan 7, 2022

**Result**
{
 "error": "Unknown database error ( Error Code: 001 )",
 "errorcode": "001",
 "status": "ERROR",
 "success": false
}

**Expected Result**
NBBO data for the ticker given.

Further info:

This has always worked reliably.  I'm guessing this is associated with oatsreportable.finra.org DNS entry having been removed on Friday.  I am also dealing with the fact that OATS Reportable Security Daily List is not available because of their missing DNS entry.  Kinda surprised FINRA has not gotten that fixed over the weekend.

**Comment by FreeGoldRush** [comment]
This data is now available and "Unknown database error" is no longer being returned.  Something caused the data to be missing for 3 days.  Hope you guys find the issue.  Thank you.

**Comment by jrbell19** [comment]
We are investigating the root of the issue, but have remedied the data being unavailable. Apologies for the inconvenience.
