### ISSUE TITLE
Crypto minute data on 2021-12-23 missing

### ISSUE THREAD

**Issue by ligrire** [polygon-io/issues#186]
**URL**
(https://api.polygon.io/v2/aggs/ticker/X:ETHUSD/range/1/minute/2021-12-23/2021-12-23?adjusted=true&sort=asc&limit=120&apiKey=)

**Result**
{
 "ticker": "X:ETHUSD",
 "queryCount": 0,
 "resultsCount": 0,
 "adjusted": true,
 "status": "OK",
 "request_id": "229c3d7e3cf9d42a28f5c945d9da7901"
}

**Expected Result**
Minute data on 2021-12-23

**Additional context**
Crypto minute aggregate data for all tickers on 2021-12-23 seems missing.

**Comment by jrbell19** [comment]
This is a known issue. We are currently working on a solution to backfill the missing data. Apologies for the inconvenience.

**Comment by jrbell19** [comment]
This has been backfilled
