### ISSUE TITLE
Dividend API v2/v3 differences: Split adjustement

### ISSUE THREAD

**Issue by bluelu** [polygon-io/issues#188]
Hi,

V2 returns non split adjusted dividends, and the new API seems to return split adjusted dividends. Is this the expected behaviour?

Example:
/v3/reference/dividends?ticker=AAPL&ex_dividend_date=2020-08-07&limit=100&
-> {"cash_amount":0.205,"declaration_date":"2020-07-30","dividend_type":"CD","ex_dividend_date":"2020-08-07","frequency":4,"pay_date":"2020-08-13","record_date":"2020-08-10","ticker":"AAPL"}

While the old one returns:
{"ticker":"AAPL","exDate":"2020-08-07","paymentDate":"2020-08-13","recordDate":"2020-08-10","amount":0.82}

It looks like in v3, dividends are split adjusted like on yahoo finance, cf.https://finance.yahoo.com/quote/AAPL/history?period1=947721600&period2=1659312000&interval=capitalGain%7Cdiv%7Csplit&filter=div&frequency=1d&includeAdjustedClose=true

Nasdaq reference(not split-adjusted):
https://www.nasdaq.com/market-activity/stocks/aapl/dividend-history

Communication apple:
https://investor.apple.com/dividend-history/default.aspx

<html>
<body>

July 30, 2020 | August 24, 2020 | August 31, 2020* | N/A | 4-for-1 Stock Split
-- | -- | -- | -- | --
July 30, 2020 | August 10, 2020 | August 13, 2020 | $.82 | Regular Cash

</body>
</html>

Thanks

**Comment by bluelu** [comment]
@jrbell19 

Any update on this since you are also deprecating the old API.

There seems to be a new issues with this new API:
- The dividends are split adjusted while the old ones are not. In addition, you somehow seem to handle the splits wrongly when the split and dividend are announced or executed on the same month (see example above), or the following example:
Example: - AFL:2018-02-20 old:0.26 new:0.52
 
- The API does not return dividends anymore for stocks which are not listed anymore after 2021-12-20: 

It does not return any data anymore for stocks where the old APi returned data: examples:
["ABDC","ABX","ACGLP","ACIM","ACSG","ADRD","ADRU","AFHBL","AGGE","AGGP","AGN","AGNCB","AGND","AHC","ALSK","ALTA","AMCA","AMGP","AMID","AMJL","AMRB","AMTD","AMU","ANDX","ANH","AOIL","APC","APU","ARD","ASFI","ASRVP","ATU","ATV","AUGR","AUO","AVH","AVX","AXJL","AXJV","AYR","BAF","BBF","BBK","BBT","BBX","BCEI","BCOM","BCRH","BCTF","BDCL","BDCS","BDGE","BEF","BEMO","BERN","BFO","BFY","BGG","BGIO","BHGE","BIKR","BKJ","BKK","BKS","BMLP","BOCH","BOKFL","BOON","BPFH","BPL","BPOPN","BPR","BPRAP","BPY","BPYU","BQH","BRGL","BRKS","BRSS","BSAE","BSCJ","BSCK","BSCL","BSD","BSE","BSJJ","BSJK","BSJL","BSML","BT","BUY","BUYN","BVAL","BXG","BXS","BZM","CAI","CARO","CBMB","CBND","CBS","CBS.A","CBSHP","CCA","CCC","CCR","CDMOP","CEFL","CEO","CEZ","CHA","CHEP","CHFC","CHKR","CHL","CHSP","CHU","CIVBP","CJNK","CLCT","CLDB","CLDC","CLGX","CLI","CLNC","CLNY","CMD","CMFN","CMFNL","CMO","CNBKA","CNHX","CNXM","COG","COMG","CORE","COT","COWNZ","CPL","CPTA","CROP","CSFL","CSS","CSWCL","CTB","CTL","CTWS","CUB","CVA","CWAI","CXO","CXP","CY","CYOU","CZFC","CZZ","DBAP","DBCP","DBKO","DCIX","DDEZ","DDJP","DEFA","DEMG","DESC","DEST","DEWJ","DEZU","DF","DHDG","DHXM","DIVY","DL","DLPH","DNBF","DNKN","DOGS","DPK","DQML","DRAD","DRYS","DSE","DVCR","DVEM","DVHL","DVP","DVYL","DWAQ","DWDP","DWFI","DWTR","DYB","DYLS","DZK","EASI","EBAYL","EBSB","ECA","ECT","EE","EEB","EEI","EFF","EFFE","EGIF","EGOV","EHT","EMAG","EMCG","EMCI","EMEM","EMIH","ENBL","EQM","EQWM","ESGF","ESGL","ESGW","ESV","ESXB","ETFC","ETH","ETM","EUFL","EUMF","EUMV","EUXL","EV","EVY","EWEM","EXT","FAUS","FBSS","FCAN","FCAU","FCBP","FDEF","FDUSL","FELP","FEU","FFG","FG","FGP","FHK","FI","FII","FINU","FINZ","FIV","FKO","FLIO","FLIR","FMK","FONE","FRAK","FRED","FRN","FSB","FSIC","FSKR","FSLF","FTR","FTVA","FVL","FWDB","FXSG","GAINL","GAINM","GARD","GARS","GASX","GBLIZ","GCAP","GCE","GDG","GDVD","GDXX","GECCL","GEX","GFNCP","GFNSL","GFY","GGM","GGO","GHII","GLADN","GLBY","GLIBP","GLOG","GMLP","GMLPP","GMZ","GNC","GOAT","GOODM","GOODP","GOV","GOVNI","GRA","GRAM","GRI","GRIF","GSB","GSH","GSVC","GUDB","GULF","GXF","HAO","HAUD","HBANN","HBANO","HCAP","HCAPZ","HCFT","HCHC","HCLP","HDLV","HECO","HEWI","HEWL","HEWP","HEWW","HEWY","HFBC","HFXE","HFXJ","HONR","HPT","HRC","HRS","HSPX","HUSE","HWCC","HWCPL","HX","HYDD","HYIH","HYND","HYXE","IBBJ","IBCD","IBDC","IBDK","IBDL","IBDM","IBKC","IBKCO","IBKCP","IBMH","IBMI","IBMJ","IBTA","ICBK","IEMD","IEMV","IFEU","IFIX","IFLY","IGIH","IGVT","IHYD","IHYV","IID","IMFC","IMFD","IMFI","IMFP","INB","INBKL","INF","IPE","IPFF","IPHS","IPLDP","IRET","IRR","ISCA","ISDS","ITE","JCAP","JCOM","JDD","JE","JEC","JHB","JHD","JHY","JKD","JKE","JKF","JKG","JKH","JKI","JKJ","JKK","JKL","JMF","JMLP","JMP","JMT","JPED","JPEU","JPGB","JPGE","JPHF","JPMF","JPMV","JPNL","JTA","JTD","KCAP","KCAPL","KCCB","KCNY","KEM","KNL","KNOW","KOL","KSU","LABL","LANDP","LB","LBDC","LBY","LDRI","LDRS","LINX","LKSD","LLQD","LM","LMLP","LMNX","LNGR","LOGM","LOR","LPT","LRAD","LRET","LTM","LTS","LTSF","LTSK","LTSL","LTXB","LVHB","LVHE","LVIN","LVL","LVUS","MAGS","MBG","MBTF","MCC","MDCA","MDLY","MDP","MELR","MEN","MFINL","MFNC","MFSF","MIDZ","MIE","MINI","MLHR","MLPC","MLPE","MLPG","MLPI","MLPQ","MLPY","MLPZ","MLQD","MLTI","MNE","MORL","MPVD","MRCCL","MRRL","MSBF","MSL","MSUS","MTSC","MTT","MUS","MVC","MVIN","MXDE","MXIM","NBL","NBLX","NCB","NCI","NEWM","NEWTI","NFO","NGHC","NGHCN","NGHCO","NGHCP","NGHCZ","NHA","NHF","NJV","NNA","NPN","NRE","NTRSP","NXR","NYMTO","NYV","OAK","OASM","OCSI","OCSLL","OFSSL","OHAI","OLBK","OLD","OMOM","OPB","OPINI","OQAL","ORG","ORIT","OSB","OSBCP","OSIZ","OTTW","OVLU","OVOL","OYLD","OZM","PACA","PBBI","PCI","PDEV","PDLI","PE","PEGI","PEK","PER","PFBI","PICO","PIHPP","PIR","PJC","PKO","PLC","PLCY","PLT","PMOM","PMR","POL","POPE","PPDM","PPEM","PPLC","PPLN","PPMC","PPR","PPSC","PQLC","PQSG","PQSV","PRID","PRME","PRSC","PRSP","PSDO","PSM","PTVCA","PTVCB","PUB","PXLG","PXLV","PXMG","PXMV","PXSG","PXSV","PZD","QADA","QADB","QEP","QGTA","QTRH","QTS","QVM","RAVN","RBC","RBS","RECN","REDV","REEM","REFA","RFAP","RFUN","RGLB","RIDV","RIF","RILYH","RILYI","RIVE","RMRM","ROGS","RORE","ROYT","RPAI","RPUT","RTL","RTN","RUSS","RVEN","RVRS","RWW","RXN","SAGG","SALT","SBBX","SBFGP","SBGL","SBLKZ","SCAP","SCID","SCIF","SCIJ","SCIU","SCIX","SCTO","SDAG","SDLP","SDR","SDT","SDYL","SEA","SEMG","SFHY","SGB","SHLD","SKIS","SLIM","SMEZ","SMHD","SMLL","SMTA","SNE","SNH","SNHNI","SNHNL","SNHY","SNR","SOIL","SONA","SOVB","SPAR","SPKE","SPKEP","SPN","SPYB","SRF","SSFN","SSI","SSW","STAY","STI","STND","SVBI","SXCP","SYE","SYG","SYMC","SYV","SYX","TAO","TBLU","TCBIL","TCBIP","TCF","TCGP","TCO","TCP","TCRD","TERM","TERP","TFIV","TFLT","TGE","TI.A","TIF","TIVO","TLDH","TLEH","TLRD","TMK","TOO","TOT","TOWR","TPCO","TRCB","TRCO","TRK","TRMT","TRWH","TSLF","TSS","TSU","TTS","TUZ","TYBS","TYNS","TYPE","UBNK","UBNT","UBSH","UCFC","UFS","UN","USDY","UTX","VALX","VAM","VEDL","VER","VETS","VGFO","VIAB","VRTSP","VSM","VTA","VTRN","WBAL","WBIA","WBIB","WBIC","WBID","WBIE","WCFB","WCHN","WDR","WDRW","WEBK","WGP","WPG","WRI","WTR","WYND","XAN","XEC","XKCP","XKFF","XKFS","XKII","XKST","XLEY","XLSY","XLTY","XLUY","XMX","XTH","YGYI","YIN","YLCO","YMLI","YMLP","ZBIO","ZCAN","ZDEU","ZF","ZGBR","ZHOK","ZJPN","ZMLP"]
-

**Comment by bluelu** [comment]
@jrbell19 Do you have an update here? in your doc the old API is marked to stop working in 1 month?

**Comment by bluelu** [comment]
@matichenor could you please have a lookt at this? Thanks

**Comment by matichenor** [comment]
Hey, @bluelu , sorry but I missed the notification on this thread.  I'm asking our eng team to step in and take a look.  They should be able to clarify on adjust vs un-adjusted split dividends.

**Comment by jrbell19** [comment]
@bluelu So sorry we missed this. Just so we understand the issue at hand here:

> .... you somehow seem to handle the splits wrongly when the split and dividend are announced or executed on the same month (see example above), or the following example:

> Example: - AFL:2018-02-20 old:0.26 new:0.52

Could you elaborate on what you're expecting to see? Both v2 and V3 return the cash amount as ".26" for the dividend paid on March 3rd, 2018. I am seeing some discrepancies between the dates returned, is this what you're referring to?

**Comment by bluelu** [comment]
There is a "2 for 1" split of AFL on March 19 2018, after the dividends are paid. 

Based on testing, it seems that v2 dividends are not split adjusted. V3 seems to be (even though your documentation doesn't mention it).

So in this specific case and for that dividend, the values should be different. But they are equal which goes against the logic of how you return previous dividends. It would be helpful to know how this split adjustment in v3 works.

**Comment by bluelu** [comment]
@jrbell19 
It seems that in the new API the dividends are always split adjusted in V3, but not in V2.

Is this the intended behaviour? If yes, can you add this to your migration notes?

**Comment by bluelu** [comment]
According to support, the dividends are split adjusted now.
