### ISSUE TITLE
Incorrect splits correction in aggregate market history

### ISSUE THREAD

**Issue by montjoye-gitHub** [polygon-io/issues#19]
**URL**
https://api.polygon.io//v2/aggs/grouped/locale/US/market/STOCKS/

**Result**
Splits are well corrected before and after the ex-date of the splits, but not on the ex-date day.
This issue causes abnormal prices for this specific day on any stock with one or more split in its history. (e.g. EWJ on 2016 Nov. 7)

**Expected Result**
Fix the wrong splits correction.

**Screenshots**
![image](https://user-images.githubusercontent.com/56591361/82470060-23ea1680-9ac5-11ea-96c2-723eec0a534a.png)

**Desktop (please complete the following information):**
 not relevant

**Additional context**
not relevant

**Comment by montjoye-gitHub** [comment]
I am also suggesting you to return the raw prices instead of trying to modify them by any corporate action ratio. Thus the end-of-day prices will be consistent with the intraday prices.

**Comment by jrbell19** [comment]
Apologies for the delayed response on this. this is a known issue that we are currently working to address. If you could continue reporting any split errors we will be sure to correct them asap.

**Comment by spazmodius** [comment]
This split for TQQQ says 2017-01-11, but it actually happened on 2017-01-12

![image](https://user-images.githubusercontent.com/259818/98047699-6052ca00-1dfa-11eb-833d-5e8e4603398f.png)

**Comment by jrbell19** [comment]
This has been resolved
