### ISSUE TITLE
Historic Forex tick data missing

### ISSUE THREAD

**Issue by PommeVerte** [polygon-io/issues#190]
I've noticed a lot of gaps in data. Below are a couple of the ones I can't find:

**URL**
The RESTful API call you are making (please be sure to omit your API key)
https://api.polygon.io/v1/historic/forex/USD/EUR/2022-01-12?limit=100
https://api.polygon.io/v1/historic/forex/USD/EUR/2022-01-19?limit=100
https://api.polygon.io/v1/historic/forex/USD/EUR/2022-01-20?limit=100

**Result**
I'm getting Null ticks 
`{
 "day": "2022-01-19",
 "map": {
  "ap": "ask",
  "bp": "bid",
  "t": "timestamp"
 },
 "msLatency": "0",
 "pair": "USD/EUR",
 "status": "success",
 "ticks": null,
 "type": "forex"
}`

**Expected Result**
Expecting some data. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Python requests and browser requests both return no data

**Additional context**
N/A

**Comment by jrbell19** [comment]
This is a known issue. We are working on a solution to backfill this data. 

Apologies for the inconvenience!

**Comment by jrbell19** [comment]
Data has been backfilled
