### ISSUE TITLE
New Quotes API returns previous last entry in addition to new entries when using next_url

### ISSUE THREAD

**Issue by bluelu** [polygon-io/issues#191]
Problem:
vX/quotes has first entry of next_url same as last entry of previous url 
Example:
Any example should work, but setting limit=1 actually leads to infinite loop

api.polygon.io/vX/quotes/AAPL?timestamp=2020-10-01&limit=1
Leads to next_url: 
https://api.polygon.io:443/vX/quotes/AAPL?cursor=YXA9MSZhcz0mbGltaXQ9MSZvcmRlcj1hc2Mmc29ydD10aW1lc3RhbXAmdGltZXN0YW1wLmd0ZT0yMDIwLTEwLTAxVDA4JTNBMDAlM0EwMC4wMzc2ODUxMzhaJnRpbWVzdGFtcC5sdD0yMDIwLTEwLTAyVDA0JTNBMDAlM0EwMFo
Which leads to the same entry 

The Problem is not present in the new trades API.

**Comment by Stormy110** [comment]
Hi there, thanks for reaching out and sharing this! I will make a ticket with my team to resolve this.

**Comment by matichenor** [comment]
We have created a ticket for this issue in our internal boards and plan to address it soon.

**Comment by matichenor** [comment]
Internal Reference Ticket: backend/421

**Comment by matichenor** [comment]
Actually, after talking to our esteemed engineering team it looks like the fix for this already went out.  Please let us know if you are still seeing the issue.

Thank you for reporting the problem to us!
