### ISSUE TITLE
Invalidly structured option symbol expiration date

### ISSUE THREAD

**Issue by ktayah** [polygon-io/issues#193]
**Client**
No client, manually connecting

**Issue**
Received invalidly structured data when connecting and subscribing to a minutely option aggregate. For the stock `SDS` received
`O:SDS1220204C00003000` which contained the extra digit `1` between the underlying ticker and the `C`.

**Expected Result**
Expected to receive `O:SDS220204C00003000` (no 1 after SDS)

**Screenshots**
From website:
<img width="376" alt="Screen Shot 2022-02-04 at 10 56 00 AM" src="https://user-images.githubusercontent.com/32495802/152560405-8c17e8bb-f62c-47df-a90b-29d1e32dbd89.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version N/A

**Comment by jrbell19** [comment]
Hi there, 

This is actually the result of a corporate action, in this case, a 1-for-5 reverse stock split. 

Here's the OCC memo declaring the adjustment: https://infomemo.theocc.com/infomemos?number=49850
