### ISSUE TITLE
Delisted symbol aggregated bars have indeterministic timestamp

### ISSUE THREAD

**Issue by heydavid525** [polygon-io/issues#195]
**URL**
https://api.polygon.io/v2/aggs/ticker/AGN/range/5/minute/2020-02-01/2020-03-01?adjusted=false&sort=asc&limit=123&apiKey=

(AGN was delisted in May, 2020)

**Result**
If run multiple times, the resulting timestamps are different. I've received the following timestamps:

1582117980000 (February 19, 2020 8:13:00 AM EST)
1582118040000 (February 19, 2020 8:14:00 AM EST)
1582118100000 (February 19, 2020 8:15:00 AM EST)

**Expected Result**
The REST API is not even restful, and the aggregation doesn't happen over a well-defined 5 minute.

**Comment by jrbell19** [comment]
Hi there, 

I can't seem to replicate this issue. Are you seeing this behavior for any other tickers or requests?
