### ISSUE TITLE
Missing historical quotes for first 7 minutes for many symbols on Feb 18, 2022

### ISSUE THREAD

**Issue by mobiusstripinf** [polygon-io/issues#196]
There seems to be missing historical quotes for the first ~7 minutes after 9:30am ET for many symbols on Feb 18, 2022.

For example, for the symbol ABBV, the first quote (after 9:30am ET) I receive has a timestamp of around 9:37am instead of shortly after 9:30am. From what I've checked briefly, this problem seems to apply to all NYSE-listed stocks, but not NASDAQ stocks, but I am not sure.

Here is an example query I used:
https://api.polygon.io/v2/ticks/stocks/nbbo/ABBV/2022-02-18?timestamp=1645194600000000000&reverse=false&limit=10

It would be good if this problem could be fixed soon, since many trading systems may depend on having these historical quotes.

**Comment by jrbell19** [comment]
This was resolved as of 02/20/2022. 

Apologies for the inconvenience.
