### ISSUE TITLE
Incorrect Financials VX data - basic_earnings_per_share (Quarterly & Annual) not matching with stock's actual EPS

### ISSUE THREAD

**Issue by naveenrb98** [polygon-io/issues#199]
**URL**
https://api.polygon.io/vX/reference/financials?ticker=AAPL&filing_date.lt=2022-02-26&filing_date.gt=2015-02-26&timeframe=quarterly
https://api.polygon.io/vX/reference/financials?ticker=AAPL&filing_date.lt=2022-02-26&filing_date.gt=2015-02-26&timeframe=annual
**Result**
basic_earnings_per_share Q3 2020  - 2.61
basic_earnings_per_share FY 2019  - 11.97
**Expected Result**
Expected basic_earnings_per_share for Q3 2020 is 0.65
Expected basic_earnings_per_share for FY 2019 is 2.97
**Screenshots**
![image](https://user-images.githubusercontent.com/99675647/156191345-0fbc968e-64dc-4b10-8cc9-96e0e85e6a7a.png)

Actual values have been verified across multiple sources and the deviation seems to be large.
**Desktop (please complete the following information):**
 - OS: macOS
 - Python API request

**Additional context**

**Comment by Stormy110** [comment]
Hi there, thanks for sharing this information! I will make a ticket with my team to investigate these discrepancies.

**Comment by jrbell19** [comment]
According to AAPL's Q3 2020 filing, the Basic EPS was 2.61. https://www.apple.com/newsroom/pdfs/FY20-Q3_Consolidated_Financial_Statements.pdf
