### ISSUE TITLE
Incorrect Anchor link

### ISSUE THREAD

**Issue by jrbell19** [polygon-io/issues#20]
**Describe the bug**
Daily open/close endpoint has an incorrect anchor link. URL should be '_' instead of '-'

**To Reproduce**
Current Link : https://polygon.io/docs/#get_v1_open-close__symbol___date__anchor
Should be : https://polygon.io/docs/#get_v1_open_close__symbol___date__anchor

**Expected behavior**
Link should take me right to the endpoint, but it does not currently.

**Comment by teambailey** [comment]
Appears to be fixed now. @jrbell19 this is referring to the sidebar link correct?

**Comment by jrbell19** [comment]
@teambailey Looks like the link has changed, but its still happening for me. 

Hitting this link ( https://polygon.io/docs/#get_v1_open_close__symbol___date__anchor ) takes me to getting started, not the Daily open / close endpoint

**Comment by teambailey** [comment]
@jrbell19 you'll see the Getting Started section of the page first when you hit that URL b/c the page is still trying to load all the no static parts. The expected behavior is for the page to move to requested section after it loads. Is that happening or is it just hanging at the top?

**Comment by jrbell19** [comment]
@teambailey I see. Working!

**Comment by teambailey** [comment]
Nooice! @jrbell19
