### ISSUE TITLE
The client-js package build is failing.

### ISSUE THREAD

**Issue by jdluker1** [polygon-io/issues#200]
**URL**
[client-js build
](https://github.com/polygon-io/client-js/runs/5542639088?check_suite_focus=true)

**Result**
The package does not install.

**Expected Result**
The package should install.

**Screenshots**
none.

**Desktop (please complete the following information):**
 - macOS

**Additional context**

**Comment by matichenor** [comment]
We're taking a look now.

**Comment by jdluker1** [comment]
Thank you! If you need me to help debug or test something, just let me know.

Thanks again,
Jarrod

Jarrod Luker
***@***.***

**Comment by matichenor** [comment]
Hi @jdluker1 , the js client library itself should work fine and is accessible via npm.  

The build failure you linked is just for a github documentation site.  Our API doc can be found here: https://polygon.io/docs/stocks/getting-started .

Client-specific doc can be found here: https://github.com/polygon-io/client-js

Are you seeing a functional issue with using the js client on your end?

**Comment by jdluker1** [comment]
There was no functional issue.

Yesterday I attempted to upgrade to 5.0.2 and there was only a License, package.json, and README.md file installed with the package. I attempted to back out to 5.0.1, but with the same results.

Presently... with no changes on my end, I can install the package, but I get 5.0.1 after performing `npm install --save @polygon.io/client-js`.

**Comment by matichenor** [comment]
Apologies for the confusion.  We've rolled out an update, this should be resolved as of 5.0.3.

**Comment by matichenor** [comment]
Issue has been fixed.  We're looking at an improvement to our CI/CD to prevent this in the future.
