### ISSUE TITLE
Crypto aggregates (bars) is returning a cut off time window

### ISSUE THREAD

**Issue by mjwweb** [polygon-io/issues#203]
**URL**
https://api.polygon.io/v2/aggs/ticker/X:BTCUSD/range/5/minute/2021-03-18/2022-03-18?adjusted=true&sort=asc&limit=50000&apiKey=

**Result**
The time window of the results set returns aggregates from 2021-03-18 to 2021-04-21

**Expected Result**
The time window of the results set should return aggregates from 2021-03-18 to 2022-03-18

**Screenshots**
first result (2021-03-18)
![firstAggregate](https://user-images.githubusercontent.com/96453373/159060027-620ee646-9ad3-4035-8ab8-d2b527a5b9dc.JPG)
last result (2021-04-21)
![lastAggregate](https://user-images.githubusercontent.com/96453373/159060028-dcabb6a1-fda1-458a-9c18-55dbb96c7fd6.JPG)

**Desktop (please complete the following information):**
- browser (Chrome)

Additional Information
- I am on the paid currencies starter plan

**Comment by matichenor** [comment]
Thanks for reporting this issue @mjwweb .  I've been able to reproduce and we are investigating the problem.

**Comment by jrbell19** [comment]
Cleaning up some issues in the backlog. This is expected functionality given the limit parameter's functionality. The limit of 50k query's the underlying aggregate, in this case, minutes to stitch together the 5-minute bars. 50,000 minutes returns around a month of data. https://polygon.io/knowledge-base/article/how-does-polygon-limit-parameter-work-for-the-aggregates

You'll need to paginate according to the last result to obtain the next set of results. Apologies for the confusion/delay.
