### ISSUE TITLE
Reverse Splits Not Implemented

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#21]
Aggregates for VXX not adjusting for reverse splits on October 5 2012 and Nov  8 2013

**Comment by qrpike** [comment]
It seems these splits are missing from our DB. We need to confirm these splits, and if so, get these added @jrbell19

**Comment by jrbell19** [comment]
I went in and added both of these splits. Thanks for making us aware of this!

https://api.polygon.io/v2/aggs/ticker/VXX/range/1/day/2012-10-04/2012-10-09?apiKey=

https://api.polygon.io/v2/aggs/ticker/VXX/range/1/day/2013-11-07/2013-11-09?apiKey=
