### ISSUE TITLE
Same request to Forex Aggregates endpoint returns 2 different results randomly

### ISSUE THREAD

**Issue by lvnfg** [polygon-io/issues#212]
**URL**
https://api.polygon.io/v2/aggs/ticker/C:EURUSD/range/1/minute/2021-12-30/2022-01-31?adjusted=true&sort=asc&limit=50000

**Result**
Randomly returns either 32855 or 31415 records

**Expected Result**
Returns the same number of records each time

**Screenshots**
![image](https://user-images.githubusercontent.com/25565516/167982705-459679d7-81d1-4961-b41c-95047370b640.png)

**Desktop (please complete the following information):**
 - OS: Debian 11 Buster
 - Browser: n/a
 - Version: n/a

**Additional context**
It appears only this specific request is affected. All other requests return consistent results.
[Update]: the bug shows up on all queries including the date range 2022-01-01 to 2022-01-03. Starting from 2021-01-15 results are consistent again. I'm not sure what happens for 2022-01-04 to 2022-01-14 as we didn't test that range.

**Comment by jrbell19** [comment]
Thanks for bringing this to our attention. We'll investigate and will circle back with some information. 

Apologies for the confusion!
