### ISSUE TITLE
Missing SPY Option Data

### ISSUE THREAD

**Issue by heydavid525** [polygon-io/issues#213]
**URL**
https://api.polygon.io/v2/aggs/ticker/O:SPY220520C00403000/range/1/day/2022-03-20/2022-03-28?adjusted=true&sort=asc&limit=118

**Result**
{
 "ticker": "O:SPY220520C00403000",
 "queryCount": 0,
 "resultsCount": 0,
 "adjusted": true,
 "status": "OK",
 "request_id": "f4e56309d79dda92350d608871cf9415"
}

**Expected Result**
There's no bar returned. Does it mean that there was no trades on this contract for those dates? or it's missing data? (I notice that this is a deep in the money option contract on those dates)

**Comment by jrbell19** [comment]
@heydavid525, It looks like there were no trades that have taken place for this contract during this time period. If you change the timespan to "month", you can see the total volume for March was only 5 contracts.

I hope this clears things up! Please let us know if you see anything else out of the ordinary.
