### ISSUE TITLE
Missing quotes for 2022-05-26

### ISSUE THREAD

**Issue by jbabyhacker** [polygon-io/issues#214]
**URL**
Stock Quotes API
https://api.polygon.io/v3/quotes/SPY?timestamp=2022-05-26&order=asc&limit=50000

**Result**
Missing a lot of quotes on 2022-05-26. On this day, there were 11,201 tickers that had trades occur on them, but only 2,712 tickers had quotes for them. Popular tickers such as AAPL and SPY have no quotes for example.

**Expected Result**
Expect number of tickers that have quote data for 2022-05-26 to be over 11,000.

**Comment by jbabyhacker** [comment]
Resolved.

**Comment by nerkka** [comment]
> Resolved.

How is this resolved? I'm still seeing the same issue
