### ISSUE TITLE
No SPY option trades between from 2022-05-23 to 2022-06-10

### ISSUE THREAD

**Issue by jbabyhacker** [polygon-io/issues#216]
**URL**
All SPY option trades inclusive between 2022-05-23 through 2022-06-10
https://api.polygon.io/v3/trades/O:SPY...

**Result**
A response with no results, but with status "OK"

**Expected Result**
Actual trade data or an error indicating why it isn't there.

**Additional context**
SPY option trade data is available inclusive 2022-05-02 through 2022-05-20, but after the 20th, no more SPY option trade data is available.

**Comment by Stormy110** [comment]
Hi there, apologies for the delay! Are you still not able to see any SPY option trades during that time? I am able to query SPY trades for this contract on 05-23-2022 - https://api.polygon.io/v3/trades/O:SPY220523C00400000?timestamp=2022-05-23&apiKey=***

**Comment by jbabyhacker** [comment]
Not sure, I have changed my subscription since then.
