### ISSUE TITLE
I'm using Websocket.Trades for 4096 tickers at the same time, after 20 minutes I start to receive messages with 10 seconds delay.

### ISSUE THREAD

**Issue by CatalaniCD** [polygon-io/issues#217]
**Client**
I'm using : https://polygon.io/docs/stocks/ws_stocks_t#Trades

**Issue**
I'm using Websocket.Trades for 4096 tickers at the same time, after 20 minutes I start to receive messages with 10 seconds delay.

**Expected Result**
The expected result is to receive all available trades with the least delay possible and below 1 second delay

**Desktop (please complete the following information):**
- Linux Environment
- Laptop ( CPU i3 Quadcore, 4Gb Ram )
 
**Additional context**

**Comment by Stormy110** [comment]
Hi there, apologies for the delay! Typically a delay or disconnect means the data isn’t being consumed fast enough. There is a server-side buffer and if it fills the connection will be delayed and eventually killed. The best way to mitigate this is to read the packets off of the network and immediately put them into a queue. Have a separate thread which is parsing the messages and running any logic on them.
