### ISSUE TITLE
400 Err

### ISSUE THREAD

**Issue by mbvg1** [polygon-io/issues#219]
I am getting an error: 400 ERR     {"status":"ERROR","request_id":"xxxxxxxxxxxxxxxxxx","error":"API Key was not provided"} Anyone have an idea how to solve this? We added the api key and tried multiple times with multiple api keys. Thanks!

**Comment by Stormy110** [comment]
Hi there, apologies for the delay! What was the specific request that you tried to send?

**Comment by NadirLumin** [comment]
What was the fix?

**Comment by Stormy110** [comment]
The user never shared the specific request. However, the error message indicates the API key was not being added to the query correctly. Are you receiving the same error?
