### ISSUE TITLE
Inconsistent between doc and actual result

### ISSUE THREAD

**Issue by sharok** [polygon-io/issues#22]
**URL**
/v2/ticks/stocks/nbbo/{ticker}/{date}

**Result**
1. The documentation says that response contains ticker as `T` field and it's required. But It's not present in the response.
2. The documentation says that field`f` is not optional. But It's not always present in the response.

**Expected Result**
Documentation and actual response should match.

**Comment by jrbell19** [comment]
Sorry for the confusion. As we continue to update the documentation we will make these fields available with accurate descriptions.
