### ISSUE TITLE
Latest GOVT Quote Data not available

### ISSUE THREAD

**Issue by russell-atomic** [polygon-io/issues#227]
**URL**
https://api.polygon.io/v2/last/nbbo/GOVT

**Result**
```
{
  "results": {
    "P": 0,
    "S": 0,
    "T": "GOVT",
    "X": 0,
    "c": [
      1
    ],
    "i": [
      605
    ],
    "p": 22.8,
    "q": 65033683,
    "s": 1,
    "t": 1670374800034727200,
    "x": 12,
    "y": 1670374800033837000,
    "z": 1
  },
  "status": "OK",
  "request_id": "98ee141b1bbe89a7ee53aa46c925ad78"
}
```

**Expected Result**
I expect last "P", "S", "X" to be populated

**Screenshots**
Comparison between GOVT and MBB showing GOVT empty data.
![image](https://user-images.githubusercontent.com/106696026/206078087-84b1021f-85c0-4366-9363-bda1a1a0accb.png)

New v3/Quotes API also doesnt have data, making api migration not a solution.
![image](https://user-images.githubusercontent.com/106696026/206078321-30f392c0-5e8b-414d-bd98-31e83178084d.png)

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version Version 107.0.5304.121 (Official Build) (arm64)

**Additional context**
Similar tickers like BND, MBB, VCIT and IUSB do not seem to have the same behavior. Requests made around 6:30 PM Pacific Standard on Tuesday 12/6. So weekday and after hours

**Update**
At midnight PST, GOVT began having correct data. Seems like a timing problem?

**Comment by jrbell19** [comment]
Sorry we missed this. This may have been an erroneous quote broadcasted by the SIP. Querying this now, we can see that the quote returned is a corrected quote, which may have only been sent with a bid message making the ask '0': 

  {
            "ask_exchange": 0,
            "ask_price": 0,
            "ask_size": 0,
            "bid_exchange": 12,
            "bid_price": 22.8,
            "bid_size": 1,
            "conditions": [
                1,
                81
            ],
            "participant_timestamp": 1670374800033837000,
            "sequence_number": 65033683,
            "sip_timestamp": 1670374800034727200,
            "tape": 1

Apologies for the confusion. I do recommend moving to v3 if you have not already.
