### ISSUE TITLE
Ticker Details v3 can't handle encoded slash in ticker

### ISSUE THREAD

**Issue by mlathan** [polygon-io/issues#231]
**URL**
https://api.polygon.io/v3/reference/tickers/AGM%2fA?date=2016-10-25

**Result**
HTTP/1.1 404 Not Found

**Expected Result**
For 2016-10-25 the Tickers endpoint reported the ticker AGM/A (URL encoded AGM%2FA).
Requesting Ticker Details v3 for AGM/A on 2016-10-25 must return details for the ticker instead of 404 Not Found.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Browser Firefox
 - Version 108.0.1 (64-bit)

**Additional context**
My guess is, that the Ticker Details v3 endpoint does not correctly handle the slash in the ticker.
Tickers API just works: https://api.polygon.io/v3/reference/tickers?ticker=AGM%2fA&date=2016-10-25
Ticker Details API is not working: https://api.polygon.io/v3/reference/tickers/AGM%2fA?date=2016-10-25
... same encoded ticker.

**Comment by jrbell19** [comment]
Hi there, 

You'll need to query AGM.A to successfully return Ticker Details for this ticker. 

You can use the Tickers endpoint to search through the different share classes of a security and find out the queryable ticker: https://api.polygon.io/v3/reference/tickers?search=AGM&active=true&apiKey=
