### ISSUE TITLE
Request for aggregates (Bars) returns empty result (Feb 2022)

### ISSUE THREAD

**Issue by mferreri86** [polygon-io/issues#232]
**URL**
https://api.polygon.io/v2/aggs/ticker/AAMC/range/1/minute/2022-02-01/2022-02-28?adjusted=true&sort=asc&limit=20000

**Result**
{
    "ticker": "AAMC",
    "queryCount": 0,
    "resultsCount": 0,
    "adjusted": true,
    "status": "OK",
    "request_id": "f592854655a8321521adebf528e0b611"
}

**Expected Result**
resultsCount should be greater than 0

**Comment by jrbell19** [comment]
It looks like AAMC did not begin trading until 2022-03-21: https://api.polygon.io/v3/trades/AAMC?order=asc&timestamp.gte=2022-01-01&apiKey=

It does appear that there was a ticker change in 2013, but there has been no trading since then.

**Comment by mferreri86** [comment]
I see, thank you very much.

One last following question about the bars enpoint, this call returns 21 results:
https://api.polygon.io/v2/aggs/ticker/AAMC/range/1/day/2021-10-01/2021-10-31?adjusted=true&sort=asc&limit=20000&apiKey=***

In these cases is it because there were a limited amount of trades in that month, or because Polygon has limited data on that ticker?

**Comment by jrbell19** [comment]
Let me check, there seems to be a daily aggregate for each trading day in October, so I would expect them all to be returned.

**Comment by jrbell19** [comment]
Actually, there were only 21 trading days in October '21, so this makes sense. 

Apologies for the confusion.
