### ISSUE TITLE
Historical Options data

### ISSUE THREAD

**Issue by kenaschmidt** [polygon-io/issues#234]
**Is your feature request related to a problem? Please describe.**
Some option data is available as a current snapshot only (OI, IV, Greeks).  No historical requests are available.  Greeks/IV can be manually calculated but historical daily OI values would be very beneficial.

**Describe the solution you'd like**
Allow a timestamp parameter for options contract/chain requests to return calculated values as of.

**Describe alternatives you've considered**
Only current solution would be to request/store values daily.

**Comment by kenaschmidt** [comment]
Did not see that this was an existing request from May-22; I second the OP's request

https://github.com/polygon-io/issues/issues/210

**Comment by jrbell19** [comment]
@kenaschmidt Appreciate the feedback. This is something that we are working to prioritize, however I'm not sure of the timeframe to expect. I'll close this one out and tag you in the #210 request.
