### ISSUE TITLE
February 22 minute aggregates returning no results.

### ISSUE THREAD

**Issue by bmalumphy** [polygon-io/issues#235]
**URL**
[The RESTful API call you are making (please be sure to omit your API key)](https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/1677076800000/1677079600000?adjusted=false&sort=asc&limit=120&apiKey={KEY})

The value for the interval can vary a good bit and the value of the future timestamps can vary a good bit as well (from 1-3 hours)

The whole day seems to be messed up for egg bars.

**Result**
No results for a valid trading session. This seems to happen across multiple tickers in Tech.

**Expected Result**
To get the minute aggregates

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari, but this is true in a python script as well.
 - Version: Recent as of Feb 25, 2023

**Additional context**

Only seems to be true for this day (Feb 22, 2023).

**Comment by jrbell19** [comment]
This issue has been resolved. So sorry for the inconvenience. Please let us know if you see anything else out of the ordinary.
