### ISSUE TITLE
Unadjusted stock price after stock split

### ISSUE THREAD

**Issue by puddinator** [polygon-io/issues#238]
**URL**
https://api.polygon.io/v1/open-close/JEF/2023-01-11?adjusted=true

**Result**
Apologies for not having the exact response. 

The response shows a high of >$40 for Jef on 2023-01-11.

**Expected Result**
Jef had a 1046 for 1000 split on January 17, 2023. Before the split, the stock price for Jef on 2023-01-11 is indeed around $40. After the split, the adjusted stock price should be around ~$37, as is currently reflected on Google and Yahoo Finance.

**Comment by jrbell19** [comment]
These splits have been added, prices should be reflected accordingly. Apologies for the inconvenience. 

Please let us know if you see any similar issues.
