### ISSUE TITLE
X:BTCUSD wrong price info

### ISSUE THREAD

**Issue by DunderChief** [polygon-io/issues#246]
For BTCUSD, the candle at: 2017-04-15 23:02:00 has a low of 0.06 where the price should really be in the neighborhood of 1200

**Comment by jrbell19** [comment]
Here is the response for this minute: https://api.polygon.io/v2/aggs/ticker/X:BTCUSD/range/1/minute/1492311600000/1492398000000?apiKey=
```
{
"v": 2.7324176799999993,
"vw": 1188.0256,
"o": 1183.98,
"c": 1184.59,
"h": 1205.9,
"l": 1176.4,
"t": 1492311660000,
"n": 25
},
```
