### ISSUE TITLE
Ticker News - Returns no new results since March 26th

### ISSUE THREAD

**Issue by reddavis** [polygon-io/issues#25]
**URL**
The RESTful API call you are making (please be sure to omit your API key)

`https://api.polygon.io/v1/meta/symbols/AAPL/news?perpage=50&page=1&apiKey=asd`

`https://api.polygon.io/v1/meta/symbols/MSFT/news?perpage=50&page=1&apiKey=asd`

**Result**
What result are getting?

Latest news article is from 2020-03-26. I see similar for any other major company too.

```
[
  {
    "symbols": [
      "AAPL"
    ],
    "timestamp": "2020-03-26T23:52:51.000Z",
    "title": "Apple (AAPL): Despite Likely iPhone 12 Delays, the Risk-Reward Remains Compelling, Says Analyst",
    "url": "https://finance.yahoo.com/news/apple-aapl-despite-likely-iphone-235251688.html",
    "source": "finance yahoo",
    "summary": "When considering the fortunes of the FAANG family since the viral outbreak, it appears Apple (AAPL) has most to lose. Amazon and Netflix can count their internet driven models as particularly well set up for a hibernation period. And while Google and Facebook stand to lose significant advertising revenue",
    "image": "https://s.yimg.com/uu/api/res/1.2/Su.8VniRbi_GL2B3BruK5w--~B/aD0zMzc7dz0xMDI0O3NtPTE7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en-US/smarteranalyst_347/6909df17d6ef3af25ac79e2e6c0078d5",
    "keywords": [
      "aapl"
    ]
  },
....
```

**Expected Result**

More up to date news about the companies I'm querying.

**Screenshots**

**Desktop (please complete the following information):**
Desktop (please complete the following information):

- OS: macOS
- Browser: Firefox (but i also receive this curling the API)
- Version: 75.0

**Additional context**

**Comment by jrbell19** [comment]
This is actively being worked on. We'll be releasing a new News endpoint in the next few weeks that will keep the data fresh, along with a few more features. 

Apologies for the inconvenience

**Comment by ZBedjaJohnson** [comment]
Hi, are there any updates on this?

**Comment by pavanagrawal123** [comment]
hi @jrbell19 I also wanted to see if there were any plans for a streaming news API a-la TDA/IBKR?

**Comment by Sm0k3scr33n** [comment]
Any fix to this yet?

**Comment by c0x65o** [comment]
In May of 2020, you all said a few weeks. Any updates?

**Comment by jcragy** [comment]
Yes, the latest news from 'AAPL' is "2020-03-26T23:52:51.000Z"
 [1] "Apple (AAPL): Despite Likely iPhone 12 Delays, the Risk-Reward Remains Compelling, Says Analyst"                                                                                                                                                          

Can't wait till the 12 drops, should be sweet, 5G

**Comment by jrbell19** [comment]
This issue has been addressed by our new Ticker News vX endpoint: https://polygon.io/docs/get_vX_reference_tickers__ticker__anchor
