### ISSUE TITLE
Dividend RESTfulAPI: declaration date in future and after Ex-Date

### ISSUE THREAD

**Issue by fplein** [polygon-io/issues#254]
**URL**
https://api.polygon.io/v3/reference/dividends?declaration_date.gte=2023-06-01&sort=declaration_date&order=asc&limit=1000

**Result**
A dividend entry for USHY with declaration date (in the future) larger than ex dividend date:
`{"cash_amount":0.2331,"currency":"USD","declaration_date":"2023-11-24","dividend_type":"CD","ex_dividend_date":"2023-02-01","frequency":12,"pay_date":"2023-02-07","record_date":"2023-02-02","ticker":"USHY"}`.

**Expected Result**
Declaration date should always be smaller than ex dividend date (overall I would expect `declaration_date < ex_dividend_date < record_date <= pay_date` ). In this precise example, I believe it is just a typo, and I assume `"declaration_date":"2023-01-24"` should be the correct date.

**Comment by Stormy110** [comment]
This dividend has been adjusted. I will also look into our dividend sources to see why it was shown as such and if there are any more examples of this typo.
