### ISSUE TITLE
Potential MOS daily low price data error on 2023-01-24 (Polygon low 40.29, TV low 45.60, IB low 42.30, Investing low 45.36)

### ISSUE THREAD

**Issue by NeilJustice** [polygon-io/issues#268]
**URL**
https://api.polygon.io/v2/aggs/ticker/MOS/range/1/day/2023-01-24/2023-01-24?adjusted=false&apiKey=

Polygon daily data for MOS on 2023-01-24:

Open: 47.75
High: 50.4
**Low: 40.29**
Close: 48.46

Polygon daily candlestick in question as it appears on a chart:
![image](https://github.com/polygon-io/issues/assets/1912242/b17a9c6b-0904-4938-afa6-eeb747785b81)

TradingView low price for MOS on 2023-01-24:
![image](https://github.com/polygon-io/issues/assets/1912242/7bffe49d-2bae-4e61-a4df-370a6394de15)

Yahoo Finance low price for MOS on 2023-01-24:
![image](https://github.com/polygon-io/issues/assets/1912242/3410c06d-f4c0-466c-bc69-d3f92f12a788)

Interactive Brokers low price for MOS on 2023-01-24:
![image](https://github.com/polygon-io/issues/assets/1912242/4c398e0e-83e3-4660-88a6-8aff5fb2ca7e)

Investing.com low price for MOS on 2023-01-24:
![image](https://github.com/polygon-io/issues/assets/1912242/da9629b7-7333-4195-9c2a-9bc52d1a8cdf)

| Data Provider | MOS Low Price on 2023-01-24 |
| ------------- | ------------- |
| Polygon       | 40.29  |
| TradingView   | 45.60  |
| Yahoo Finance | 45.60  |
| Interactive Brokers | 42.30 |
| Investing.com | 45.36  |

Which data provider provides the True low price? What says the tick data for MOS on 2023-01-24?

**Comment by AHangstefer** [comment]
Hello again! This looks like another case where the trade is a dark pool trade. We include dark pool trades in our Aggregates. 
I'm seeing a number of dark pool trades for MOS on  2023-01-24 with a price of 40.29

Here's the query I made:
https://api.polygon.io/v3/trades/MOS?order=desc&limit=50000&timestamp=2023-01-24&apiKey=**

{
  conditions: [ 10, 37, 41 ],
  correction: 8,
  exchange: 4,
  id: '79371806191693',
  participant_timestamp: 1674570612366000000,
  price: 40.29,
  sequence_number: 109974,
  sip_timestamp: 1674570612388618000,
  size: 4,
  tape: 1,
  trf_id: 10,
  trf_timestamp: 1674570612388599000
}
{
  conditions: [ 37 ],
  correction: 8,
  exchange: 4,
  id: '71675273364296',
  participant_timestamp: 1674570606211000000,
  price: 40.29,
  sequence_number: 511129,
  sip_timestamp: 1674570609801590500,
  size: 10,
  tape: 1,
  trf_id: 12,
  trf_timestamp: 1674570609801239000
}

**Comment by NeilJustice** [comment]
Interesting findings, thanks for investigating!
