### ISSUE TITLE
Duplicate symbols when subscribing to AM.* in wss://socket.polygon.io/stocks

### ISSUE THREAD

**Issue by slecrenski** [polygon-io/issues#27]
**Client**
Which WebScoket client are using?
ws
wss://socket.polygon.io/stocks

**Issue**
Response data is duplicated for what appears to be no good reason.  This occurs when I subscribe to all stock tickers via the subscribe action "AM.*"  I have also tried explicitly setting comma delimited symbols using the results of v2/snapshot/locale/us/markets/stocks/tickers

**Expected Result**
Only one unique symbol should be returned for each company and not some odd smattering of duplicate symbol data.  In this screenshot the same symbol is repeated several times with what appears to be exactly the same data.  Is this like duplicate data based on market or something?  If so it still doesn't make sense because the market is not included in the aggregate results..

**Screenshots**
![Screenshot from 2020-05-28 16-00-23](https://user-images.githubusercontent.com/1291050/83187611-6d0d1c80-a0fc-11ea-816b-46a807f8ddfb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] Fedora 32
 - Browser [e.g. chrome, safari] NodeJS
 - Version [e.g. 22] v12.16.3

**Additional context**
I do not receive duplicates when subscribing to single stocks or a couple stocks.

**Comment by qrpike** [comment]
I dont see this happening in production. Can you double check your code?

We send messages as an array. You could possibly just be reading the first message in the array?

**Comment by slecrenski** [comment]
Yes I guess I improperly followed some code example online.  I rewrote the code and it works just fine now.
