### ISSUE TITLE
Inaccurate vwap price on 1 minute chart

### ISSUE THREAD

**Issue by Gabsys** [polygon-io/issues#275]
**URL**
https://api.polygon.io/v2/aggs/ticker/GLMD/range/1/minute/1689253200000/1689253200000?adjusted=false&sort=asc&limit=120&apiKey=<API_KEY>

**Result**
`"vw": 2.9383,`

**Expected Result**
`"vw": 3.53,`

**Screenshots**
Result from API:
![image](https://github.com/polygon-io/issues/assets/23636171/25879125-2909-45f0-990a-a64db728cef0)

VWAP from TradingView
![image](https://github.com/polygon-io/issues/assets/23636171/e1ad1026-8ef1-4928-8e05-4ae0a65b9076)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: ??

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out.  We get our data from all 19 US exchanges but most other providers only use a handful of the exchanges. We also do not filter out dark pool trades.  This often causes a difference in our OHLCV values. 
Our VWAP is calculated by totaling the dollars traded for every transaction (price multiplied by the volume) and then dividing by the total shares traded. This looks correct to me

**Comment by Gabsys** [comment]
I see, ok then. Thanks forthe clarification

**Comment by AHangstefer** [comment]
Anytime! Let me know if there's anything else I can do for you
