### ISSUE TITLE
Missing ticker I:RUT, Russell 2000 Index

### ISSUE THREAD

**Issue by miguelprovencio** [polygon-io/issues#278]
**URL**
https://api.polygon.io/v3/reference/tickers?ticker=I:RUT&active=true

**Result**
{
    "results": [],
    "status": "OK",
    "request_id": "a2ce3ba407220f5cd87531722ca50c78"
}

**Expected Result**
I should get ticker info for the the Russell 2000 Index.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 119

**Additional context**
Also can't get any aggregate data for I:RUT.

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. We don't currently support Russell 2000. You can see the Indices we support using our[ Tickers endpoint](https://polygon.io/docs/stocks/get_v3_reference_tickers), just use the market parameter with "indices" selected.
