### ISSUE TITLE
Currency/Forex ticker day aggregate is not returning any results/not working

### ISSUE THREAD

**Issue by apasumarthi1999** [polygon-io/issues#28]
**URL**
https://api.polygon.io/v2/aggs/ticker/C%3AGBPUSD/range/1/day/2020-01-01/2020-01-10?sort=asc&apiKey=<Your API Key>

**Result**
{
  "ticker": "C:GBPUSD",
  "status": "OK",
  "queryCount": 0,
  "resultsCount": 0,
  "adjusted": true,
  "results": null,
  "request_id": "ec928eb81b212654b60e2df098dc47da"
}

**Expected Result**
List of daily candles for the given currency/forex ticker

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by apasumarthi1999** [comment]
Hi,

Any update on when this will be fixed?

Aditya.

**Comment by jrbell19** [comment]
Hi Aditya, 

Sorry for the inconvenience. We'll go in and repopulate these bars to make them available again as soon as possible. I'll keep you posted on progress.

**Comment by tankorsmash** [comment]
I'm also having issues downloading aggregate bars for Forex, has there been any movement on this? Seems like I can't get any fx data.

**Comment by BeauAgst** [comment]
Also having the same issue. It looks like data is returned (almost) correctly if the timespan is daily. However, if I change to any other timespan, the response alternates between an empty array and null.

Please can we get an update on this? As this is a paid service, I'm quite shocked at the inconcistency.

**Comment by jrbell19** [comment]
Hi! So sorry for the delay on this issue. 

The tick and aggregated data for forex is available again back to 2009. 

Really appreciate your patience with us on this. Let me know if you see anything out of the ordinary.
