### ISSUE TITLE
Financials API - Support for current shares and multiple share classes (+ EPS)

### ISSUE THREAD

**Issue by rookbreezy** [polygon-io/issues#282]
# Value add
Getting the shares outstanding right is super important as it's the basis of all per share calculations It's then used in valuation metrics like the Price to Sales and Price to Cash Flows. The current shares are used in calculating the current market cap although [Polygon prefers to use the weighted average](https://polygon.io/knowledge-base/article/what-is-market-cap-and-how-does-polygon-calculate-that-value). 

**Describe the solution you'd like**
- API item for current shares per quarter
- API items for the weighted average shares for each class, basic and diluted.
- EPS for companies with multiple share classes (Visa - NYSE:V)

Let's look at Visa as an example, the current shares are found on the first page:
https://www.sec.gov/ix?doc=/Archives/edgar/data/1403161/000140316119000050/v093019form10k.htm#

# XBRL - Current

I don't have much experience dealing with XBRL data so maybe someone at Polygon can chip in with how challenging it is to extract this data.

Tag for Class A: dei:EntityCommonStockSharesOutstanding + us-gaap:CommonClassAMember
And 2 more classes

<img width="579" alt="current" src="https://github.com/polygon-io/issues/assets/59795195/1db4d6d0-9a62-4057-8c43-20801689dc30">

# XBRL - Weighted Average and EPS

Tag for Basic Class A EPS: us-gaap:EarningsPerShareBasic + us-gaap:CommonClassAMember
Tag for Basic Class A Shares: us-gaap:WeightedAverageNumberOfSharesOutstandingBasic + us-gaap:CommonClassAMember

And 2 more classes + diluted

<img width="914" alt="weighted" src="https://github.com/polygon-io/issues/assets/59795195/0f8ce82c-43c7-4674-be11-40f3b599d182">

# Alternative ways

## #1
Theoretically you can find the shares by using only the EPS and Net Income numbers like so:

Net Income / Basic EPS = Basic Weighted Average Shares

But since the Net Income and EPS are rounded it won't be accurate. Not to mention that some companies like Visa allocate a portion of Net Income to each share class, even allocating some to preferred stock. (See page 96 of the sec.gov Visa report linked above). 

## #2

Perhaps Polygon could do the weighted average share calculations themselves. Would still need to get the current shares.

# More Examples

## Berkshire Hathaway
[BRK recent 10-Q](https://www.sec.gov/ix?doc=/Archives/edgar/data/1067983/000095017023058993/brka-20230930.htm) (Page 1)
<img width="715" alt="brk" src="https://github.com/polygon-io/issues/assets/59795195/8db197c4-940c-49ee-aa17-2da6af8c80ff">

## Village Super Market (Small Cap)
[VLGEA recent 10-Q](https://www.sec.gov/ix?doc=/Archives/edgar/data/103595/000010359523000016/vlgea-20231028.htm)

Some companies like Visa or Village here allocate Net Income and sometimes convert shares in that calculation. I am not sure how common this is or how much it complicates things.  (Page 9)

<img width="943" alt="village" src="https://github.com/polygon-io/issues/assets/59795195/2cc7428c-1f59-4f31-896b-3e24403aa2f9">

# Related Issues

Apple has -48,266,000 shares outstanding
https://github.com/polygon-io/issues/issues/279

**Comment by AHangstefer** [comment]
HI! Thanks for reaching out! We've got an open ticket for this issue. Hopefully it will be resolved soon. Let me know if there's anything else I can do for you.

**Comment by rookbreezy** [comment]
@AHangstefer Don't close the issue before it's completed. An open issue shows that it is being worked on. Useful if someone else encounters this before it's fixed.
