### ISSUE TITLE
Historical Option Open Interest / As-of

### ISSUE THREAD

**Issue by kenaschmidt** [polygon-io/issues#283]
**Is your feature request related to a problem? Please describe.**
Would like to be able to get snapshot information for option open interest on specific days

**Describe the solution you'd like**
Add a field to 'Options Contract[s]' /v3/reference/options/contracts/ endpoint which returns Open Interest on the 'as_of' date (defaults to today)

**Describe alternatives you've considered**
Running a script every day to store the values in a local database.  Doesn't provide any back testing capabilities and is subject to error.

**Additional context**
N/A

**Comment by AHangstefer** [comment]
HI! Adding historic open interest is on our roadmap. You can also submit ideas through our [roadmap](https://polygon.io/product-roadmap)! Users can vote on what's most important to them and we use that data to help us decide what features to work on next.
