### ISSUE TITLE
Indicator data along with OHLC data for the Aggregates endpoint.

### ISSUE THREAD

**Issue by imzeeshan** [polygon-io/issues#285]
**Is your feature request related to a problem? Please describe.**
The Stock Aggregates endpoint returns the OHLC for the timeframe requested and works great, Polygon introduced the Indicator endpoints that work on any timeframe. It would be great if the Indicators are also sent through the Stock Aggregates endpoint.

**Describe the solution you'd like**
A new API that includes the OHLC + Indicators data, for the timeframe requested for. 

**Describe alternatives you've considered**
Hitting 2 separate API's to fetch and match the timeframe.

**Additional context**

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out! That's a great idea. You can submit ideas through our [roadmap](https://polygon.io/product-roadmap)! Users can vote on what's most important to them and we use that data to help us decide what features to work on next.
