### ISSUE TITLE
Feature Request - Allow the Snapshot API to select multiple tickers

### ISSUE THREAD

**Issue by ScottNg49** [polygon-io/issues#29]
**Is your feature request related to a problem? Please describe.**
There is too much overhead when pulling Snapshot - All Tickers or multiple REST calls for single tickers. 

**Describe the solution you'd like**
Create a new feature, under the Snapshot API, to pull data from multiple tickers in one REST call. /v2/snapshot/locale/us/markets/stocks/tickers/{ticker}

https://polygon.io/docs/#get_v2_snapshot_locale_us_markets_stocks_tickers__ticker__anchor

**Describe alternatives you've considered**
The best workaround atm, it to pull Snapshot - All Tickers, and process the data there. However, this generates unnecessary overhead such as increased processing time for both server and client. 

Pulling multiple tickers with Snapshot - Single Ticker requires either async or multithreading, 

**Additional context**
Reduce resource usage for both server and client (ex: latency (ms)). RTT (latency) is one of the biggest bottlenecks in algotrading.

**Comment by qrpike** [comment]
Hi Scott, 

This feature is now available. You can pass in `tickers` query string param as a comma separated list of tickers to filter on. Eg:
`https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers?tickers=AAPL,MSFT,NVDA,AMD`

We will update the documentation soon to reflect this. 

Thanks,
