### ISSUE TITLE
persisent Time-Out messages this morning

### ISSUE THREAD

**Issue by struxomath** [polygon-io/issues#290]
Good morning. I'm getting persisent Time-Out messages this morning. Am I the only one ?

**URL**
[The RESTful API call you are making (please be sure to omit your API key)] 
 https://api.polygon.io/v2/aggs/ticker/I:NDX/range/60/minute/1702650600000/1705611599999?limit=50000&apiKey=

**Result**
What result are getting?
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.19.2</center>
</body>
</html>

**Expected Result**
The normal response json

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome, safari] Chrome

**Comment by RenaatTruijen** [comment]
Hi, it's solved now, thank you !
