### ISSUE TITLE
OPRA flat files - missing sale conditions pre 2019.11.04

### ISSUE THREAD

**Issue by mpolatov** [polygon-io/issues#292]
One example:
2015-01-05
ticker,conditions,correction,exchange,price,sip_timestamp,size
O:A150220C00042500,,0,302,1.68,1420473268715000000,1

In reality, that trade was done with trade condition R (SPIM).

So looks like you are missing *all* OPRA conditions BEFORE they were changed back in Nov 4 2019.

Attached the old OPRA spec with old trade conditions and indications how they would change effective Nov 4th 2019.

[OPRA_Pillar_Output_Specification - 2019.pdf](https://github.com/polygon-io/issues/files/14897595/OPRA_Pillar_Output_Specification.-.2019.pdf)

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. I'm looking into this for you
