### ISSUE TITLE
Crypto flat files - invalid exchange

### ISSUE THREAD

**Issue by mpolatov** [polygon-io/issues#294]
2020-05-21
X:BTC-USD,2,10,850623306,1590019202938000000,9511.95,0.01195

Lot of trades with the exchange 10 (NYSE) between 2017.01.01 and 2021.06.02

**Comment by AHangstefer** [comment]
Hi! I've created a ticket for this issue and it should be corrected soon

**Comment by AHangstefer** [comment]
Hello again! It looks like we used to support another crypto exchange and "10" was it's identifier so this is as expected. Let me know if there's anything else I can do for you!

**Comment by mpolatov** [comment]
Well - since there is no way for me to query exchange mapping as-of (2020-05-21), how one expect to map those trades to the proper exchange?
Also you should not be re-using identifiers.
