### ISSUE TITLE
Some tickers are missing CIK

### ISSUE THREAD

**Issue by mpolatov** [polygon-io/issues#297]
**URL**
[The RESTful API call you are making (please be sure to omit your API key)](https://api.polygon.io/v3/reference/tickers?ticker=PDYN&active=true&apiKey=___

**Result**
 "results": [
        {
            "ticker": "PDYN",
            "name": "Palladyne AI Corp. Common Stock",
            "market": "stocks",
            "locale": "us",
            "primary_exchange": "XNAS",
            "type": "CS",
            "active": true,
            "currency_name": "usd",
            "composite_figi": "BBG00YMWMLR0",
            "share_class_figi": "BBG00YMWMLS9",
            "last_updated_utc": "2024-04-10T00:00:00Z"
        }
    ],
    "status": "OK",
    "request_id": "8e454af48052e4565499d27ed77a7a24",
    "count": 1

**Expected Result**
CIK=1826681

as per

https://www.sec.gov/edgar/browse/?CIK=1826681&owner=exclude

There are more examples like that.

**Comment by AHangstefer** [comment]
Hello again! We have a ticket open for this issue and our engineering team is working on it.
