### ISSUE TITLE
Forex Market Trade API Missing

### ISSUE THREAD

**Issue by swapnil5775** [polygon-io/issues#298]
**URL**
Trade API for Forex market doesnt exists but in subscription "Trades & Quotes" included as seperate bullet point for premium Personal Plan For Forex. 

**Result**
No results as Trade API is missing, it is only having Quotes. 

**Expected Result**
All confirmed executed trades for FX market 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. We support Quotes for Forex and Trades for Crypto. Forex and Crypto are bundled under the Currencies plan.
