### ISSUE TITLE
UVXY Reverse Splits not Implemented

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#30]
UVXY reverse splits have not been implemented in the adjusted data

**Comment by jrbell19** [comment]
Looks like we were missing the 1 for 5 split from 07/25/2016. Went ahead and added that to the database. Let me know if you see any others that need to be added.

**Comment by ryantjo** [comment]
Did you check the first price in the series vs the last price.  2011 price is 242695146 in 2020 it is 43. Have to be a lot of splits still not accounted for

**Comment by jrbell19** [comment]
We actually do account for every split that has occurred with this symbol. If you check YF, the adjusted close price is also over $200mil ( https://finance.yahoo.com/quote/UVXY/history?period1=1317686400&period2=1317859200&interval=1d&filter=history&frequency=1d ) 

UVXY Splits - https://www.splithistory.com/uvxy/
Polygon UVXY Splits - https://api.polygon.io/v2/reference/splits/UVXY?apiKey=
