### ISSUE TITLE
requesting CSV should be done via parameter, not HTTP header.

### ISSUE THREAD

**Issue by dbregman** [polygon-io/issues#300]
**Is your feature request related to a problem? Please describe.**
Polygon recently introduced CSV output from the REST APIs by setting a HTTP header, accept:text/csv.
CSV is great, but unfortunately setting a HTTP header is terrible UX.
When doing a basic request in my browser (URL bar) there's simply no way to set headers. This is a frequent use case for me personally and I can't use CSV here at all.
Even when coding up the requests in a programming language, setting headers can be quite a few extra steps that require digging into documentation of the particular HTTP library. Multiply this by the number of languages / http libs you use polygon from.

**Describe the solution you'd like**
Just have a parameter like &format=csv

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. That's a great idea. You can submit ideas through our [roadmap](https://polygon.io/product-roadmap)! Users can vote on what's most important to them and we use that data to help us decide what features to work on next.
