### ISSUE TITLE
asian user can't access the websocket api

### ISSUE THREAD

**Issue by scs001** [polygon-io/issues#304]
**Client**
i am a aisan user, when i connect the websocket in india, i got a wrong informartion. please complex it as soon as possible

**Issue**
i am a aisan user, when i connect the websocket in india, i got a wrong informartion. please complex it as soon as possible. we change many ip, but doesn't useful

**Expected Result**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Additional context**

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. It looks like we had an issue on this particular day. Are you able to connect to websockets now?
