### ISSUE TITLE
Stray quotation mark in Trades documentation: 'The trade conditions. See Conditions and Indicators" for Polygon.io's trade conditions glossary.'

### ISSUE THREAD

**Issue by NeilJustice** [polygon-io/issues#305]
On the documentation page https://polygon.io/docs/stocks/ws_stocks_t, in the Trades section, in the definition for response attribute 'c', there appears a stray quotation mark character. Not the world's most pressing issue but an issue nonetheless.

`The trade conditions. See [Conditions and Indicators"](https://polygon.io/glossary/us/stocks/conditions-indicators) for Polygon.io's trade conditions glossary.`

![image](https://github.com/user-attachments/assets/87d7fca2-28ab-488a-8719-0e346c545eb8)

**Comment by AHangstefer** [comment]
Thank you for bringing this to our attention. We have a ticket open to fix it. Let me know if there's anything else I can do for you

**Comment by NeilJustice** [comment]
Thank you but it does appear that the stray quotation mark character is still present at https://polygon.io/docs/stocks/ws_stocks_t.
