### ISSUE TITLE
Missing definitions for trade correction codes on the stock trades flat files page

### ISSUE THREAD

**Issue by NeilJustice** [polygon-io/issues#306]
On the stock trades flat files page at https://polygon.io/flat-files/stocks-trades?stocks-trades=documentation, definitions for trade correction codes appear to be missing. From looking at the stock trade tick data, I see there are correction codes 1, 8, 10, 12 - four values with currently unknown definitions from this user's point of view.

![image](https://github.com/user-attachments/assets/a6ae169b-82cf-4be7-8a44-0b4c2f3cd028)

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. You can see trade correction indicator ids and definitions here:
https://polygon.io/glossary/conditions-indicators
