### ISSUE TITLE
Missing after-hours trading data of half-day market closure 

### ISSUE THREAD

**Issue by SPengLiang** [polygon-io/issues#309]
**URL**
[The RESTful API call you are making (please be sure to omit your API key)
](https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2024-07-03/2024-07-03?adjusted=true&sort=asc&limit=500000&apiKey=)

**Result**
Missing data from 1:00pm to 4:00pm

**Expected Result**
return missing data

**Screenshots**
<img width="708" alt="image" src="https://github.com/user-attachments/assets/b94d4762-3162-4791-a3a5-7ec6f0a2ce15">
**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Comment by AHangstefer** [comment]
Thanks for reaching out! I'm looking into this

**Comment by AHangstefer** [comment]
It looks like this has been corrected. I am seeing minutes between 13:00 and 16:00 now:

https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2024-07-03/2024-07-03?apiKey=**&adjusted=true&sort=asc&limit=50000
