### ISSUE TITLE
Historical quotes have wrong timestamp on certain days

### ISSUE THREAD

**Issue by spazmodius** [polygon-io/issues#31]
Historical NBBO quotes for QQQ, **on 2012-12-14**, are timestamped 5 hours off.  If I ask for the quotes starting at 9:30 EST (14:30 UTC), I actually get quotes that happened at 14:30 EST.

**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/QQQ/2012-12-14?timestamp=1355495400000000000&limit=10

**Result**
Receive quotes that actually happened 5 hours after their timestamps.

**Expected Result**
Receive quotes that are correctly timestamped, and occurred during the time requested.

**Comment by spazmodius** [comment]
Looks like quotes for QQQ **on 2013-10-24** are similarly off, by 4 hours.

https://api.polygon.io/v2/ticks/stocks/nbbo/QQQ/2013-10-24?timestamp=1382621400000000000&limit=50

**Comment by spazmodius** [comment]
On **2013-11-29**, off by 5 hours.

https://api.polygon.io/v2/ticks/stocks/nbbo/QQQ/2013-11-29?timestamp=1385735400000000000&limit=50

**Comment by spazmodius** [comment]
**2014-06-02** off by 4 hours

**Comment by qrpike** [comment]
Are you using UTC timestamps?

The request you sent has an offset of:
`1382621400000000000` which is `Thu Oct 24 2013 09:30:00 GMT-0400 (Eastern Daylight Time)`

The first result in the response has a timestamp of:
`1382621402335000000` which is `Thu Oct 24 2013 09:30:02 GMT-0400 (Eastern Daylight Time)`

**Comment by spazmodius** [comment]
No, it's not that.  Those four days are the only exceptional timestamps in all the market days since 2011-02-23.

Yes, the response has timestamps that match my request.  But the quote that is timestamped `Oct 24 2013 9:30:02 EDT` _actually happened_ at `Oct 24 2013 13:30:02 EDT`

**Comment by qrpike** [comment]
Hmm. What makes you think the quote happened at a different time than what's on the quote?

**Comment by spazmodius** [comment]
Primarily, by comparison with another source of the same data. Polygon's data for QQQ on those specific days is vastly different from ActiveTick's. Offsetting the data by 4 or 5 hours makes it to line up penny-for-penny.

How can I tell which of Polyogon or ActiveTick is wrong? By checking a historical intra-day chart (say, on barchart.com), and seeing what times the high and low occurred.

Finally, it is confirmed by looking at the time-range of quote activity on those days. Polygon has it beginning and ending several hours before extended market hours begin and end.

**Comment by qrpike** [comment]
I think the best way to gauge the correctness would be to make sure the sequence numbers are in order. If the sequence number is in order then I believe it is correct.

**Comment by spazmodius** [comment]
I haven't been clear. I didn't mean that _one_ quote was out of sequence. I mean _the whole day's data_ is timestamped 4 or 5 hours wrong. 

Graph the day's data, and it is visually obvious.

**Comment by qrpike** [comment]
I understand what you're saying, but the sequence numbers state the order which I believe to be correct.

**Comment by qrpike** [comment]
Interesting. I will look into this further. Thank you for the chart, that helps.

**Comment by pps83** [comment]
@qrpike any updates on the issue? Can you please also check your entire historical DB that the timestamps have proper ranges if QQQ data had the issue (4am - 8pm NY time)?

It seems that QQQ for 2013-10-24 does return proper timestamps now.
https://api.polygon.io/v2/ticks/stocks/trades/QQQ/2013-10-24?limit=2&apiKey=zzz:

```
[{"t":1382601902690000000,"q":902,"i":"","x":12,"s":300,"c":[12],"p":82.22,"z":3},
{"t":1382601902690000000,"q":903,"i":"","x":12,"s":300,"c":[12],"p":82.22,"z":3}]
```

stamps are:
`Thursday October 24, 2013 04:05:03 (am)`

**Comment by qrpike** [comment]
We regenerated those couple days of data. We generate daily files at a time, so all tickers on those days should be fixed. 

Have you seen any other issues since?
