### ISSUE TITLE
Unexpected error message when daily data is requested for a valid format date that does not exist such as 2024-07-32

### ISSUE THREAD

**Issue by NeilJustice** [polygon-io/issues#312]
An unexpected error message is returned when the user requests daily data for a valid format date that does not exist such as 2024-07-32.

Request:
`https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2024-07-32/2024-07-32?apiKey=ApiKey`

Response:
`{"status":"ERROR","request_id":"4b382ea29fa0494d312e1c8ecee9038d","error":"Could not parse the time parameter: 'from'. Use YYYY-MM-DD or Unix MS Timestamps"}`

Possible improved response:
`{"status":"ERROR","request_id":"4b382ea29fa0494d312e1c8ecee9038d","error":"Invalid date for parameter 'from': 2024-07-32"}`

**Comment by AHangstefer** [comment]
Thank you! I'll let our team know about this suggestions. You can submit this ideas through our [roadmap](https://polygon.io/product-roadmap) as well! Let me know if there's anything else I can do for you.
