### ISSUE TITLE
Unexpected error message when future daily data that does not exist yet is requested

### ISSUE THREAD

**Issue by NeilJustice** [polygon-io/issues#313]
The user is shown an unexpected error message in response to submitting a request for future daily data that does not exist yet.

Request submitted with a Stocks Developer API key:
`https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2024-12-31/2024-12-31?apiKey=ApiKey`

Response:
`{"status":"NOT_AUTHORIZED","request_id":"dd68e9ff6c00458b806e1947d8bbe2ff","message":"Your plan doesn't include this data timeframe. Please upgrade your plan at https://polygon.io/pricing"}`

Possible improved response:
`{"status":"ERROR","request_id":"dd68e9ff6c00458b806e1947d8bbe2ff","error":"Invalid future date for parameter 'from': 2024-12-31"}`

**Comment by AHangstefer** [comment]
Thank you! That's a great idea. You can submit ideas through our [roadmap](https://polygon.io/product-roadmap)! Users can vote on what's most important to them and we use that data to help us decide what features to work on next.
Let me know if there's anything else I can do for you.
