### ISSUE TITLE
Ticker Details v3 | Market Cap inaccurate for past data

### ISSUE THREAD

**Issue by jpedrofs** [polygon-io/issues#316]
**URL**
[Ticker Details v3](https://polygon.io/docs/stocks/get_v3_reference_tickers__ticker)

**Current Behavior**
Market cap in the API currently **does not** represent the market cap at a given point in time for past dates. When you transform based on past stock splits, the number seems reasonable, however you should not require developers to calculate this. It should be default behavior of the API.

**Expected Behavior**
Market cap for past data should represent the market cap at that point in time, as it's independent from stock splits. When a stock splits, the share price and the number of shares outstanding adjust proportionally, leaving the market cap unchanged.

**Examples**

Market cap for Apple was larger in 2010 than it is today according to the API:

request: https://api.polygon.io/v3/reference/tickers/AAPL?date=2024-09-27
market cap in response: "market_cap": 3,463,350,367,230

request: https://api.polygon.io/v3/reference/tickers/AAPL?date=2010-09-27
market cap in response: "market_cap": 4,776,952,176,108

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. We have a ticket open for this issue. Let me know if there's anything else I can help you with.

**Comment by jpedrofs** [comment]
Awesome, thanks for the quick follow up
