### ISSUE TITLE
Option Price data is missing for some days

### ISSUE THREAD

**Issue by MohaMaya** [polygon-io/issues#318]
**URL**
/v2/aggs/ticker/{optionsTicker}/range/{multiplier}/{timespan}/{from}/{to}

**Result**
For the dates August 2nd and 5th 2024, price data are only partial

There could be many more days

**Comment by AHangstefer** [comment]
Hi! Are you able to share a particular query with specific parameters that you feel should return bars? I'm happy to look into this for you.
