### ISSUE TITLE
Missing NBBO data on one day

### ISSUE THREAD

**Issue by spazmodius** [polygon-io/issues#32]
There are no quotes for QQQ on 2014-06-10.

**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/QQQ/2014-06-10?timestamp=1402407000000000000

**Result**
404
`{"error":"Unknown database error ( Error Code: 001 )","errorcode":"001","status":"ERROR","success":false}`

**Expected Result**
Receive the quotes for QQQ on 2014-06-10

**Additional context**
This is _not the same issue_ as https://github.com/polygon-io/issues/issues/23, which is for closed-market days. This one is for an open-market day. [QQQ did trade](https://api.polygon.io/v2/ticks/stocks/trades/QQQ/2014-06-10?timestamp=1402407000000000000).

**Comment by MBPersonal** [comment]
There is a similar issue affecting the whole equities universe on 2020-06-10 and 2020-06-11

**Comment by qrpike** [comment]
This should be fixed now.

**Comment by KshitizSharmaV** [comment]
Hi, 

NBBO quotes data is failing for 15th June. Why does it keep failing for different dates? I have reported this issue a number of times. Is there logical reasoning behind it?

https://api.polygon.io/v2/ticks/stocks/nbbo/AAPL/2020-06-15?limit=10

Tx
