### ISSUE TITLE
Feature Request: Provide OpenAPI Specification for Polygon.io REST APIs

### ISSUE THREAD

**Issue by NipunaRanasinghe** [polygon-io/issues#320]
**Is your feature request related to a problem? Please describe.**
Hi Team, 

I would like to request the provision of OpenAPI specifications for the REST APIs offered by Polygon.io. Having an OpenAPI spec is essential for the following reasons:

- Enhanced Developer Experience: OpenAPI specs serve as a standardized way for developers to interact with the API. They provide an easy-to-understand and machine-readable documentation, reducing the effort required to integrate the APIs into various projects.

- Automated Code Generation: OpenAPI allows developers to generate client SDKs automatically in various programming languages, improving productivity and reducing manual effort for writing repetitive code.

- Better Tooling Support: With an OpenAPI specification, various tools can be leveraged for API testing, documentation, and monitoring, helping developers build robust applications on top of Polygon.io.

- Consistency and Accuracy: OpenAPI helps maintain accurate and up-to-date API documentation, preventing mismatches between the actual API and the documentation, and ensuring consistency across different platforms.

- Community Contributions: An OpenAPI spec will foster contributions from the developer community by enabling them to easily experiment, test, and provide feedback.

Given these benefits, I believe it will significantly improve the usability of Polygon.io's REST APIs for developers and third-party integrations.

Thank you for considering this request. Looking forward to your feedback!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NipunaRanasinghe** [comment]
As a lead developer from the [Ballerina programming language](https://ballerina.io/) team, I would like to highlight that we are open to adding new Ballerina connector support for Polygon APIs, provided that official OpenAPI specifications become available for Polygon. These connectors will be generated using the Ballerina OpenAPI tool, streamlining API integration for Ballerina developers.

This will further expand the Polygon.io ecosystem and offer seamless integration with Ballerina developers.

**Comment by AHangstefer** [comment]
Hi! Thanks for reaching out. You can submit ideas through our [roadmap](https://polygon.io/product-roadmap)! Users can vote on what's most important to them and we use that data to help us decide what features to work on next. I've gone ahead and submitted your requests through our roadmap. Let me know if there's anything else I can do for you!
