### ISSUE TITLE
Duplicate incorrect stock splits

### ISSUE THREAD

**Issue by projects2080** [polygon-io/issues#324]
See #311 

Guys... You are a data provider charging $199 per month, with a pro tier, if someone reports that many stocks have duplicate incorrect splits, YOU should check and correct them all, not ask for a list of symbols to fix and do nothing until then. 

Here are some more.

['AINC', 'ALEX', 'COEP', 'CVLY', 'CZFS', 'FTLF', 'LADR', 'LBAI', 'MDRR', 'NYC', 'OUT', 'PGC', 'QBAK', 'SFE', 'SLG', 'STCN', 'VGR']

This means that your adjusted aggs are incorrect for these symbols too.

**Comment by cookie359** [comment]
Here's a list of all of the split issues I've found.

How can you not have some kind of primary key on symbol/date for splits in your datasource?! 

[split_errors.txt](https://github.com/user-attachments/files/18092341/split_errors.txt)

**Comment by AHangstefer** [comment]
It looks like these are all cooperate actions or reverse stock splits. I understand that the results you’re seeing are unexpected, and I'm sorry for the confusion that might have caused. The endpoint is functioning correctly and returning accurate data. These are not traditional stock splits but corporate actions - reverse splits or reorganizations. 
The split data reflects adjustments recognized in the market and represent actual stock activity on that date.

Here's an example:

ALEX
On November 28, 2017, for Alexander & Baldwin (ALEX)- These adjustments are related to the reorganization of the company into a REIT, where the number of shares in circulation was increased. The first adjustment was a **1-for-1.42** split, and the second was a **1-for-1.574** split. Such changes can appear similar to splits in stock history records but are typically part of a broader corporate restructuring.
