### ISSUE TITLE
tickers endpoint fails when using next_url

### ISSUE THREAD

**Issue by gsiano** [polygon-io/issues#325]
**URL**
https://api.polygon.io/v3/reference/tickers?cursor=YWN0...

**Result**
AssertionError: bad code 400 {"status":"ERROR","request_id":"5e041cea74a7f8be5d5669d2fdbe5e1a","error":"Failed to parse query parameters from URL: strconv.ParseFloat: parsing \"BCAB\": invalid syntax"}

**Expected Result**
tickers

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by AHangstefer** [comment]
Hello! Thanks for reaching out. This issue should be resolved now. Please let me know if there's anything else I can help you with.
