### ISSUE TITLE
Missing Historical Data

### ISSUE THREAD

**Issue by MBPersonal** [polygon-io/issues#33]
**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/AAPL/2020-06-10?limit=10

**Result**

{
  "error": "Unknown database error ( Error Code: 001 )",
  "errorcode": "001",
  "status": "ERROR",
  "success": false
}

**Expected Result**

This is just one example of data problem affecting the entire equities universe on 2020-06-10 and 2020-06-11 when requesting historical Quotes

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Comment by jrbell19** [comment]
We are aware of this, and will be repopulating this data as soon as possible.

**Comment by qrpike** [comment]
This should be fixed.

**Comment by MBPersonal** [comment]
Thanks guys for a timely fix!
