### ISSUE TITLE
Get Latest News Across all Tickers

### ISSUE THREAD

**Issue by timetraveler328** [polygon-io/issues#34]
**Is your feature request related to a problem? Please describe.**
I'd like a way to get the most recent news articles for all ticker symbols

**Describe the solution you'd like**
An endpoint /v1/meta/news that gets the most recent articles across all tickers, without having to specify a ticker symbol like in the current Ticker News endpoint

**Comment by edzme** [comment]
2nd this. Maybe specify a minimum timestamp and return all the news after that, paginated like now.

**Comment by joshlang** [comment]
3rd this.

And even better would be a websocket subscription for news, so we don't have to consume polygon resources with a poll every minute/second/nanosecond :D

**Comment by jrbell19** [comment]
Ticker News: https://polygon.io/docs/stocks/get_v2_reference_news
