### ISSUE TITLE
Way to get 52 Week High, 52 Week Low, and Average Volume for Ticker

### ISSUE THREAD

**Issue by timetraveler328** [polygon-io/issues#35]
**Describe the solution you'd like**
It would be nice to have an endpoint to get 52w high, 52w low, and average volume for a ticker.

**Describe alternatives you've considered**
I looked at using various aggregates for that stock, but it doesn't seem to provide the expected result

**Comment by jrbell19** [comment]
This is actually a feature that is available now that we have improved our Aggregate's time snapping functionality. You can read more about that in this article: https://polygon.io/blog/aggs-api-updates/
