### ISSUE TITLE
Urls should not be case sensitive for endpoints

### ISSUE THREAD

**Issue by teambailey** [polygon-io/issues#36]
**URL**
Works: https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers/AAPL
Does not work: https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers/aapl

**Result**
Return object: { status: "Not Found"}

**Expected Result**
Return the populated object for this endpoint

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 83

**Additional context**
There might be other endpoints that have this same issue. Please make sure that all public urls are not case sensitive.

**Comment by qrpike** [comment]
We must make ticker symbols case sensitive because there are situations where this impacts what symbol is actually is. 

Eg: `AMpB` is ticker: `AM` preferred class B. Which is very different than `AMPB`, which is just a class A `AMPB` ticker.

**Comment by teambailey** [comment]
Gotcha. We'll make adjustments on the frontend to handle that fact.
