### ISSUE TITLE
Forex Historical Ticks API returning wrong timestamp after 2020-06-15

### ISSUE THREAD

**Issue by mg1262** [polygon-io/issues#37]
**URL**
https://api.polygon.io/v1/historic/forex/AUD/USD/2020-06-15?limit=100&apiKey

**Result**
Starting on 6/15/2020, the timestamp being return for each tick is not accurate and is the same value for each tick
{
  "day": "2020-06-15",
  "map": {
    "a": "ask",
    "b": "bid",
    "t": "timestamp"
  },
  "msLatency": 8,
  "pair": "AUD/USD",
  "status": "success",
  "ticks": [
    {
      "b": 0.68511,
      "a": 0.68518,
      "x": 48,
      "t": **5815518660978**
    },
    {
      "b": 0.68518,
      "a": 0.68525,
      "x": 48,
      "t": **5815519660978**
    },

**Expected Result**
Each tick should include the accurate timestamp.

**Screenshots**
![image](https://user-images.githubusercontent.com/12704253/85025318-dcdf5780-b13c-11ea-8de2-dd4b7361912a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version 83.0.4103.97

**Comment by jrbell19** [comment]
We're looking into what may have occurred this. Sorry for the inconvenience

**Comment by MBPersonal** [comment]
Any update on this issue?  Still has not been fixed

**Comment by MBPersonal** [comment]
The same issue is affecting Crypto historical trades starting on 2020-06-15
