### ISSUE TITLE
Aggs endpoint queryCount != resultsCount

### ISSUE THREAD

**Issue by clickingbuttons** [polygon-io/issues#4]
**URL**
https://api.polygon.io/v2/aggs/ticker/GEO/range/1/day/2004-01-01/2020-02-02
https://api.polygon.io/v2/aggs/ticker/GEO/range/1/day/2004-01-01/2020-02-03

**Result**
https://api.polygon.io/v2/aggs/ticker/GEO/range/1/day/2004-01-01/2020-02-02 gives:
```json
{"ticker":"GEO","status":"OK","queryCount":3403,"resultsCount":3403,"adjusted":true,"results":[...]}
```
but extending the range one day to https://api.polygon.io/v2/aggs/ticker/GEO/range/1/day/2004-01-01/2020-02-03 (a Monday) gives:
```json
{"ticker":"GEO","status":"OK","queryCount":3404,"resultsCount":3403,"adjusted":true,"results":[...]}
```

**Expected Result**
I expect the query count to always equal the results count, and for https://api.polygon.io/v2/aggs/ticker/GEO/range/1/day/2004-01-01/2020-02-03 to return data for 2020-02-03 (a Monday). Can we at least get some documentation as to ~what `queryCount` is and~ what we can do to form better queries?

Edit: I see now that queryCount is "Number of aggregate ( min or day ) used to generate the response," and after your response to #1 I assume it's the number of results returned from the query to Cassandra before being passed to the aggregation service. So I think this is a problem with the aggregation service not adding that Monday to the result when it should.

**Comment by EmilKaczmarski** [comment]
Hi, @jbonzo , @jrbell19  do you know whether issue has ben solved? Because i see that i have similar issue as @clickingbuttons  :)
