### ISSUE TITLE
Multiple issues with Ticks api

### ISSUE THREAD

**Issue by pps83** [polygon-io/issues#42]
**URL**
https://api.polygon.io/v2/ticks/stocks/trades/AAPL/2020-06-02?apiKey=...

I tried to use [tick polygon io api](https://polygon.io/docs/#get_v2_ticks_stocks_trades__ticker___date__anchor), and I'll summarize multiple issues that I encountered.

1.
![image](https://user-images.githubusercontent.com/1614246/85973372-5ce6a680-b9f4-11ea-8bb7-6389e79d7171.png)

Really, SIP timestamp is optional?! How could this even be so and when it might be omitted? **Please explain that clearly.**
I do see that TRF stamp is often omitted, but my code only uses SIP stamp, which according to the docs might also be missing?
The other point with timestamps starting from 1970: wouldn't that be easier to specify stamps relative to a day (in NY timezone) 
Generally, market opens at 9:30 but the code to figure out if a trade with some timestamp happened pre-market or during regular market hours is surprisingly non-trivial and often cannot be even done in some languages correctly. In C/C++ you pretty much cannot do that properly without writing TONS of complex code! To convert a timestamp to local time, [localtime](https://en.cppreference.com/w/cpp/chrono/c/localtime) could be used. But, it won't work unless timezone of the PC that runs the code is set to NY! And even if you force your local time zone settings to use NY it still won't work correctly for historical stamps. The reason is that [DST/EST switch rules changed in the past](https://en.wikipedia.org/wiki/Eastern_Time_Zone#Daylight_saving_time) and `localtime` on windows will be returning wrong local NY time for a few weeks for stamps before 2008! Most likely the same problem exists on other systems and/or other languages that most likely use `localtime` under the hood for their own time conversions. I know your API supports up to 10 years of historical ticks and last such EST/DST change happened in 2007, so, polygon.io might be ok for now (unless some other historical timestamp go beyond 2007), yet, you may eventually add more historical data and then your users and most likely your own service won't do proper conversions if it ever needs to calculate bars for regular market time (excluding pre/post market activity).

2. 
![image](https://user-images.githubusercontent.com/1614246/85976009-5a3b7f80-b9fb-11ea-82be-2309d79b50ee.png)

Your timestamp handling overall is complete mess, the API mentions `timestamp` used for pagination... really, what timestamp? The one that's optional?! How could this possibly work with a timestamp that's omitted? **Please, fix this, make it clear what timestamp has to be used out of the three that your API provides.**
Yet another messed up problem with timestamps: let's say I request ticks for a day. I get 50000 results, and then I try to request next "page". The only timestamp that I can possibly put at this point is the one that was in the last tick of the first 50000 results. Then, the next page will contain that last tick once again. So freaking annoying to deal with that mess.

3.
![image](https://user-images.githubusercontent.com/1614246/85973466-9c14f780-b9f4-11ea-9193-4f1f57eea725.png)

These are junk, unless your docs could specify any use for these. And to make things more confusing, why are there both of these that seem to have similar meaning?
**Can you please clearly explain what each of these mean and why we may need both of them?**

4.
![image](https://user-images.githubusercontent.com/1614246/85973585-0b8ae700-b9f5-11ea-8ff2-493903e67a0b.png)

Clearly, your API would be broken if price was an `Integer`. A number? Maybe, but not an integer.
Imagine, somebody actually follows your docs and codes something according to your documentation and then looses tons of money because your docs lied. Easily possible.

-----

On the other hand, I checked and I see that total volume from aggregated bars matches market daily volume as reported by nasdaq.com and/or ToS for example (it's not 100% but the error is withing 1% of the total volume). If one manually calculates volume from 30min bars in ToS, total volume, for example, will surprisingly be way off by 30% or more.

I didn't try to manually aggregate ticks returned by polygon, but I have a question: do you simply aggregate them in bars, or you skip some of the ticks based on condition code? CTA / UTP have different rules/exceptions for aggregate volume to be updated based on conditions. Can't you put simple example code that aggregates ticks for a day in some bars and correctly handles conditions (if any special handling is required)?

**Comment by spazmodius** [comment]
> the code to figure out if a trade with some timestamp happened pre-market or during regular market hours is surprisingly non-trivial 

Wouldn't the trade condition indicate (more accurately) whether a trade was Regular or FormT?

> In C/C++ you pretty much cannot do that properly without writing TONS of complex code!

Fortunately, you're not the first to encounter this problem: https://github.com/google/cctz

**Comment by pps83** [comment]
> > In C/C++ you pretty much cannot do that properly without writing TONS of complex code!
> 
> Fortunately, you're not the first to encounter this problem: https://github.com/google/cctz

Even this lib seem not to be able to do it properly. First of all, it doesn't seem to be trivial, it doesn't work on windows and requires some files to be installed etc. So, not even sure if it at all can do that properly.

Imo polygon should have distributed timestamps that can easily be converted to market time without doing anything special. One obvious solution is to use stamps relative to day's 00:00 or 04:00 time

**Comment by occasionallydavid** [comment]
Just adding 2 cents from a current trial user, I have never once in 30 years seen a situation where storing a denormalized timestamp improved things, except as seen here, superficially. There are at least 2 zones within the US alone relevant to US markets, and at least 3 European zones for markets that run concurrently to the US market. Every single one of these will have their own DST rules.

Luckily a standard database has existed since technical prehistory, the Olsen timezone database, that records globally the current idea of how to translate this huge mess into simple integers on which playschool arithmetic can be performed by adults as easily as children. Even more luckily, this has been standard practice everywhere in the industry for many years

**Comment by pps83** [comment]
> Just adding 2 cents from a current trial user, I have never once in 30 years seen a situation where storing a denormalized timestamp improved things, except as seen here, superficially. There are at least 2 zones within the US alone relevant to US markets, and at least 3 European zones for markets that run concurrently to the US market. Every single one of these will have their own DST rules.
> 
> Luckily a standard database has existed since technical prehistory, the Olsen timezone database, that records globally the current idea of how to translate this huge mess into simple integers on which playschool arithmetic can be performed by adults as easily as children. Even more luckily, this has been standard practice everywhere in the industry for many years

well... the issue still stands: it not trivial to convert timestamps to market times. If you run backtesting code over tick data for many symbols your Olsen tz conversion times will likely dominate over your actual algo (what a surprise). If polygon data had times relative to market time, everything would be trivial. If you had minute data for SPY from polygon and wanted to run a simple test to compare buy at open and sell at close VS buy close and sell open ... suddenly such a simple trivial test becomes non trivial at all: you either spend hours trying to get conversion right (which won't be right most likely), or you try to find some olsen tz db, spend even more time to get it integrated... or, most likely, one will simply use localtime and won't get correct results in some years. Yes... totally superficial. That's how errors propagate and may eventually cost you money.

**Comment by occasionallydavid** [comment]
Time conversion most certainly would dominate runtime if executed on every tick, but it is only necessary to recalculate the offset once per 86400 seconds, ideally at the market open where there is no risk of crossing a DST boundary. Since Polygon's data is already naturally partitioned into daily sets, that is even easier than usual implement in this case

Example (Pythonish pseudo code):

```python
for file in files:
    ticks = load_ticks(file)
    base_ns = ticks[0].sip_ts
    base_dt = nsec_to_datetime(base_ns, tz='America/New_York')
    for tick in ticks:
        ts = base_dt + timedelta(seconds=(tick.sip_is - base_ns) / 1e9)
````

**Comment by pps83** [comment]
> Time conversion most certainly would dominate runtime if executed on every tick, but it is only necessary to recalculate the offset once per 86400 seconds.

Yes, that's true :)

> Example (Pythonish pseudo code):
> 
> ```python
> for file in files:
>     ticks = load_ticks(file)
>     base_ns = ticks[0].sip_ns
>     base_dt = nsec_to_datetime(base_ns, tz='America/New_York')
>     for tick in ticks:
>         tick_dt = base_dt + timedelta(seconds=(tick.sip_ns - base_ns) / 1e9)
> ```

I don't do python, but try to check some historical dates when [DST rules have changed for EST timezone](https://en.wikipedia.org/wiki/Eastern_Time_Zone#Daylight_saving_time). In regular C/C++ using `localtime` on windows to convert to local time won't produce proper results for dates before 2007: you'll end up with a few weeks each year where your open/close times will be shifted by 1 hour. Also, in pure c/c++ you cannot even convert to market time if you your PC isn't in NY timezone
