### ISSUE TITLE
Cannot subscribe to more than 43 symbols

### ISSUE THREAD

**Issue by benfrankstein** [polygon-io/issues#44]
**Client**
Polygon websocket client

**Issue**
The websocket client allows me to subscribe to 43 tickers. When i try to subscribe to 44 and more, the connection closes and the flow of market data never starts. I used dead volume stocks as well to see if it was a Buffer issue and it happened as well.
**Expected Result**
I expected to be able to subscribe to as many tickers as I can handle.
**Screenshots**

**Desktop (please complete the following information):**
Ubuntu / python

**Additional context**

**Comment by joshlang** [comment]
We connect to 3150 symbols at once, no prob
