### ISSUE TITLE
Aggs endpoint capped at 5000 bars

### ISSUE THREAD

**Issue by t73liu** [polygon-io/issues#45]
**URL**
https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2020-06-04/2020-07-04

**Result**
All minute bars for the last month.

**Expected Result**
Returned 5000 minute bars ranging from June 4th to June 12th.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Firefox

**Additional context**
Is the documentation missing a max # of bars or is the endpoint supposed to return the entire set of data?

Another minor grievance is the following minute bar, the volume ("v") is technically an integer but can trip up some JSON parsers. A mention of this in the API doc would be helpful.

```json
{"v":1.029145e+06,"vw":349.0938,"o":349.31,"c":348.78,"h":349.5,"l":348.05,"t":1591882200000,"n":6966}
```

**Comment by jrbell19** [comment]
While 5000 is the default limit for results, you can add '&limit=50000' to the api call to return the maximum results possible.

**Comment by pps83** [comment]
`"v":1.029145e+06` that's really weird bug. In c++, most parsers allow to retrieve by type and attempts to read a floating point number as an int or int64_t in most parsers throw an error.
@jrbell19 please change it to a proper int (and use 64 bit int for large nums instead)

**Comment by jrbell19** [comment]
I will make note of this. Thanks for the suggestion. 

 @pps83
