### ISSUE TITLE
UVXY Reverse Splits not Implemented

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#46]
Trying to reopen issue UVXY Reverse Splits not Implemented #30 (https://github.com/polygon-io/issues/issues/30). Which was closed without being fixed.

As noted in subsequent comments some splits are stills missing as 2011 price is 242695146 in 2020 it is 43.

**Comment by ryantjo** [comment]
Is there any news/updates on this. Is it being worked on?

**Comment by qrpike** [comment]
@jrbell19

**Comment by jrbell19** [comment]
Apologies for closing the issue prematurely. All of the splits for this ticker are in our DB, but they are definitely not being adjusted correctly. We will tackle this asap. Let me know if you see any more instances of this. 

For reference:
https://api.polygon.io/v2/reference/splits/UVXY?apiKey=
https://www.splithistory.com/uvxy/

**Comment by jrbell19** [comment]
After checking again, this doesn't appear to be an actual issue. Yahoo Finance is showing the same prices historically. Do you have a source of this data that is showing different prices? 

https://finance.yahoo.com/quote/UVXY/history?period1=1317686400&period2=1317859200&interval=1d&filter=history&frequency=1d

This is why I closed the issue originally. If you could provide any more information as to why this may be erroneous, we will continue to investigate.
