### ISSUE TITLE
Minute bars sometimes have wrong data

### ISSUE THREAD

**Issue by pps83** [polygon-io/issues#47]
**URL**
https://api.polygon.io/v2/aggs/ticker/SPY/range/1/minute/2019-01-02/2019-01-02?unadjusted=true&sort=asc&apiKey=xxx

There is one bar that has these values:

```
{"v":282676,"vw":246.9297,"o":247.08,"c":247.14,"h":247.15,"l":247.02,"t":1546440540000,"n":1402}
```

Note, that these values cannot be correct.
First of all, `vw` is ridiculously [isn't even mentioned in the docs](https://polygon.io/docs/#get_v2_aggs_ticker__ticker__range__multiplier___timespan___from___to__anchor). I guess it's volume weighted or average price. The problem with this bar is that `vw` price is lower than `l` price. Clearly, your code is buggy if it ends up with such wrong values. That also means that all other values of `vw` perhaps cannot be trusted as well.
Can you please check why you have such wrong values?

Similarly, on the same day:
```
{"v":633567,"vw":249.763,"o":249.43,"c":249.31,"h":249.45,"l":249.29,"t":1546447920000,"n":1094},
```
`vw` is higher than the `h`.

Note, that it's not some rare data error. Polygon clearly has a bug calculating `vw`, around 5% of bars have the error.

**Update:** seems more than 10% bars have the error.

**Comment by jrbell19** [comment]
We are investigating this, you're not the only user who has reported this. We will investigate and circle back with some kind of solution as soon as possible. 

Apologies for the inconvenience.

**Comment by pps83** [comment]
Any hints about expected time frame? Are you going to rebuild bars with proper volume weighted values or update API version to server correct values?

**Comment by qrpike** [comment]
So there is not a bug in the code and those values are correct as we interpret them. 

There are trade conditions which must be met for a trade to update the OHLC. More details about this can be found here ( https://polygon.io/blog/understanding-trade-eligibility/ ). 

When we calculate the VWAP we update it with any trade which is eligible to update the volume ( which is almost any ). So the VWAP is impacted by trades which may not be eligible to update the OHLC. This means that the VWAP can actually be outside of the OHLC range. 

We interpret VWAP as it's literal definition of "volume weighted average price". And for that reason do not apply trade conditions used in OHLC prices. 

If you believe this is incorrect, or think it should be changed. Please put in a separate 'enhancement' ticket and we can discuss more.

**Comment by pps83** [comment]
There is no way anybody could accept that volume weighted average can be outside [min, max] range. This is simply illogical, more over, 10% of minute bars have the error. I'd assume that some trades that do not affect OHLC with humongous volume would affect `vw`, but if that happens 10% of the time, then something is clearly wrong. This simply makes no sense

**Comment by qrpike** [comment]
@pps83 ~40% of trading happens off the exchanges ( TRF ), so 10% of aggs is not out of the question. Again, if you think this is incorrect put in an enhancement issue and we ( and others ) can voice their opinions.
