### ISSUE TITLE
Historical quote requests fail with some recent dates

### ISSUE THREAD

**Issue by isak-r** [polygon-io/issues#48]
**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/AAPL/2020-07-07?limit=10

**Result**
{
  "error": "Unknown database error ( Error Code: 001 )",
  "errorcode": "001",
  "status": "ERROR",
  "success": false
}

**Expected Result**
Quote data

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: 78

**Additional context**
Historical trades requests for the same date do work

**Comment by jrbell19** [comment]
Sorry you ran into this. We have since fixed the issue.
