### ISSUE TITLE
Reference tickers endpoint missing 7660 US stock tickers from grouped endpoint

### ISSUE THREAD

**Issue by clickingbuttons** [polygon-io/issues#5]
**URL**

https://api.polygon.io/v2/reference/tickers?sort=ticker&market=stocks&perpage=50&page=1
...
https://api.polygon.io/v2/reference/tickers?sort=ticker&market=stocks&perpage=50&page=706

https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2004-01-01
...
https://api.polygon.io/v2/aggs/grouped/locale/US/market/STOCKS/2020-05-01

**Result**
A list of 35259 tickers from the reference tickers endpoint, but 42919 tickers from the grouped endpoint.

**Expected Result**
A list of 42919 tickers from the reference tickers endpoint including the 7660 missing ones from 'AAA' to 'ZZZZ' that are in the grouped endpoint from 2004-01-01 to 2020-05-01. Here's the complete list of missing tickers: [grouped_not_tickers.txt](https://github.com/polygon-io/issues/files/4589765/grouped_not_tickers.txt)

**Additional context**
There are also many missing warrants and subclasses of symbols, like `MRTpA.CL`, but I don't expect the reference tickers endpoint to return these. To reproduce this list of tickers, you can run "Jack.java" at https://github.com/clickingbuttons/polyquest and then the "compare_tickers.py" script.

**Comment by jrbell19** [comment]
We just began redesigning / reengineering our tickers APIs, which will address issues like this.

**Comment by jrbell19** [comment]
These tickers have been removed from Grouped Daily. Sorry this took 3 years to close out @clickingbuttons

**Comment by clickingbuttons** [comment]
On 2011-06-07 the following appear in the grouped endpoint but 404 on ticker details for the same date:
```
PPLpU
NYBpU
HIWpB.CL
PSApI.CL
ZZZ
PETpD.CL
FTBpC.CL
AIVpU
BACpU
ZWZZT
CpU
SKF
TWQ
GJE.CL
ZVZZT
TWON
ZXZZT
```

Some are known test tickers and should be removed from the grouped daily endpoint. Determining that is a bit tricky since some tickers like "ZZZ" were used as tests in the past but are now real tickers.

**Comment by clickingbuttons** [comment]
Here's my list of test ticker regexes to filter these:
```
; https://www.nasdaqtrader.com/Content/ProductsServices/TRADING/TRF-Chicago-Test-Securities.xlsx
CBO
CBX
IBO
IGZ
ZBZX
ZEXIT
ZIEXT
ZVV
ZXIET
; More than the spreadsheet listed A, B, C, V, W, X are used.
Z[A-Z]ZZT
ZVZZC
ZWZZT
ZXZZT

; don't know where these came from but they're verified test tickers
[A-Z][A-Z]ZST
; keep in mind ZTSTF is a valid OTC
ZTST
ZZK
ZZV
;! end=2023-01-01
ZZZ

; Informal rule so far has been to not allow real tickers with "TEST" in their name.
.*TEST.*
```
