### ISSUE TITLE
Sockets are dropping messages

### ISSUE THREAD

**Issue by ArvindTrees** [polygon-io/issues#50]
I unsubscribed from multiple feeds, but one of the unsubscribes (MSFT) was ignored.
<img width="1194" alt="Screen Shot 2020-07-21 at 11 04 52 AM" src="https://user-images.githubusercontent.com/4358865/88093110-67edac00-cb46-11ea-95da-a50f9fc59580.png">

**Comment by jrbell19** [comment]
We'll take a loko into why this is occurring and push a fix as soon as possible. Thanks for bringing this to our attention.

**Comment by jrbell19** [comment]
Are you still experiencing these dropped messages?
