### ISSUE TITLE
Splits not implemented

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#51]
Below ticker/dates splits not implemented

ACN 2011-12-29 
AFL 2018-03-16
ACGL 2018-06-20 
AOS 2016-10-05
APH 2014-10-09 
CF 2015-06-17

**Comment by jrbell19** [comment]
Will add these today. Thanks for providing these. Apologies for the inconvenience.

**Comment by jrbell19** [comment]
I went ahead and corrected the existing splits, and added the missing ones. 

The data should be adjusted properly now.
