### ISSUE TITLE
QQQ Gap in Aggs

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#52]
For QQQ I get zero data returned for the period 2004-11-30 - 2011-03-23 for the 1-minute aggregate

**Comment by jrbell19** [comment]
It looks like this is because the tick data is missing from this period as well. We will backfill this data as soon as possible. 

Thanks for pointing this out.

**Comment by jiosec** [comment]
four months passed, a simple issue like this not fixed yet?

**Comment by qrpike** [comment]
Duplicate of: https://github.com/polygon-io/issues/issues/118 

Please see resolution in that ticket.
