### ISSUE TITLE
Stock Splits not Implemented

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#53]
The below stock splits do not seem to be implemented for the 1-minute aggregates:

 CHDN 2019-01-25

CHD 2016-09-01  

CIM 2015-04-06  

CLR 2014-09-10

CMCSA 2017-02-17  

CNC 2015-02-19

COLM 2014-09-26

COP 2012-04-30 

CTSH 2014-03-07  

ELS 2019-10-15 

EOG 2014-03-31 

ERIC 2008-06-09 

EW 2015-12-11 

EW 2020-05-29 

EXPO 2015-06-04  

FAST 2019-05-22  

FFIN 2014-06-02  

FISV 2013-12-17  

FNB 2009-01-02 

GGG 2017-12-27 

GIL 2015-03-27 

GNTX 2014-12-31 

GPN 2015-11-02  

HAIN 2014-12-29 

HBI 2015-03-03 

HLF 2018-05-14 

HOMB 2016-06-08 

HRL 2016-02-09 

HSIC 2017-09-14 

HTA 2014-12-30 

HTHT 2018-05-24 

IART 2017-01-03 

IBN 2014-12-08 

ICE 2016-11-03 

IDXX 2015-06-15 

INFY 2014-12-05 

INFY  2015-06-24

INFY  2018-09-11

ISRG 2017-10-05  

JNPR 2017-11-29  

KR 2015-07-13 

LBTYA 2005-09-06 

LNT 2016-05-19  

LOGM 2020-03-16  

MANH 2014-01-10

MA 2014-01-21

MGA 2015-03-25

MIDD 2014-06-26

MNST 2016-11-09

MPC 2015-06-10

MRO 2011-06-30

NJR 2015-03-03

NKE 2015-12-23

NSP 2017-12-18

OTEX 2014-02-18

OTEX 2017-01-24

ROL 2018-12-10

ROST 2015-06-11

SBUX 2015-04-08

SKX 2015-10-15

SLGN 2017-05-26

SNN 2014-10-14

SSNC 2016-06-24

TAL 2017-08-15

TJX 2018-11-06

TLK 2016-10-25

TREX 2014-05-07

TREX 2018-06-18

TRN 2014-06-19

TTC 2016-09-16

TU 2020-03-17

UFPI 2017-11-14

UGI 2014-09-05

UNP 2014-06-06

VIPS 2014-11-03

V 2015-03-18

WCN 2017-06-16

WIT 2017-06-12  
 
WY 2010-07-19

**Comment by ryantjo** [comment]
I was wondering if there was any progress or an ETA on this?
Thx

**Comment by jrbell19** [comment]
Unfortunately not yet. They are all in our DB, they just aren't being applied correctly. We're going to change the way Splits are applied/ adjusted so we can fix them all at once. 

I'll be sure to keep you posted on the progress of that.
