### ISSUE TITLE
ETF Splits not Implemented

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#54]
The below ticker/date splits appear not to have been implemented

BWX 2016-09-28

DDM 2015-05-19

DDM 2018-05-23

FAS 2015-05-19

IBB 2017-11-30

IGIB 2018-08-07

IJR 2017-01-18

IWR 2018-10-25

NUGT 2016-08-24

QLD 2015-05-19

QLD 2017-07-14

SCO 2017-01-11
 
SSO  2015-05-19

TNA 2017-04-28

TQQQ 2018-05-23

UDOW 2015-05-19

UPRO 2015-05-19

UPRO 2018-05-23

URTY 2017-07-14

UWM 2017-07-14

UYG 2015-05-19

UYG 2018-05-23

VCSH 2020-03-19

XBI 2015-09-10

XRT 2015-09-10

ZSL 2015-11-12

**Comment by jrbell19** [comment]
Once the Symbols API complete ( ~6 weeks ) it will allow us to go in and add all missing splits, as well as ensure they are kept up to date and accurate.
