### ISSUE TITLE
Minute Snapshot data is inaccurate or missing

### ISSUE THREAD

**Issue by ishaybas** [polygon-io/issues#6]
**URL**
https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers

**Result**
I collected every minute during trading hours for the last 3.5 months (starting January 31st) for all symbols and I can say that in 35% of the cases the high and low figures for the minute are 0, in 8,6% of the cases the last trade value is smaller than the low for the minute, and in 8,8% of the rest of the cases the last trade is higher than the minute high value. All in all in 53% of the minute snapshots (I have a total of 222,217,824) the minute high/low data doesn't match the lastTrade number for the same minute.

**Expected Result**
The lastTrade data should match the minute aggregate h/l/o/c numbers

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser curl

**Comment by jrbell19** [comment]
Not all trades are eligible to update the OHLC values for aggregated data, so the snapshot results may not match the last trade. 
We have a table that shows which trade conditions determine a trade to be eligible to update the OHLC values here: https://polygon.io/glossary/us/stocks/conditions-indicators

**Comment by qrpike** [comment]
@ishaybas Can you confirm if the trades you're referring to are eligible for aggregate updates?

**Comment by ishaybas** [comment]
Sadly I cannot as I don't have all the information for the trade.
But even if some are not eligible it does not explain why in 35% of the
cases the minute data is 0 during trading hours.
Should I provide some examples with timestamps and you could maybe check on
your side?
Keep in mind, that my data was not downloaded while pulling historical
data, but rather requesting "live" the current snapshot.
Maybe the missing data is just a delay in calculating the minute bars.

**Comment by qrpike** [comment]
There is a 4-5second delay in broadcasting minute bars. 

Can you explain further what you mean by "minute data is 0 during trading hours"?

**Comment by ishaybas** [comment]
here is an example where minute data is 0, but there is lastTrade data:

"day":{"c":0,"h":0,"l":0,"o":0,"v":0,"vw":0},"lastQuote":{"P":34.78,"S":5,"p":34.69,"s":5,"t":1589206080574755732},"lastTrade":{"c":[17,41],"i":"52983525231415","p":34.69,"s":100,"t":1589203800254067521,"x":11},"min":{"c":0,"h":0,"l":0,"o":0,"v":0,"vw":0},"prevDay":{"c":34.9145,"h":34.9145,"l":34.5834,"o":34.5834,"v":1656,"vw":34.6411},"ticker":"FITE","todaysChange":-0.224,"todaysChangePerc":-0.643,"

another example where minute h is 0, but the rest of the minute data is ok:

"day":{"c":12.35,"h":12.8185,"l":11.8,"o":12.81,"v":29567,"vw":12.299},"lastQuote":{"P":12.36,"S":1,"p":12.29,"s":2,"t":1589214300000611549},"lastTrade":{"c":[14,41],"i":"52983543583304","p":12.34,"s":100,"t":1589213068070781920,"x":11},"min":{"c":12.35,"h":0,"l":12.35,"o":12.35,"v":100,"vw":12.35},"prevDay":{"c":12.75,"h":12.99,"l":11.71,"o":11.76,"v":147896,"vw":12.2884},"ticker":"REV","todaysChange":-0.41,"todaysChangePerc":-3.216,"

If you need more examples or infos just let me know!

Thank you

**Comment by qrpike** [comment]
We have updated streaming aggregates to no longer broadcast if any of the values are '0'.
