### ISSUE TITLE
Snapshot endpoint returns 404 during market hours and before midnight

### ISSUE THREAD

**Issue by skitle** [polygon-io/issues#60]
**URL**
https://api.polygon.io/v2/snapshot/locale/us/markets/stocks/tickers/AAPL?apiKey=

**Result**
"404 page not found"

**Expected Result**
The snapshot data for all/specific tickers

**Additional context**
Requesting data from the snapshot endpoint after the market closes and prior to midnight, or currently while the market is open, returns a 404 response. Attempted numerous ticker symbols as well as for all at once with the same result.

**Comment by jrbell19** [comment]
Are you still running into this? I have not been able to replicate the 404 issue during the normal market hours.
