### ISSUE TITLE
v2/aggs/ticker randomly returns random data

### ISSUE THREAD

**Issue by yazabaza** [polygon-io/issues#62]
**URL**
`https://api.polygon.io/v2/aggs/ticker/' + symbol + '/range/1/minute/' + startDate + '/' + endDate`

**Result**
My code calls the above URL in a loop to download 1-minute bars, one day at a time, using startDate = endDate. On random occasions the returned bars have dates very different (years apart) from the requested date. Furthermore, the price data on these occasions appears to be from a different symbol than the requested symbol (spots checks revealed that the requested symbol never had prices in the returned range over the past 10 years.

**Expected Result**
Most of the time the API returns a full day of 1-minute bars for the requested symbol and date. On random occasions, however, the returned bars are for different dates and apparently different symbols. Furthermore, this is not consistently repeatable; multiple runs produce different random errors.

**Screenshots**
Here is example output from 3 different runs where it caught returned bar dates different than the requested bar dates. These were run with the exact same inputs and code. These examples requested symbol TLT, but I have observed the same problem on other symbols, e.g. GLD, VXX. I have not tested many symbols. For brevity I have _not_ included here the full dump of all bars for each bad day, but you can run the code and get that.

	barDate != requestedDate
	requestedDate 2015-03-24 barDate 2020-08-06
	bad bar:
	{'v': 4199, 'vw': 31.9119, 'o': 31.92, 'c': 31.9121, 'h': 31.92, 'l': 31.9, 't': 1596732120000, 'n': 48}
	all bars in this request:
	.
	.
	.
	barDate != requestedDate
	requestedDate 2012-10-05 barDate 2020-07-27
	bad bar:
	{'v': 4114, 'vw': 2.0122, 'o': 2.055, 'c': 2.01, 'h': 2.055, 'l': 2.01, 't': 1595856600000, 'n': 4}
	all bars in this request:
	.
	.
	.
	barDate != requestedDate
	requestedDate 2011-10-28 barDate 2020-07-30
	bad bar:
	{'v': 2609, 'vw': 8.6699, 'o': 8.67, 'c': 8.67, 'h': 8.67, 'l': 8.67, 't': 1596115800000, 'n': 3}
	all bars in this request:
	.
	.
	.
My code:

	import requests, datetime, csv, pytz, os, sys, json

	def processBars(bars, directory, requestedDate):
		for bar in bars:
			# Flag error if returned bar date != requested date
			dateTimeObj = datetime.datetime.fromtimestamp(bar[timeStampName] / timeStampDivisor, tz=pytz.timezone('America/New_York'))
			barDate = dateTimeObj.date()
			if barDate != requestedDate:
				print('barDate != requestedDate')
				print('requestedDate', requestedDate, 'barDate', barDate)
				print('bad bar:')
				print(bar)
				print('all bars in this request:')
				print(json.dumps(bars, indent=2))
				sys.exit()

	def polygonAggregateBars(symbol, startDate, endDate):
		URL = 'https://api.polygon.io/v2/aggs/ticker/' + symbol + '/range/1/minute/' + startDate + '/' + endDate
		r = requests.get(url=URL,
			params={'apiKey': APCA_API_KEY_ID,
						'search': symbol,
						'locale': 'us'
						})
		if r.status_code != requests.codes.ok:
			print(r.raise_for_status())
		return r.json()['results']

	APCA_API_KEY_ID = 'XXXXXX'
	directory = '/path/to/directory'
	symbol = 'TLT'
	timeStampDivisor = 1e3
	timeStampName = 't'
	columnNames = ['t', 'o', 'h', 'l', 'c', 'v']
	dateInitial = datetime.date(2010,1,4)
	dateFinal =   datetime.date(2020,8,7)
	currentDate = dateInitial
	appendToExistingFile = False

	while True:
		currentDateString = currentDate.strftime('%Y-%m-%d')
		print(currentDateString)
		bars = polygonAggregateBars(symbol, currentDateString, currentDateString)
		if len(bars) > 0:
			processBars(bars, directory, currentDate)
		else:
			print('no data for this date')
		currentDate += datetime.timedelta(days=1)
		if currentDate > dateFinal:
			print('reached final date')
			break

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser: Not applicable
 - Python 3.8

**Additional context**

**Comment by yazabaza** [comment]
FYI I have enhanced my code such that if any bar within the one-day batch returned from the API has a date other than the requested date then I re-request the bars for that day, and loop until all returned bars have the correct date. When this error occurs, usually the correctly dated bars are returned on the second (repeated) API call for that day, but so far I have seen one case where it took 2 repeats (total of 3 calls) to get the correctly-dated bars for a day.

**Comment by jrbell19** [comment]
Hmm, thanks for the detailed report. We will investigate to see what may be causing the issue. 

Apologies for the troubles.

**Comment by yazabaza** [comment]
Note that the same API is missing data (returns nothing) for 1-minute bars for symbol VXX from 2019-01-30 to 2019-05-05 inclusive. Should I create a different github issue for that?

**Comment by ryantjo** [comment]
I had the same issue on VXX. It is a rather complex story but the result is the ticker changed to VXXB for this period.

**Comment by neoform** [comment]
I'm seeing this as well, I filed a bug as well (I had not seen this one).

https://github.com/polygon-io/issues/issues/65

**Comment by ryantjo** [comment]
Is there any update from Polygon on this???

 This is a major issue - the API is totally unusable if it returns random data... Multiple customers are reporting this and there is no comment on a fix. I can't really see how the historic data API is of any use in its current form.

**Comment by jembl** [comment]
is this fixed, this is a big issue for me

**Comment by qrpike** [comment]
This should have been solved with the release of the new aggregates API: https://polygon.io/blog/aggs-api-updates/ on Dec 4th 2020. 

Closing this, please re-open if you continue to see these issues.
