### ISSUE TITLE
Stream Minute Bars - VWAP Docs Unclear

### ISSUE THREAD

**Issue by neoform** [polygon-io/issues#63]
On the "Aggregate Bars" REST API https://polygon.io/docs/#get_v2_aggs_ticker__ticker__range__multiplier___timespan___from___to__anchor

According to the docs, this is an expected response:

```
{
    "T": "AAPL",        // Ticker symbol
    "v": 31315282,      // Volume
    "o": 102.87,        // Open
    "c": 103.74,        // Close
    "h": 103.82,        // High
    "l": 102.65,        // Low
    "t": 1549314000000, // Unix Msec Timestamp ( Start of Aggregate window )
    "n": 4              // Number of items in aggregate window
}
```

In reality, the response does not contain `T` (no big deal, since the request contains it), but there is an additional field not listed in the docs: `vw`, for which there is no explanation. 

I looked at the websocket API, and it *does* contain a `vw` field which is apparently the `VWAP`:

https://polygon.io/sockets

```
// Stocks Aggregate:
{
    "ev": "AM",             // Event Type ( A = Second Agg, AM = Minute Agg )
    "sym": "MSFT",          // Symbol Ticker
    "v": 10204,             // Tick Volume
    "av": 200304,           // Accumulated Volume ( Today )
    "op": 114.04,           // Today's official opening price
    "vw": 114.4040,         // VWAP (Volume Weighted Average Price)
    "o": 114.11,            // Tick Open Price
    "c": 114.14,            // Tick Close Price
    "h": 114.19,            // Tick High Price
    "l": 114.09,            // Tick Low Price
    "a": 114.1314,          // Tick Average / VWAP Price
    "s": 1536036818784,     // Tick Start Timestamp ( Unix MS )
    "e": 1536036818784,     // Tick End Timestamp ( Unix MS )
}
```

Two issues:

1. In the REST API, is the `vw` value the VWAP?
2. Why are there two different VWAP values in the websocket? I'm unclear what "Tick Average / VWAP Price" is, since the explanation doesn't make much sense. If the VWAP is `114.4040` and the tick average (aka: 'typical price', aka: HLC/3) would end up being `((114.19 + 114.09 + 114.14) / 3)` divided by the VWAP Price, ergo: `((114.19 + 114.09 + 114.14) / 3) / 114.4040 = 0.99769` whereas the listed value is `114.1314`.

Am I reading this incorrectly?

**Comment by jrbell19** [comment]
So this is a bit unclear at the moment, I will make sure we address this in the docs to eliminate further confusion. 

1. The 'vw' value in the rest API is VWAP, yes. 
2. The two vwap values in the websocket docs are referring to the daily vwap and that tick's vwap. So the 'vw' field shows the vwap for the entire day's trading session, while 'a' is showing the vwap for the minute/second bar that is being broadcasted. 

Sorry for the confusion.
