### ISSUE TITLE
Ticker Change Mapping 

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#64]
It would be very useful to be able to map ticker changes. 

Three main scenarios : 
1. Where a company changes ticker symbol and continues trading as normal.    

2. Mergers (useful to know that one ticker was merged into another ticker)

3. Where a ticker symbol is recycled (currently these look like long gaps in the historic data during the period between the disuse of the ticker and its reassignment).

**Comment by jrbell19** [comment]
This is actually something that we are planning to implement with our upcoming symbols API. This project will be apart of the next few sprints. At this time we are expecting 6-7 weeks for the ticker mapping functionality to be in place.

**Comment by brianschardt** [comment]
@jrbell19 amazing. This will help me tremendously. Any way to get Alpha access? We can also pay more to our subscription

**Comment by brianschardt** [comment]
Also just to have it said, to have the ratio with which it converts at is important to e.g.

trch -> mmat changes at 1.8 shares or something like that

**Comment by matichenor** [comment]
Hi @brianschardt , unfortunately I want to provide you with an update that the ticker change mapping feature will not make our Q1 deliveries as expected.  I am working with the polygon.io engineering team to see what we can do to get this capability delivered on a future roadmap.  We'll keep you posted.

**Comment by ivan416** [comment]
Any updates on this feature? Thanks in advance.

**Comment by jrbell19** [comment]
Check out our TIcker Events endpoint which provides the timeline of events for the entity associated with the given ticker, CUSIP, or Composite FIGI. 

https://polygon.io/docs/stocks/get_vx_reference_tickers__id__events

We will continue to make improvements over this API. Closing this issue
