### ISSUE TITLE
Intermittently Incorrect Data Returned By Historical Aggregates (Bars)

### ISSUE THREAD

**Issue by neoform** [polygon-io/issues#65]
**URL**
https://api.polygon.io/v2/aggs/ticker/TJX/range/1/MINUTE/2020-08-27/2020-08-27?apiKey=XXXXXXXX

**Result**

I'm requesting `1 MINUTE` bar data for `TJX` for the date `2020-08-27` (just one day's worth). 

Most of the time the bar data is correct (as far as I can tell, since all the timestamps are all from the same day, `2020-08-27`), but intermittently, I get results that do not belong.

Sample data:

```
{"ticker":"TJX","queryCount":404,"resultsCount":404,"adjusted":true,"results":[
{"v":206,"vw":14.49,"o":14.49,"c":14.49,"h":14.49,"l":14.49,"t":1486132200000,"n":1},
{"v":560,"vw":14.4,"o":14.4,"c":14.4,"h":14.4,"l":14.4,"t":1486132320000,"n":3},
{"v":274,"vw":14.4552,"o":14.475,"c":14.475,"h":14.475,"l":14.475,"t":1486133160000,"n":4},
{"v":200,"vw":14.48,"o":14.48,"c":14.48,"h":14.48,"l":14.48,"t":1486134720000,"n":1},
[...]
{"v":89845,"vw":53.7268,"o":53.75,"c":53.68,"h":53.77,"l":53.67,"t":1598558340000,"n":924},
{"v":32669,"vw":53.67,"o":53.67,"c":53.67,"h":53.67,"l":53.67,"t":1598558640000,"n":20},
{"v":14341,"vw":53.67,"o":53.67,"c":53.67,"h":53.67,"l":53.67,"t":1598559840000,"n":1},
{"v":100,"vw":53.5,"o":53.5,"c":53.5,"h":53.5,"l":53.5,"t":1598560860000,"n":1}
],"status":"OK","request_id":"d4e95fce95b78d698c5ef9c2a3196f6e"}
```

As you can see, the first bar's timestamp is `1486132200000` which is `Friday, February 3, 2017 2:30:00 PM`, either the bar does not belong in this result set, or the data contains errors.

------

Another example:

```
{"ticker":"TJX","queryCount":404,"resultsCount":404,"adjusted":true,"results":[
{"v":426,"vw":53.2008,"o":53.2472,"c":53.2472,"h":53.2472,"l":53.2472,"t":1598529600000,"n":6},
{"v":416,"vw":52.7502,"o":52.75,"c":52.75,"h":52.75,"l":52.75,"t":1598530020000,"n":2},
{"v":762,"vw":53.1692,"o":53.17,"c":53.16,"h":53.17,"l":53.16,"t":1598531580000,"n":6},
{"v":125,"vw":53.25,"o":53.25,"c":53.25,"h":53.25,"l":53.25,"t":1598532420000,"n":1},
[...]
{"v":2817,"vw":26.5784,"o":26.58,"c":26.56,"h":26.6,"l":26.56,"t":1587407280000,"n":34},
{"v":1102,"vw":26.544,"o":26.55,"c":26.525,"h":26.55,"l":26.525,"t":1587407340000,"n":27},
{"v":5732,"vw":26.574,"o":26.535,"c":26.59,"h":26.6,"l":26.535,"t":1587407400000,"n":68},
{"v":1918,"vw":26.6202,"o":26.6,"c":26.62,"h":26.645,"l":26.59,"t":1587407460000,"n":30}],
"status":"OK","request_id":"4e4fca85068be116616ce2ae549f5617"}
```

As you can see the timestamps start out on `2020-08-27` but the last bunch of bars are from `April 20, 2020`.

**Expected Result**
I should only be getting aggregate bars that for `2020-08-27`.

**Additional context**
This only happens a small fraction of the time. I noticed it happening when doing hundreds of calls in a row, it would suddenly start happening a lot, then I wouldn't see it happen for thousands of requests after that.

I've had to put a sanity-check in my code to make sure the results are what I'm expecting, since every now and then, the results have timestamps that are wildly incorrect.

This error is reproducible by repeatedly submitting the same TJX/2020-08-27 request (might take several thousand requests), eventually a bad result will come up. I was able to reproduce this several times. This also works with other stock symbols and dates, I'm just using TJX because that's the one I noticed it happening on most recently.

I can provide the full (non-truncated) responses if needed.

**Comment by neoform** [comment]
Related: #68 #62 #69

**Comment by jrbell19** [comment]
We are aware of this behavior and are working to resolve the underlying issue. Sorry for the confusion.

**Comment by larimer** [comment]
Another datapoint for you here, as I'm also seeing this issue. In my case, I'm requesting minute-aggregate data for market hours of one day using Unix epoch milliseconds  -- example: `https://api.polygon.io/v2/aggs/ticker/LABD/range/1/minute/1555939800000/1555963200000`

Usually the bad results begin with aggregate minutes from an incorrect date (usually a random day in Sep or Oct 2020) and finish with minutes from the correct/requested date range, but sometimes the bad results are entirely outside the requested range (but again are usually Sep or Oct 2020).

I noticed the metadata in a bad response is actually correct -- the `resultsCount` in the bad response matches the `resultsCount` in a good response (a second attempt of the same request), and the actual count of *bad* `results` items matches the `resultsCount`:

Try 1:
```
{ "ticker": "LABD", "resultsCount": 384, "results": [ -- 384 BAD RESULTS -- ] }
```
Try 2:
```
{ "ticker": "LABD", "resultsCount": 384, "results": [ -- 384 GOOD RESULTS -- ] }
```

Also, the bad data appears to be for the wrong *symbol* (though again the metadata `ticker` value is correct).

I too have noticed that the bad responses come in bunches -- no bad responses for many thousands of requests, then many bad responses in a short time span.

I'm using a simple sanity check and retrying the request if the response appears to be bad...but that doesn't give me any warm/fuzzies, so please fix this as soon as possible.

**Comment by qrpike** [comment]
This should have been solved with the release of the new aggregates API: https://polygon.io/blog/aggs-api-updates/ on Dec 4th 2020. 

Closing this, please re-open if you continue to see these issues.
