### ISSUE TITLE
Incorrect Timestamps For 1 Minute Bars (3:59pm bar should contain daily closing price, not 4:00pm bar)

### ISSUE THREAD

**Issue by neoform** [polygon-io/issues#67]
**Summary**

The `Aggregates (Bars)` API endpoint data does not appear to align correctly with the `Daily Open / Close` API endpoint data.

**Context**

When looking at the *close price* for a given stock via the `Daily Open / Close` API, the price given appears to match the *close price* from the `4:00pm` bar of the `Aggregates (Bars)` API; it **should** be matching the `3:59pm` bar.

**Expected Behavior**

Given that the `Aggregates (Bars)` API: 

1. The first bar of the data-set has a `5:00am` timestamp
2. The last bar of the data-set has a `7:59:00pm` timestamp

It only makes sense then that the stock trading day should be summarized by 1 minute bars with timestamps `9:30:00am` through `3:59:00pm` (one bar per minute).  

Therefore the closing price of the `3:59:00pm` bar should in fact be the closing price for that trading day.

**Actual Result**

The daily close price is taken from the `4:00:00pm` minute bar (which I would interpret as being the first bar of the post-market trading session).

**Example**

Using symbol `WMT` and looking at data from `2020-08-17` :

`Daily Open / Close` says the close price is `135.6`

`Aggregates (Bars)` (1 minute bars) when viewing the `3:59pm` bar (timestamp: `1597694340000`), it says the close price is `135.77`

*Incidentally...*

`Aggregates (Bars)` (1 minute bars) when viewing the `4:00pm` bar (timestamp: `1597694400000`), it says the close price is `135.6` (the same price as listed by the `Daily Open / Close` API.

-----

Request: `https://api.polygon.io/v2/aggs/ticker/WMT/range/1/MINUTE/2020-08-17/2020-08-17?apiKey=XXXXXXXX`:

Response: 
```
[...]
{"v":358287,"vw":135.8102,"o":135.99,"c":135.77,"h":136.01,"l":135.61,"t":1597694340000,"n":2400},
{"v":117302,"vw":135.6038,"o":135.6,"c":135.6,"h":136.25,"l":135.6,"t":1597694400000,"n":74},
[...]
```

Request: `https://api.polygon.io/v1/open-close/WMT/2020-08-17?apiKey=XXXXXXXX`:

Response:
```
{"status":"OK","from":"2020-08-17","symbol":"WMT","open":134.35,"high":136.13,"low":133.85,"close":135.6,"volume":26722704,"afterHours":134.28,"preMarket":132.8}
```

**Additionally**

I confirmed via nasdaq.com that the close price returned by `Daily Open / Close` is correct.

**Comment by jrbell19** [comment]
I see what you're saying, however the Market Center Official Close trade (c:15) in this case happened at 04:00:01.743 (t:57601743299), which signifies the beginning of extended hours trading. Because this eligible trade occurred after 4:00:00pm the bar will be populated for that minute, which I believe is the desired functionality on our end. 

Looping Q in to confirm.

**Comment by neoform** [comment]
That's quite surprising. Is it normal for a trade to take place after 3:59:59.999pm and be considered part of the trading day? Is it because the trade was initiated prior to 4:00:00.000pm?

**Comment by jrbell19** [comment]
Yes, this is quite normal. The market doesn't close exactly at 4:00:00pm, it technically closes whenever that Market Center Official Close trade is executed. Oftentimes this is microseconds after 4:00, but because it is still after 4:00, we still generate the bar for that minute. 

Hope this helps clear the confusion up.

**Comment by neoform** [comment]
Is there any way for me to identify when the market closed? AFAIK, the polygon API doesn't provide the "this is the last trade of the day" flag for a given bar.

**Comment by jrbell19** [comment]
Not through the aggregates endpoint, no. You could listen to the websocket stream for the last ~30 seconds or so to look for the trades with condition code 15 though.
