### ISSUE TITLE
Cross-Symbol Data Corruption

### ISSUE THREAD

**Issue by yazabaza** [polygon-io/issues#68]
**URL**
https://api.polygon.io/v2/aggs/ticker/

### REVISED 2020-9-2
**I am removing the original description of this issue regarding a large number of missing bars and changing this to refer only to cross-symbol data corruption.**

**Result**
In the time period starting 2009-2-1 and ending 2020-8-7 there appears to be an inverse correspondence of missing bars between symbols, meaning that when a bar is missing for one symbol it is present for another, and vice versa. The attached spreadsheet shows present/missing bars for 3 symbols (IWM, TLT, GLD). Blanks indicate missing bars. Rows in the table are in time order but _not contiguous_. This is small subset of all rows in which the bar is missing for at least one of these 3 symbols. The data show that when a TLT is present then the bar for one of the other symbols is absent. This seems to indicate some kind of database corruption.

**Desktop (please complete the following information):**
 - OS: macOS, python 3.8.5, using requests module

[Polygon.Missing.Bars.xlsx](https://github.com/polygon-io/issues/files/5165069/Polygon.Missing.Bars.xlsx)

**Comment by yazabaza** [comment]
This just got more complicated. In addition to the majority of TLT 1-minute bars being absent, I discovered a relationship between the presence/absence of TLT bars and other symbol bars being present or absent. The attached spreadsheet shows present/absent bars for 3 symbols (IWM, TLT, GLD). Blanks indicate missing bar data. Rows in the table are in time order but not contiguous. This is small subset of all rows in which the bar is missing for at least one of these 3 symbols. The data show that when a TLT is present then the bar for one of the other symbols is absent. This seems to indicate some kind of database corruption.

[Polygon Missing Bars.xlsx](https://github.com/polygon-io/issues/files/5158813/Polygon.Missing.Bars.xlsx)

**Comment by jrbell19** [comment]
We are aware of this behavior and are working to resolve the underlying issue. Sorry for the confusion.

**Comment by qrpike** [comment]
This should have been solved with the release of the new aggregates API: https://polygon.io/blog/aggs-api-updates/ on Dec 4th 2020. 

Closing this, please re-open if you continue to see these issues.
