### ISSUE TITLE
Random Data Inserted into Aggs Request

### ISSUE THREAD

**Issue by ryantjo** [polygon-io/issues#69]
When running multiple requests for historic aggregates data, random data is inserted to the result. 

Hard to provide specific code examples as this behaviour is random since the same request will not result in incorrect data when repeated. It is persistent, however, and seems to occur once per 30-40 requests in my testing.

I was requesting 1-min aggs on tickers MELI, ASML.  The incorrect data is usually several days (at least) from a different ticker and a different year.

**Comment by neoform** [comment]
Sounds like the same as what I saw. https://github.com/polygon-io/issues/issues/65

**Comment by jrbell19** [comment]
We are working to address this now. When you experienced this, what kind of timeframe were you pulling minute data for? One day, a few weeks, months? What is the rate at which you are hitting the endpoint? 

Any additional information about the circumstances around how you are querying the data will help.

**Comment by smartFunX** [comment]
In my case I wanted to get  1-min aggs for several years of data for 16 stocks in parallel. The querying range I used is 1 day (if I choose larger range e.g. 1 month, the API somehow drops a lot of data). Almost every stock data at the end got the some random data, however the fraction is relatively small, less than 1 day of bad minutes. Here is some example for AAPL symbol:
...
date, open, high, low, close, volume, timestamp
2004-03-05 10:50,1.9,1.9429,1.8929,1.8944,1161916.0,1078501800     | Expected data
2004-03-05 10:51,1.895,1.9572,1.8922,1.8972,472850,1078501860     | Expected data
2020-08-06 11:08,33.83,33.93,33.83,33.93,561,1596726480               | Random minute entry started
....
2020-08-06 15:02,33.96,33.96,33.96,33.96,439,1596740520               
2020-08-06 15:03,33.98,34,33.98,34,690,1596740580                          | Random minute entry finished
2004-03-05 13:34,1.9265,1.9265,1.9236,1.9243,331576,1078511640    | Expected data

**Comment by ryantjo** [comment]
In my case, I was not querying in parallel but in sequence. Requested 10 years data (requesting one month of 1-min bars per query) . Hitting the endpoint again only when the prior query data was returned so not sure the frequency but about once per 3-5 seconds.

It seems that the random data was usually from 2020.

**Comment by vgoklani** [comment]
Same issue here; we ended up filtering the data looking for garbage, and then re-download the corrupted files.

**Comment by tr8dr** [comment]
I have seen the same problem.  I now run my queries in a loop, examining the returned data programmatically to see whether there is an odd gap or backward dated bar in the sequence.   Looking forward to a fix.

**Comment by jrbell19** [comment]
This issue was fixed by our Aggregates API update from 11/25/2020: https://polygon.io/blog/aggs-api-updates/

Let me know if you see anything else out of the ordinary.
