### ISSUE TITLE
Missing several days of data for /v2/aggs/range/5/minute calls

### ISSUE THREAD

**Issue by himmxt** [polygon-io/issues#72]
**URL**
1. https://api.polygon.io/v2/aggs/ticker/OIH/range/5/minute/2020-08-11/2020-09-11?sort=asc&apiKey=KEY

2. https://api.polygon.io/v2/aggs/ticker/AAPL/range/5/minute/2020-08-11/2020-09-11?sort=asc&apiKey=KEY

**Result**
1. Missing data between: 2020-09-02 14:50:00 -> 2020-09-10 09:45:00
2. Missing data between: 2020-08-19 15:44:00 -> 2020-09-10 04:04:00

**Expected Result**
Expect several rows of data for the missing dates

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
I think I am having this issue for all tickers I'm testing.

**Comment by jrbell19** [comment]
Hi there, 

This is actually a pretty easy fix. The default limit of results is 5000, but you can increase this to the max value of 50,000 by adding "&limit=50000" to the query. 

This will give you a wider window of data to pull from, and will return all of the results for this specific request. 

1. https://api.polygon.io/v2/aggs/ticker/OIH/range/5/minute/2020-08-11/2020-09-11?sort=asc&apiKey=KEY&limit=50000
2. https://api.polygon.io/v2/aggs/ticker/AAPL/range/5/minute/2020-08-11/2020-09-11?sort=asc&apiKey=KEY&limit=50000

Sorry for the confusion. We are going to make this clear on the documentation soon.
