### ISSUE TITLE
Incorrect historical trades data

### ISSUE THREAD

**Issue by gms008** [polygon-io/issues#73]
**URL**
https://api.polygon.io/v2/ticks/stocks/nbbo/TWTR/2020-09-03?limit=50000

**Result**
These are the trades I get from Polygon for the second starting at 9:42:01am:
```1599140521755000 6 42.21
1599140521759000 6 42.21
1599140521759000 1 42.22
1599140521759000 2 42.22
1599140521759000 3 42.22
1599140521759000 3 42.22
1599140521759000 6 42.22
1599140521759000 5 42.22
1599140521759000 5 42.22
1599140521759000 6 42.22
1599140521759000 6 42.22
1599140521759000 9 42.22
1599140521759000 10 42.22
1599140521759000 11 42.22
1599140521759000 20 42.22
1599140521759000 21 42.22
1599140521759000 20 42.22
1599140521759000 12 42.22
1599140521759000 13 42.22
1599140521759000 4 42.22
1599140521759000 11 42.22
1599140521759000 11 42.22
1599140521760000 9 42.22
1599140521760000 4 42.22
1599140521765000 3 42.22
1599140521765000 2 42.22
1599140521794000 3 42.22
```

None of these trades occur at the best ask - they are all at the best bid. In fact, I can't find a single trade (scanning visually) that occurs at the best ask. This can't be right.

I checked with both TDA and IB and they both list these as the trades that occurred at this second:
TDA:
```
1599140521365000 150 42.2141
1599140521759000 200 42.23
1599140521759000 100 42.23
1599140521759000 100 42.23
```
IB:
```
Time: 1599140521, TickAttribLast: PastLimit: 0, Unreported: 0, Price: 42.214100, Size: 150, Exchange: FINRA, SpecialConditions:     
Time: 1599140521, TickAttribLast: PastLimit: 0, Unreported: 1, Price: 42.219700, Size: 4, Exchange: FINRA, SpecialConditions:    I
Time: 1599140521, TickAttribLast: PastLimit: 0, Unreported: 0, Price: 42.230000, Size: 200, Exchange: NYSE, SpecialConditions:     
Time: 1599140521, TickAttribLast: PastLimit: 0, Unreported: 0, Price: 42.230000, Size: 100, Exchange: ISLAND, SpecialConditions:     
Time: 1599140521, TickAttribLast: PastLimit: 0, Unreported: 0, Price: 42.230000, Size: 100, Exchange: DRCTEDGE, SpecialConditions:  F  
Time: 1599140521, TickAttribLast: PastLimit: 0, Unreported: 1, Price: 42.225000, Size: 1, Exchange: FINRA, SpecialConditions:    I
```
Aside from IB showing unreported trades, TDA and IB show the same data. What is up with the polygon trades? 

**Expected Result**
Expect correct data.

**Screenshots**
How come there are only trades at the best bid?
![Screenshot from 2020-09-12 21-59-30](https://user-images.githubusercontent.com/71043667/93008507-70110900-f543-11ea-8bd2-69708ec99018.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version 85.0.4183.83

**Additional context**
My trial has run out. I am holding off on subscribing until I get an answer here and on: https://github.com/polygon-io/issues/issues/41

I would like to double check Polygon's data in case I downloaded it incorrectly, but I don't want to sign up for a subscription just to confirm that, just in case I happen to be right. I am actually leaning towards myself being wrong here - I can't imagine this to be a legitimate error.

**Comment by freepi** [comment]
Whew, you really scared me there for a second.  The reason the "trades" are only on the best bid price is because ... duh duh duh... what you're reporting as trades are the bids from Polygons NBBO endpoint, so it seems your code has a bug. If you check the data from Polygon's trade endpoint, the data matches IB perfectly over the period you specify: https://api.polygon.io/v2/ticks/stocks/trades/TWTR/2020-09-03?timestamp=1599140521159000000&limit=10

**Comment by gms008** [comment]
Ok, I figured something like that, thanks for checking - I couldn't check with my free api key. I think I will sign back up for the subscription now, but would still appreciate some sort of response soon on issue #41.

**Comment by jrbell19** [comment]
This had me worried as well until I read over it a few times. We receive the trade data directly from the SIPs ( CTA and UTP ), which are the sources of truth for trade and quote data. We do not alter this data in any way, so there is no way for this data to be wrong. 

I believe you would need level 2 data to really determine whether a trade was executed on the bid or ask side. We do intend on offering this data sometime next year though.
