### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by margeaucs** [polygon-io/issues#77]
**Client**
Which WebScoket client are using? - I don't know how to answer this question.

**Issue**
Hi I am a new python coder. What am I doing wrong? How come I am receiving "authentication failed"? Thank you!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]

**Comment by neoform** [comment]
You should probably remove your API key from the code when posting this online.
