### ISSUE TITLE
Significant delay in tick data

### ISSUE THREAD

**Issue by 2young-2simple-sometimes-naive** [polygon-io/issues#79]
**URL**
curl "https://api.polygon.io/v2/ticks/stocks/trades/SPY/2020-09-22?apiKey=xxxxxxxxxxxxxxxxx" > test.out

**Result**
The latest tick timestamp shows it's 9:55am. I am testing it at 4:30pm.

**Expected Result**
It should show more recent data

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser curl
 - Version curl 7.64.1 (x86_64-apple-darwin19.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.39.2 Release-Date: 2019-03-27

[test.out.txt](https://github.com/polygon-io/issues/files/5264085/test.out.txt)

**Comment by neoform** [comment]
You probably need to paginate your results with `timestamp`.

**Comment by jrbell19** [comment]
@neoform is correct. The results are limited to the first 50,000 trades of the day, so you will need to paginate the results from that last timestamp onward to get the next 50,000 trades. Even if you are properly paginating the results it is still not guaranteed to be near real time. 

We suggest consuming the messages from the ( T. ) [Websocket](polygon.io/sockets) channel for access to the most recent trades in real time.

**Comment by 2young-2simple-sometimes-naive** [comment]
Thanks for the replies. I found the solution. For anyone interested use reverse =True to get most recent data.
