### ISSUE TITLE
Missing historic quote data

### ISSUE THREAD

**Issue by M00NSH0T** [polygon-io/issues#8]
Over the past few weeks, I've been doing some backtesting using your historic quotes data on 215 symbols (all are in the russell 3k, so big companies), and there are several days  where one or more companies are missing. This is all through the '/v2/ticks/stocks/nbbo/{ticker}/{date}' endpoint. 

Here's my log of errors during download:
2019-09-18
problem ticker:  TSN
problem ticker:  WFC
problem ticker:  WMB
problem ticker:  WY
2018-09-28
problem ticker:  WFC
2018-09-26
problem ticker:  STZ
2018-09-13
problem ticker:  UNP
2018-06-18
problem ticker:  HD
2018-05-31
problem ticker:  MSFT
2018-05-07
problem ticker:  TXN
2017-12-26
problem ticker:  SHW
2017-12-19
problem ticker:  EBAY
2017-12-05
problem ticker:  NEE
2017-12-01
problem ticker:  JPM
2017-11-29
problem ticker:  TGT
2017-11-22
problem ticker:  LUV
2017-11-06
problem ticker:  SRE
2017-09-18
problem ticker:  VZ
problem ticker:  WBA
problem ticker:  WEC
2017-05-10
problem ticker:  SBUX
2017-04-12
problem ticker:  GILD
2017-03-30
problem ticker:  CCL
2017-03-02
problem ticker:  ADI
2017-02-21
problem ticker:  PPG
problem ticker:  PPL              
2017-02-17
problem ticker:  C
problem ticker:  SHW
2017-02-15
problem ticker:  HSY
problem ticker:  SY
2017-02-08
problem ticker:  BMY
2017-02-06
problem ticker:  CPRT
problem ticker:  WMB
2017-01-30
problem ticker:  ED
2017-01-23
problem ticker:  CVX
2017-01-19
problem ticker:  CSX
2017-01-18
problem ticker:  BK
problem ticker:  KO
2017-01-03
problem ticker:  AMGN
2016-12-27
problem ticker:  CRM
2016-12-14
problem ticker:  NKE
2016-10-21
problem ticker:  APD
2016-10-13
problem ticker:  PEP
2016-10-12
problem ticker:  CHD
problem ticker:  CINF
2016-10-04
problem ticker:  AXP
2016-09-27
problem ticker:  OKE
2016-08-29
problem ticker:  AIG
2016-08-05
problem ticker:  ED
problem ticker:  EFX
problem ticker:  EL
2016-05-13
problem ticker:  NEM
2016-05-06
problem ticker:  VTR
problem ticker:  XOM
2016-05-03
problem ticker:  BAC
problem ticker:  LVS
problem ticker:  PFE
2016-04-29
problem ticker:  INTC
2016-04-15
problem ticker:  XLNX
2016-04-08
problem ticker:  CPRT
problem ticker:  PG
2016-04-06
problem ticker:  COF

**Comment by jrbell19** [comment]
We'l l go in and make this data available as soon as possible, apologies for the inconvenience.

**Comment by M00NSH0T** [comment]
thank you very much. That will fix things for me, but you might want to run some additional checks on your end as this is likely indicative of a bigger issue. Like maybe 'select distinct date' for each company in your db and check against a master date list, or something that tallies the number of quotes per company per day and then look for anomalies. These errors are only from trying to get data for 213 companies and as you can see, there were a fair number of missing days. And these are only the cases where I got no hits for the whole day for a particular company. If these 213 companies are representative, there are likely thousands of additional missing sets (date / ticker pairs).

**Comment by qrpike** [comment]
@M00NSH0T I have tried several of these tickers and get data back. eg:
- https://api.polygon.io/v2/ticks/stocks/nbbo/MSFT/2018-05-31?limit=10&apikey=
- https://api.polygon.io/v2/ticks/stocks/nbbo/TSN/2019-09-18?limit=10&apikey=
- https://api.polygon.io/v2/ticks/stocks/nbbo/HD/2018-06-18?limit=10&apikey=

 Can you post a URL ( without your API key ) to one where the data is missing.

**Comment by M00NSH0T** [comment]
yeah when I fist ran it (17 days back), those were all missing, but now they do appear to be working. Is there a reason why some companies on some days might not work when others do? I've encountered this several times before. Like this past week, I was getting errors trying to get historic data for AAPL from earlier in May (and it would also hang on last_quote calls for AAPL as well, perhaps coincidentally, perhaps not), but now it works. Other tickers for the same days worked fine though and the results would be the same over several attempts over the course of the day. Is it indicative of some of your servers dropping from the cluster or something like that?

**Comment by qrpike** [comment]
@M00NSH0T Our data is stored on a per day batching, so if 1 ticker works, they should all work. If you see this happen again, please reopen this with the error codes or any additional information you can provide.
