### ISSUE TITLE
Unmatched ticker details whereas historical trades/quotes exists

### ISSUE THREAD

**Issue by RobinhoodFR** [polygon-io/issues#81]
**URL**
https://api.polygon.io/v1/meta/symbols/TARGETTICKER/company?apiKey=...

**Result**
Ticker details are missing for a lot of symbols whereas historical trades/quotes exist in the Polygon.io database.

**Expected Result**
If historical data exist for a given ticker, I except to see ticker details on it using https://api.polygon.io/v1/meta/symbols/TARGETTICKER/company?apiKey=...

**Screenshots**
Not needed

**Desktop (please complete the following information):**
Not needed

**Additional context**
For your information, I made a test on the S&P 500 components. The following tickers are concerned:

BRK.B
LIN
RTX
BKNG
TFC
LHX
TT
CARR
OTIS
CTVA
WELL
AMCR
VIAC
PEAK
J
BF.B
CBRE
LUMN
NLOK
EVRG
BKR
HWM
GL

**Comment by jrbell19** [comment]
This will be addressed by our new Symbols API that we are currently working to complete.

**Comment by RobinhoodFR** [comment]
Thanks for your answer. Waiting for that. ++

**Comment by aspromatis** [comment]
When will the new Symbols API be available to fix this issue?

**Comment by MSara13** [comment]
Hi all do we have a timeline on this API fix issue?  There are numerous delisted equities symbols also missing (LEH, BSC) which can cause survivorship bias.  Alternatively, can Polygon provide a full symbol list so we can at least access the data?

**Comment by tr8dr** [comment]
What is the ETA on this?   I am finding quite a few stocks which have an entry in the database, but have incorrect stock split information (i.e. missing one or more splits).   This is a big problem for backtesting

**Comment by nerka-kurt** [comment]
Same here. Waiting for the fix.

**Comment by c0x65o** [comment]
Any update on this? For stating that you have 100% market coverage, this seems like a big issue. A timeline would be much appreciated for all on this thread.

**Comment by jrbell19** [comment]
We are shooting to release the updated tickers API by the end pf this quarter. This will resolve these issues, as well as allow us to fix / update all of the issues with reference data. 

Apologies for the ongoing issues. We really appreciate your patience with us on this.

**Comment by jrbell19** [comment]
This issue has been addressed by our updated Ticker Details vX endpoint: https://polygon.io/docs/get_vX_reference_tickers__ticker__anchor
