### ISSUE TITLE
VWAP prices are not adjusted in daily aggregates

### ISSUE THREAD

**Issue by furechan** [polygon-io/issues#82]
**URL**
/v2/aggs/ticker/AAPL/range/1/day/2015-01-01/2020-09-24&unadjusted=false

**Result**
{'ticker': 'AAPL',
 'status': 'DELAYED',
 'queryCount': 503,
 'resultsCount': 501,
 'adjusted': True,
 'results': [{'v': 95938824.0,
   'vw': 221.8698,
   'o': 55.25,
   'c': 55.105,
   'h': 55.9375,
   'l': 54.94,
   't': 1537934400000,
   'n': 1},
...

**Expected Result**
'vw': 221.8698 should have been adjusted same way as the other prices

**Comment by jrbell19** [comment]
Hi there, 

We just pushed a fix for the maladjusted vwap price, and it is working as expected. Apologies for the inconvenience.
