### ISSUE TITLE
Missing Daily Open / Close and Ticker details for selected stocks

### ISSUE THREAD

**Issue by RobinhoodFR** [polygon-io/issues#85]
**URL**
https://api.polygon.io/v1/open-close/VERY/2020-10-06?apiKey=XXXX
https://api.polygon.io/v1/open-close/BBXIA/2020-10-06?apiKey=XXXX
https://api.polygon.io/v1/open-close/ADRO/2020-10-06?apiKey=XXXX

https://api.polygon.io/v1/meta/symbols/VERY/company?apiKey=XXXX
https://api.polygon.io/v1/meta/symbols/BBXIA/company?apiKey=XXXX
https://api.polygon.io/v1/meta/symbols/ADRO/company?apiKey=XXXX

**Result**
No data =>"Not found" tag for both urls. 

Example with daily open \ close => "https://api.polygon.io/v1/open-close/VERY/2020-10-06?apiKey=XXXX"

{
  "status": "NOT_FOUND",
  "from": "",
  "symbol": "",
  "open": 0,
  "high": 0,
  "low": 0,
  "close": 0,
  "volume": 0,
  "afterHours": 0,
  "preMarket": 0
}

Example with ticker details => "https://api.polygon.io/v1/meta/symbols/VERY/company?apiKey=XXXX"

{
  "error": "Not Found"
}

**Expected Result**
To get daily open / close data and ticker details data

**Screenshots**
Not needed

**Desktop (please complete the following information):**
Not needed

**Additional context**
So daily open/close data ("fresh" that means at least yesterday's data) and ticker details data are missing for at least 3 stocks (VERY-BBXIA-ADRO) wich are part of the Russell 2000 Index. I guess the issue also exist for others stocks, for sure.

Thanks by advance for your time++

**Comment by jrbell19** [comment]
Looking into this now. Daily aggregates are available, so I'm unsure why this data would not populate. 

The issue with the ticker details will be addressed by our Symbols API.

**Comment by jrbell19** [comment]
This is resolved. VERY data is available. The other tickers were not actively traded on this date:

https://api.polygon.io/v1/open-close/VERY/2020-10-06?adjusted=true&apiKey=
https://api.polygon.io/v3/reference/tickers/ADRO?date=2020-10-06&apiKey=
