### ISSUE TITLE
Historical data never matches streaming data

### ISSUE THREAD

**Issue by smartFunX** [polygon-io/issues#88]
**Client**
Using the client from Github https://github.com/polygon-io/client-python
Version 0.1.6.

**Issue**
The streaming data that I'm getting for the stock "A" (any other stock as well) doesn't match the historical data from REST API.
The prices (close, open, high, low) are sometimes matching or very close, however the volumes are very different.
Example:
From Rest API for stock "A"
{"v":630,"vw":105.4064,"o":105.41,"c":105.41,"h":105.41,"l":105.41,"t":1602617040000,"n":16},
From streaming data:
 v: 10775; o: 105.41; c: 105.39; h: 105.41; l: 105.36; t: 1602617040000;

As you can see the volume is 17 times bigger in the streaming data than in the historical data.
I

**Expected Result**
Historical and streaming data should more or less match 

**Desktop (please complete the following information):**
 - OS: OS X

**Comment by jrbell19** [comment]
Hi there, 

This issue is related to the duplicate volume flowing through the websocket feed for NYSE traded symbols. It is an issue that we are actively working to address. 

Apologies for the inconvenience.

**Comment by nerka-kurt** [comment]
@jrbell19 Is there any update on this issue?

**Comment by jrbell19** [comment]
Yes, we were able to fix the duplicate trades that were being broadcasted, so the real time aggregates should be much closer to the aggregates you see through our Aggregates endpoint. 

They are not guaranteed to be the same, as there are trades that are reported late, or trade corrections that can alter the initial aggregate values. The aggregates will be recalculated at the end of the trading day to account for these messages.
