### ISSUE TITLE
REST API for "tickers"

### ISSUE THREAD

**Issue by mankeskes** [polygon-io/issues#9]
Hi - I am seeing something strange when using the REST API for "tickers". https://api.polygon.io/v2/reference/tickers?sort=ticker&type=cs&market=STOCKS&locale=us&perpage=50&page=1&apiKey=YOUR_API_KEY. Count is only 235 and the results seem to include only ticker starting with W, X, Y and Z. Any idea?
"page": 1,
  "perPage": 50,
  "count": 235,
  "status": "OK",
  "tickers": [
    {
      "ticker": "WADV",
      "name": "Wireless Advantage Inc Common Stock",
      "market": "STOCKS",
      "locale": "US",
      "type": "CS",
      "currency": "USD",
      "active": true,
      "primaryExch": "GREY",
      "updated": "2020-03-30",
      "codes": {
        "figiuid": "EQ0010295500001000",
        "scfigi": "BBG001S87270",
        "cfigi": "BBG000DKG4K2",
        "figi": "BBG000DKG4K2"
      },
      "url": "https://api.polygon.io/v2/tickers/WADV"
    },

**Comment by mankeskes** [comment]
Hi Jack - Are you able to reproduce the problem? Thanks

**Comment by quantic-cloud** [comment]
There is a major discrepancy between the `type` field from `Tickers` (`/v2/reference/tickers`) and `Ticker Details` (`/v1/meta/symbols/{symbol}/company`). The count of common stocks in `Ticker Details` is > 5000, which seem closer to reality.

**Comment by simsman2695** [comment]
Hey All,

So it seems like some stocks have the "ticker" attribute and some do not!!

![Selection_110](https://user-images.githubusercontent.com/8283104/87980437-7aa1ab80-ca88-11ea-9d84-c8c81b5bc68e.png)
