### ISSUE TITLE
Error: getaddrinfo ENOTFOUND api.polygon.io - When calling APIs

### ISSUE THREAD

**Issue by rmary007** [polygon-io/issues#91]
**URL**
https://api.polygon.io/v2/reference/tickers?active=true&sort=ticker&perpage=100&market=STOCKS&page=1&apiKey=xxxxx

**Result**
Error: getaddrinfo ENOTFOUND api.polygon.io

**Expected Result**
Need to get the records without fail.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome , Firefox

**Additional context**
Whenver I start calling Poygon APIs , I used to get the above issue, which halt my program execution.

**Comment by clickingbuttons** [comment]
This is a DNS problem on your end @rmary007 . Both 1.1.1.1 (Cloudflare) and 8.8.8.8 (Google) can resolve `api.polygon.io` fine. Here are instructions to change it for [Windows 10.](https://developers.google.com/speed/public-dns/docs/using)
