### ISSUE TITLE
Closing price seen in 16:01 (NY) 1min bar rather than 16:00 (NY) bar

### ISSUE THREAD

**Issue by tr8dr** [polygon-io/issues#95]
**URL**
https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2020-10-30/2020-10-30/?sort=asc&apiKey=...

**Result**
I am seeing a closing price of 109.07 for the 2020-10-30T20:00 UTC bar (whereas should be 108.86).  The next bar (after market close) is for 20:01 UTC and closes with 108.86.

**Expected Result**
The 2020-10-30T20:00 UTC bar should have a closing price of 108.86 and not 109.07.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A, using python
 - Version: Python 3.7

**Additional context**
I suspect that the closing trades are delivered with latency on the SIP feed (a few ms after 2020-10-30T20:00.000) and allocated into the next bar.   This produces issues when attempt to rollup 1min bars into daily, hourly, etc.

**Comment by jrbell19** [comment]
This is actually expected behavior. issue #67
