### ISSUE TITLE
All Minute Aggs Missing For 2014-01-23

### ISSUE THREAD

**Issue by neoform** [polygon-io/issues#99]
No data is being returned for Jan 23, 2014 (regardless of time unit provided).

**URL**
https://api.polygon.io/v2/aggs/ticker/GOOG/range/1/minute/2014-01-23/2014-01-23?sort=asc&apiKey=XXXXX
https://api.polygon.io/v2/aggs/ticker/MSFT/range/1/minute/2014-01-23/2014-01-23?sort=asc&apiKey=XXXXX
https://api.polygon.io/v2/aggs/ticker/T/range/1/minute/2014-01-23/2014-01-23?sort=asc&apiKey=XXXXX
https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2014-01-23/2014-01-23?sort=asc&apiKey=XXXXX

Try any other symbol and the result is the same.

**Result**
I've confirmed via other historical site's historical data that Jan 23, 2014 was a regular trading day.

Eg: https://finance.yahoo.com/quote/AAPL/history?period1=1388534400&period2=1391126400&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true

**Expected Result**
Agg data for 2014-01-23 be returned.

**Comment by clickingbuttons** [comment]
It looks like this is working now.

**Comment by neoform** [comment]
It does indeed seem fixed now.
